### ISSUE TITLE
Clang-format/tidy failing on macOS 11 arm64

### ISSUE THREAD

**Issue by GoodnatureBeacon** [microsoft/vscode-cpptools#10282]
### Environment

- OS and Version: Mac OSX 11.3.1
- VS Code Version: 1.74.0
- C/C++ Extension Version: 1.13.7
- Other extensions you installed (and if the issue persists after disabling them):  N/A
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

### Bug Summary and Steps to Reproduce

Bug Summary:

My formatter is no longer working, the output simply reads: 
Formatting failed:
/Users/michael/.vscode/extensions/ms-vscode.cpptools-1.13.7-darwin-arm64/bin/../LLVM/bin/clang-format -style=file -fallback-style=LLVM --Wno-error=unknown -assume-filename=[PATH TO FILE]

When I run the clang-format in the terminal I get the following error: 
dyld: Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEE4openEPKcj
  Referenced from: /Users/michael/.vscode/extensions/ms-vscode.cpptools-1.13.7-darwin-arm64/bin/../LLVM/bin/clang-format (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

The formatter has been working correctly until today, has there been a recent update to the extension that could be causing this issue?

The only thing I can think of on my end is that I recently uninstalled Xcode to free up space on my computer (the command line tools are still installed). Could that cause this error?

I've tried restarting VSCode
I've tried restarting my machine
I've tried uninstalling and re-installing the command line tools

Steps to reproduce:
1. Make change to file
2. Save file (with format on save turned on)

### Expected behavior

Format the file correctly

### Code sample and Logs

```shell
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
            ],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/Users/michael/Projects/Development_Tools/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-g++",
            "cStandard": "c99",
            "cppStandard": "c++11",
            "intelliSenseMode": "macos-gcc-arm",
            "mergeConfigurations": false,
            "browse": {
                "path": [
                    "${workspaceFolder}/**"
                ],
                "limitSymbolsToIncludedHeaders": true
            }
        },
        {
            "name": "Test",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "macos-clang-arm64"
        }
    ],
    "version": 4
}
```

**Comment by Colengms** [comment]
Hi @GoodnatureBeacon .  Thanks for reporting this.  It looks like our macOS arm64 build of clang-format and clang-tidy needs to specify a `CMAKE_OSX_DEPLOYMENT_TARGET`.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.13.8

**Comment by GoodnatureBeacon** [comment]
Hey there, 

First of all, thanks for the quick response and sorry for not including that I was using an M1 but that is correct. 

I just installed the update and am still getting the same error. I got a new error message on startup too that reads:

`Failed to spawn IntelliSense process: -2147418105`

Still getting the same error when I try and run it manually in the terminal

**Comment by sean-mcmanus** [comment]
@GoodnatureBeacon Sorry about that -- it looks like we built with the wrong target of 20 (the darwin version) instead of 11 (the OS version). We can rebuild it (maybe for 1.13.9, not sure yet) and also look into if we're able to test it on an older mac 11 OS.

The `Failed to spawn IntelliSense process: -2147418105` is fine because we should automatically retry -- do you only see 1 of those messages or do you see 9 or more in a row?

**Comment by sean-mcmanus** [comment]
I figured out we can "test" the fix via running `otool -l` and looking for "minos 11.0", which is what our cpptools binary shows, but clang-format/tidy shows 20.1.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.13.9
