### ISSUE TITLE
Enable an insert mode that never replaces (like TypeScript instead of VS)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10613]
This issue prevails, even with `"editor.suggest.insertMode": "insert", "[cpp]": { "editor.suggest.insertMode": "insert" }`:

![actual](https://user-images.githubusercontent.com/9538837/221896188-806284f2-69f7-4ba7-b872-81c5ac34faa1.gif)

I would expect the editor with the above settings to never ever ever delete characters, e. g. expect the following outcome:

![expected](https://user-images.githubusercontent.com/9538837/221896339-a6c4b8a1-ef0a-4273-99a9-81ab58473bef.png)

_Originally posted by @Longhanks in https://github.com/microsoft/vscode-cpptools/issues/10553#issuecomment-1448365253_

**Comment by sean-mcmanus** [comment]
It looks likes this would be fixed by switching to returning https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#insertReplaceEdit (instead of the textEdit that is currently returned).

**Comment by Longhanks** [comment]
I think this goes against the spirit of the setting and should be considered a bug, rather than a feature request. Maybe the VS Code devs can chime in to clarify the proper idea of `"insertMode": "insert"`.

**Comment by sean-mcmanus** [comment]
@sean-mcmanus Sure, we can consider it a bug, but I'm not sure when we'll get around to fixing it (although the issue is closed, it could still get fixed if we decide to prioritize it later on).

**Comment by loikkant** [comment]
This is how the issue replicates in the "folder" settings:
![Screencast from 16 08 2023 10 21 12](https://github.com/microsoft/vscode-cpptools/assets/37328774/c948eeef-3959-4651-a659-5cdfde935b0b)

When one selects the non-default mode (insert), it swaps back to the default (replace) as soon as the focused UI element is changed. To me this makes it seem like a bug even further.

I find it extremely annoying that the "insert" mode is not working.

**Comment by Adnn** [comment]
I'm joining from #11353, is there anything we can do to help prioritize this issue?

**Comment by Adnn** [comment]
By the way, as there existed previous comments discussing the intention of the settings and whether it was a bug:

>   // Controls whether words are overwritten when accepting completions. Note that this depends on extensions opting into this feature.
>   //  - insert: Insert suggestion without overwriting text right of the cursor.
>   //  - replace: Insert suggestion and overwrite text right of the cursor.

(from [the documentation of the default settings](https://code.visualstudio.com/docs/getstarted/settings#_default-settings))

**Comment by sean-mcmanus** [comment]
@Adnn It's already been prioritized.

**Comment by albertcaldas84** [comment]
Hi, I've been always finding pretty annoying that either pressing tab/enter the autosuggestion feature always replace the text on the right of the cursor, I always want to "insert". The cpp extension ignores the insertmode setting from vscode and overwrites it. Is it going to be fixed? Thanks!

**Comment by n808** [comment]
Trying to figure out how to fix this annoying behavior. Why is the setting "editor.suggest.insertMode": "insert", ignored?
It was "replace" but I changed the global and all languages, yet it deleted the next word when I am inserting auto-completed code.

**Comment by phogy** [comment]
Hi, chiming in on this! I find it very annoying, and there must be quite a lot of us. How this is not the behavior everyone expects is beyond me, but at least respect the setting. It did use to work at some point, of this I'm certain, so it's not a feature request imho.

**Comment by Adnn** [comment]
Yes, this definitely worked as intended at some point.

**Comment by bobbrow** [comment]
This is actively being worked on and you won't have to wait too much longer.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.19.0 (pre-release)

**Comment by albertcaldas84** [comment]
I'm still experiencing the same issue with pre-release 1.19.2.

**Comment by Adnn** [comment]
@albertcaldas84 I just checked back on this issue, and it works for me with pre-release 1.19.2.
Did you make sure to set the `cpp` `insertMode` to `insert`? For some reason, the default for Cpp is `replace` (by opposition to the "general" default, which is `insert`, and the language specific value takes precedence).

To set the value for Cpp, I aded the following entry to my `settings.json`:

```
{
    ...
    "[cpp]": {
        "editor.suggest.insertMode": "insert"
    }
}
```

**Comment by albertcaldas84** [comment]
If I add this to the settings.json it works. I didn't have any entry, which should assume that "insert" was the default value.

**Comment by Adnn** [comment]
> I didn't have any entry, which should assume that "insert" was the default value.

The default value for `cpp` language is `replace` (unlike the "general" default, but the cpp value takes precedence when you edit cpp). This is why this is why setting this explicitly is required.

**Comment by bobbrow** [comment]
> For some reason, the default for Cpp is replace (by opposition to the "general" default, which is insert, and the language specific value takes precedence).

I apologize in advance for the history lesson, but we chose "replace" even before the VS Code setting existed. This aligned better (though not exactly) with how C++ in Visual Studio behaves.  When VS Code introduced the setting they reached out to us and there was a vote about what the default value for the setting would be.  We narrowly lost the vote but were given a way to keep our behavior by overriding the default for c and cpp files.  We recently suggested a new value "[languageDefined](https://github.com/microsoft/vscode/issues/176324)" so that we could keep our default and also not require the weird language setting syntax to change it, but it didn't clear the triage bar.
