### ISSUE TITLE
Most Recent Update killed Intellisense (Can't find any declarations)

### ISSUE THREAD

**Issue by perks** [microsoft/vscode-cpptools#1076]
Is there a way to revert to an older version?

**Comment by sean-mcmanus** [comment]
You can try the older version at http://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/cpptools/0.12.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage (renaming the zip to vsix and using the Install from vsix command).

However, we're not aware of any regression like this, so we'd appreciate more info. It sounds like your symbol database may not be populating correctly.

**Comment by perks** [comment]
Below is my cpp configuration that is relevant

```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/usr/include/c++/4.2.1",
                "/usr/local/include",
                "/usr/include",
                "${workspaceRoot}/include"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include/c++/4.2.1",
                    "/usr/local/include",
                    "/usr/include",
                    "${workspaceRoot}/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "${workspaceRoot}/.vscode/browse.VC.db"
            },
```

On the older version header files inside my workspace root folder where being picked up automatically (GoToDefinition, etc would work). With newest update it can no longer find the them and Problem output console reports that it cannot find the imports in the browsepath.

**Comment by perks** [comment]
![screen shot 2017-09-27 at 4 58 30 pm](https://user-images.githubusercontent.com/1820298/30937549-21830dd0-a3a5-11e7-8669-6b43d106a5f8.png)

For example here is header file layout in the project 

I also tried adding

`${workspaceRoot}/remill` to the browsepath to no avail. Is it recursive?

**Comment by sean-mcmanus** [comment]
Yes, browse.path is recursive. Can you verify if an older version fixes the issue for you? 0.13.0 will remove old items from the database if they're not found on disk. Does opening the file that contains the symbols still not make the symbols available? Does ${workspaceRoot}/.vscode/browse.VC.db appear to be many MB in size.

**Comment by hamparawa** [comment]
I do also seem to have this issue in Windows with the recent update. The same project was working without any issue before the update, now Cpp.Intellisense crashes with a notification that it will not restart again.

When I close the VSCode and open again, it works for some time, and crashes again with 10-15mins of work.

I'm not sure this would do any help, but my BROWSE.VC.DB file is around 60MB in size.

**Comment by sean-mcmanus** [comment]
@hamparawa Have you tried going back to the previous 0.12.4 version? Our crash telemetry shows 0.13.0 is crashing about 50% less than 0.12.4 in the 3 days after both were released (with roughly the same number of activations), so I believe 0.13.0 is more stable in general. It's possible something in your code has changed to hit a scenario where our IntelliSense crashes. The best way to help us fix this would be to get a small isolated repro of the code that causes a crash.

Which process is crashing? Microsoft.VSCode.CPP.Extension.exe or Microsoft.VSCode.CPP.IntelliSense.Msvc.exe? If you get a message about not restarting again, then it's not the IntelliSense process that is crashing. Your database size is fine.

**Comment by sean-mcmanus** [comment]
Wait, I'm seeing crashes with the new signature help and document highlight feature we shipped in 0.13.0. Okay, looks like that's what you're hitting. You can set  "editor.occurrencesHighlight": false to prevent crashes in that, but unfortunately, there is no way to disable the signatureHelp...other than to be careful when you type "(".

**Comment by perks** [comment]
@sean-mcmanus Reverting the change back to 12.4 and using Tag parsing works fine -- although I had to delete database and specify a new location and the editor seemed to have weird behaviour until the db was rebuilt

**Comment by lorak41** [comment]
Same situation for me, reverting to 12.4 and deleting database helped.

**Comment by bobbrow** [comment]
We have released fixes for the reference highlighting and signature help crashes in 0.13.1. Please let us know if you continue to have issues with IntelliSense on the latest version.

**Comment by sean-mcmanus** [comment]
We're still seeing a crash when invoking signature help with 0.13.1 (although it's possible it crashes less often if we're hitting a different crash from the one we fixed). Is anyone able to provide a repro? We might need to add a setting to disable this feature until we can make sure it's stable. The reference highlight crash appears to have been fixed.

**Comment by lorak41** [comment]
No, it fixed my problem. Thank you!

Cheers,

Karol

**Comment by bobbrow** [comment]
I got a repro.  If you re-invoke signature help with `(` or `<` when you have already typed some of the arguments, but there is an extra `]` or `}` in the signature somewhere (syntax error) before adding another `[` or `{`, it will crash.

**Comment by bobbrow** [comment]
We released 0.14.0 with a fix for the second issue. Please let us know if you continue to have issues.
