### ISSUE TITLE
Duplicate message appeared in output window when delete “exe” for Compiler path on Windows

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode-cpptools#12445]
### Environment

VSCode 1.90.2+ C/C++ Extension 1.21.0 pre-release)

### Bug Summary and Steps to Reproduce

**More info**:
Repro platform: Windows
Repro languages: ENU and loc languages

**Steps to reproduce**:
1. Create a new folder named 'Test' and open it in VScode
2. Open the command palette-> Type "C/C++: Edit Configurations(UI)" and hit enter
3. Delete "exe" for "Compiler path"
4. Check the output info for "C/C++ Configuration Warnings"

**Expected result**:
Only one message appeared

**Actual result**:
Duplicate message appeared:
[7/5/2024, 10:27:44 AM] Unable to resolve configuration with compilerPath "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.".  Using "cl.exe" instead.
[7/5/2024, 10:27:44 AM] Unable to resolve configuration with compilerPath "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.".  Using "cl.exe" instead.
![Cpp_Dup](https://github.com/microsoft/vscode-cpptools/assets/37648162/65e7159e-1722-457f-87e2-4b8a24394e3b)

Whole process:
![Cpp_dupOutput](https://github.com/microsoft/vscode-cpptools/assets/37648162/1f5bfca5-e321-479f-a2a3-bcd95e1d7b7b)

### Configuration and Logs

```shell
not related
```

**Comment by sean-mcmanus** [comment]
@PhoebeTf Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.22.0

**Comment by Ashley-Li** [comment]
Tested on C/C++ 1.22.0 (pre-release), this issue still repro, please see below test result, do we need to be re-open this?
![Verify_12445](https://github.com/user-attachments/assets/f0242e74-c8ee-4f2c-81ba-07ab0dd9b064)

**Comment by sean-mcmanus** [comment]
@PhoebeTf Interesting, I saw it show 2 errors one time too, but then when I retried I got only 1 error. Seems like there's some random bug that causes it to still repro sometimes.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.22.3
