### ISSUE TITLE
[Loc] Inconsistent translation in command and walkthrough page for “build” 

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode-cpptools#12443]
### Environment

VSCode 1.90.2+ C/C++ Extension 1.21.0 pre-release)

### Bug Summary and Steps to Reproduce

**More info**:
- Repro platform: Windows, Linux, Mac
- Repro languages: CHS, PTB,TRK
- Not repro language: CHT, JPN, KOR,ITA, ESN, FRA, PLK, DEU, RUS, CSY

**Steps to reproduce**:
1. Create a new folder named 'Test' and add a cpp file named "main.cpp"
2. Open the folder 'Test' with VScode, change the display language to CHS
3. Open the command palette-> Type "Welcome: Open Walkthrough..." and hit enter
4. Select the "Get Started with C++ Development"
5. Check the string ‘cl.exe - Build and debug active file’ status in 4th part _(Run and debug your C++ file)_
6. Open file "main.cpp"
7. Click the play button in the top right corner of the editor.
8. Check the command ‘C/C++: cl.exe - Build and debug active file’

**Expected result**:
“build” in command and walkthrough with same translation
_Such as on CHT windows version:_
![image](https://github.com/microsoft/vscode-cpptools/assets/37648162/1f770f4a-704a-4bb5-8601-cf194aa2ff09)

**Actual result**:
Inconsistent translation in command and walkthrough for “build” 
_Such as on CHS windows version:_
Command: “cl.exe - **生成**和调试活动文”   Walkthrough page: “cl.exe - **构建**和调试活动文件”
![image](https://github.com/microsoft/vscode-cpptools/assets/37648162/63dda8f9-bb25-4930-a737-84347165b71a)

### Configuration and Logs

```shell
loc issue not related to log
```

**Comment by browntarik** [comment]
Thank you for reporting this issue, this has been filed with our internal localization team (VS: 985108). Please track this issue for updates.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.22.9

**Comment by Yingzi1234** [comment]
@PhoebeTf @sean-mcmanus This issue hasn't been solved, we can still reproduced this issue on latest C/C++ version v1.23.0(pre-release), you can get the details below. We reopened the issue. Thank you!

CHS:
![Image](https://github.com/user-attachments/assets/85a59c83-eb81-4b4f-be75-a4babd2a99de)

PTB:
![Image](https://github.com/user-attachments/assets/ff81bcde-4175-40cd-b645-2738d5742ce1)

TRK:
![Image](https://github.com/user-attachments/assets/ed61d415-307c-47e7-8eee-c725ab5b2862)

**Comment by bobbrow** [comment]
@Yingzi1234 thank you for checking this. I opened new bugs for the localization team to address this.

**Comment by Yingzi1234** [comment]
@bobbrow @PhoebeTf Thank you for your update! This issue has been fixed on latest C/C++ version 1.23.2(pre-release), you can get the details below. 
CHS
![Image](https://github.com/user-attachments/assets/09dd3af9-0b96-4188-9159-66886b3b6c35)

TRK
![Image](https://github.com/user-attachments/assets/6ced2ed1-602e-4724-a1a3-9387548268c7)

PTB
![Image](https://github.com/user-attachments/assets/56f58aa0-252a-4d89-83ad-1c1ce16c93de)
