### ISSUE TITLE
Doxygen param with direction `in`, `out` broken output

### ISSUE THREAD

**Issue by zhekaso** [microsoft/vscode-cpptools#13682]
### Environment

- VS Code Version: 1.100.3
- C/C++ Extension Version: 1.26.1

In older version i rember output was correct, but now:

doxygen:  `* @param[in]       key             The Mpls Evpn Model Tunnel Key.`

Output in popup up window:
` [in] - key  The Mpls Evpn Model Tunnel Key.`

Correct output, what i saw in previus versions, with and without direction for `param`:
` key -  The Mpls Evpn Model Tunnel Key`

**Comment by sean-mcmanus** [comment]
This is a regression bug inherited from VS (i.e. works with 1.25.3 of our extension) -- I've filed an internal bug against VS at https://developercommunity.visualstudio.com/t/C-Doxygen-comment-with-paramin-does/10920217 , but I don't think it's externally viewable currently (because I don't think the VS update with the bug has been released publicly yet).

**Comment by sean-mcmanus** [comment]
@zhekaso Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.26.2

**Comment by Delgan** [comment]
Hello @sean-mcmanus.

I'm using v1.26.3 and unfortunately I'm observing this bug is still present.

For example with the following function:

```cpp
/**
 * @brief Function description.
 * 
 * @param[in] arg Hello, world.
 */
void foobar(int arg);
```

Curiously, it only seems to be triggered when the argument description contains a comma.

Without comma (expected):
<img width="284" height="170" alt="Image" src="https://github.com/user-attachments/assets/0547b200-4556-485f-9336-2e030f9a6d4e" />

With comma (unexpected):
<img width="278" height="173" alt="Image" src="https://github.com/user-attachments/assets/799f40ca-d08a-45df-abaf-f6e45e8a503c" />

**Comment by sean-mcmanus** [comment]
@Delgan Yeah, that case got missed by our testing. I've filed a new bug.
