### ISSUE TITLE
When I open the C file, there is an error.：The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by songwenshuai** [microsoft/vscode-cpptools#143]
Updating C++ Debugger dependencies...

Warning: Debugging is currently only supported for Windows when using MinGW or Cygwin. Please refer to C:\Users\songwenshuai.vscode\extensions\ms-vscode.cpptools-0.8.1\README.md for troubleshooting information. Issues can be created at https://github.com/Microsoft/vscppsamples/issues

Finished

The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by greazer** [comment]
We'd like to investigate. Any chance you have a repro you can share?

**Comment by songwenshuai** [comment]
Submit a report, how should I operate?

**Comment by jgoshi** [comment]
Can you attach a small repro project with steps to cause the crash?

**Comment by jgoshi** [comment]
This is fixed an will appear in the next release (version 0.9.0)

**Comment by johncruise** [comment]
I know that this was closed but I still see this message pop up on version 0.9.1.
