### ISSUE TITLE
The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-cpptools#178]
_From @wuzhijiexia on August 28, 2016 6:17_
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:
1. Install C/C++ extension
2. Started the extension then the error appear
3. Can't go to definition and declaration

_Copied from original issue: Microsoft/vscode#11059_

**Comment by sandy081** [comment]
_From @mrmlnc on August 28, 2016 22:12_

Please move this issue into repository of C/C++ extension: https://github.com/Microsoft/vscppsamples/issues.

![chrome_2016-08-29_01-11-18](https://cloud.githubusercontent.com/assets/7034281/18037142/a827bcd4-6d85-11e6-960a-74ffe90ad745.png)

**Comment by jgoshi** [comment]
This should be fixed in the next release of the cpptools (version 0.9.0). This release should be available in the next week or so. If you still run into the issues at that time please reopen this bug.

**Comment by johncruise** [comment]
This problem still shows up on **0.9.1**.

Output window shows:

```
[11:06:19 AM] Connection to server got closed. Server will restart.
[11:06:19 AM] Connection to server got closed. Server will restart.
[11:06:19 AM] Connection to server got closed. Server will restart.
[11:06:19 AM] Connection to server got closed. Server will restart.
[11:06:19 AM] Connection to server got closed. Server will not be restarted.
```

Could you help clear up what server it is trying to connect to?  If this is a local settings (which I couldn't find), could you point us to it?

Thanks

**Comment by delmyers** [comment]
@pieandcakes, is this our debugger extension trying to download dependencies, or @sridmad is this the language server?

**Comment by pieandcakes** [comment]
@jgoshi @delmyers  @sridmad  This is from the download manager. I found this error message in the language client code.

**Comment by sean-mcmanus** [comment]
The server is the Microsoft.VSCode.CPP.Extension.exe. It appears to be crashing. Sounds like we need more repro or crash details.

**Comment by johncruise** [comment]
I'm not familiar where to get more logs or crash information for this extension but if anybody would point that to us here, I'd be more than happy to provide it.

Thanks for looking into this.

**Comment by sean-mcmanus** [comment]
Can you re-open if it's not fixed in 0.9.2? There may be crash info in the Windows Event Viewer.

**Comment by johncruise** [comment]
Hello Sean, thanks for checking back.

I've updated to 0.9.2 just now, I still see the same errors per previous output I included.  I checked Windows Event Viewer and didn't see anything that registers there after I relaunch VS and after the error message pops up.

If it helps, here's the other output under C/C++ dropdown option.

```
Updating C/C++ dependencies...

Downloading package 'Visual Studio Windows Debugger' (12073 KB) .................... Done!
Downloading package 'C/C++ language components (Windows)' (2514 KB) .................... Done!
Downloading package 'ClangFormat (Windows)' (810 KB) .................... Done!

Installing package 'Visual Studio Windows Debugger'
Installing package 'C/C++ language components (Windows)'
Installing package 'ClangFormat (Windows)'

Finished
```

**Comment by itorus** [comment]
Having this same issue too. Any solutions yet? Using v 0.9.2 . Really want to use VS code to code in C but these issues are really starting to deter me.

**Comment by sean-mcmanus** [comment]
What are your repro steps? On VS Code startup? Are you making changes to an unsaved document like "Untitled-1"? Our extensions should work with C code just as well as C++ code. We have a known crash when an unsaved document is used as a C/C++ file.

**Comment by itorus** [comment]
Well I just freshly installed VS Code. Installed the C/C++ 0.9.2 extension, enabled. Then when I type cmd+k, m and select C, then type a letter it gives me that error. Yes, it is on VS code startup and typing into unsaved Untitled-1 document. Is this why it doesn't work for Java either? Because it is an unsaved document? For Java it gives me error of "couldn't start client Language support". Sorry, I'm new to all this so I have no idea what that means :/

**Comment by sean-mcmanus** [comment]
Yes, we don't currently handle the unsaved file case correctly. If you save the file first (so it exists on disk somewhere), our tool should be usable.

**Comment by itorus** [comment]
Ah okay great, that fixed it. No longer getting that error. Just out of curiosity, is VS code capable of automatically importing necessary header files? For example, if I type "pri", will it suggest "printf" and automatically import <stdio.h>? Or vice versa, if I've already imported <stdio.h>, will it suggest printf when I type "pri"? I'm just wondering if this feature is something you can only get from an IDE. Thank you for your help!

**Comment by sean-mcmanus** [comment]
We have some rudimentary auto-complete (which will get better later), but no auto-#include adding. Opening a folder gives best results.

**Comment by protolyser** [comment]
I also get this error everytime with Visual Studio Code v1.7.1 and C/C++ v0.9.2.
I have an Arduino Project folder (with .ino) files open. Doesn't it work with Arduino?

**Comment by sean-mcmanus** [comment]
We've never tested with Arduino projects. We support C/C++ projects. If you can provide a repro of the crash we could investigate.

**Comment by protolyser** [comment]
it happens with any arduino project I tried so far. for example any of the examples included with the arduino ide. or for example this here: https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/NTPClient/NTPClient.ino

when I put that in a folder, open the folder with VS Code and wait a bit, the message pops up.

**Comment by shreyasp** [comment]
Error still occurs on VS Code version 1.7.1 and cpptools v 0.9.2

<img width="1244" alt="screen shot 2016-11-20 at 9 20 27 am" src="https://cloud.githubusercontent.com/assets/3377167/20460224/a4ebb494-af02-11e6-9a25-f9d164e3fab2.png">

**Comment by siyideng** [comment]
Still occurs on VS Code ver 1.8.1 and C/C++ tools 0.10.0, on macOS

![image](https://cloud.githubusercontent.com/assets/5482521/22379360/e2ab3a3e-e46d-11e6-8ada-0f8f68a9482b.png)

**Comment by sean-mcmanus** [comment]
This bug appears to be tracking multiple different crashes. Which crash scenario did you want fixed? We haven't fixed the "unsaved file" or Arduino crashes yet.

**Comment by mhalber** [comment]
Hi - I am experiencing a similar issue. I am not working on "unsaved files" or Arduino. The cpp extension functionality like "Go To Definition" simply never work, and the message about language server crashing shows up sporadically. I've attempted  to reinstall the vscode completely,
however issue persist even after reinstall. I've found information regarding specifying full path to "browse.VC.db", since this file seemed not to be created. After this modification I do see the files "browse.VC.db", "browse.VC.db-wal", "browse.Vc.db-shm". This did not help, and I am still unable to use "Go To Declaration" or "Peek Declaration". At the same time I am concstantly seeing the fire icon next to configuration status in the bottom bar.

Code Version: 1.9.1  f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
Extension Version: 0.10.1
OSVersion: macOS Sierra 10.12.3

I know this is not the most detailed bug report, but the behavior I am seeing is bit bizzare.

**Comment by sean-mcmanus** [comment]
The fire icon means where scanning/parsing the workspace and includePaths, until that is finished some definitions may not be found. Can you try 0.10.3? We fixed a number of issues.

**Comment by huhutm** [comment]
This issue still exist in version 0.10.3.

**Comment by sean-mcmanus** [comment]
@huhutm Can you provide more repro info? I need to know what OS you're on. What is the size of the .browse.vc.db? What is the behavior of the Microsoft.VSCode.Cpp.Extension process before and after the failure? I assume you're getting the message "The C/Cpp Language Server server crashed 5 times"? What actions are being done before the crash? Does it crash without any actions? We have a parsing thread that runs when the config is red in the bottom right, so we need to know if that is red and if the #include squiggles say "Searching..." or not.

**Comment by jwatte-imvu** [comment]
I run into this writing Arduino code, so I'd like to see it fixed for that case.
However, if there are multiple crashing cases, perhaps actually fixing all of them would be best ;-)

Arduino projects are C++ projects that have one "main" file in a file named ".ino" and the allows additional .cpp and .h files in the same directory, plus references to external libraries where .cpp and .h files go in the same directories.
The Arduino IDE pre-processes the ino file to add a few default include headers, and looks for the external include .h files to know what external .cpp files need to be built.
However, largely, this should look like a C++ project where ".ino" should be treated as ".cpp"

**Comment by sean-mcmanus** [comment]
@jwatte-imvu We need info on how to repro the crash. What is your OS? 64-bit Ubuntu? Does it crash immediately or after editing for a few minutes or after only letting the parsing thread work after opening a workspace? I can open the Arduino-1.8.1 folder and open example .ino files and I don't get any crashes.

**Comment by jwatte-imvu** [comment]
My OS is 64-bit Windows 10 Pro. I separately also have Visual Studio 2015 Pro installed.
The crash happens after a number of minutes of editing.
I installed an update of the C++ tools today, and it identifies itself as version 0.10.3.
Open an Arduino project as a folder, preferable one with a .ino file as well as a few .cpp and .h files, and you should see this happening if you work on it for a bit.

I'll see if I can attach to the Microsoft Cpp process and catch it in an exception.

**Comment by jwatte-imvu** [comment]
There are no public symbols on the Microsoft symbol server, so the stack trace isn't particularly useful, but I did get a dmp file.

![microsoft vscode cpp extension](https://cloud.githubusercontent.com/assets/14279884/23817747/64438940-05aa-11e7-9640-da9f52b75690.png)

Unfortunately, the dump file is too big to upload in this issue tracker.
I have put a copy of it on the web at:
https://watte.net/Microsoft.VSCode.CPP.Extension.dmp

The final Debug Output line before the death is std::length_exception, which might be related.

**Comment by bobbrow** [comment]
That was super helpful.  @sean-mcmanus, this looks like it's caused by the recent updates to parameter help.

**Comment by bobbrow** [comment]
@jwatte-imvu, the crash is on line 59, char 24 of one of your source files.  Parameter help is being invoked on what looks like a simple open parenthesis and it fails to find a function identifier before the open paren because this isn't a function call.

**Comment by sean-mcmanus** [comment]
The bug has been fixed and we'll release it in our next update (hopefully early next week). The bug reproed whenever there's a non-alphanumeric character, a whitespace, and ( is typed. It was caused by a fix to signatureHelp in 0.10.2.

**Comment by jwatte-imvu** [comment]
Glad you could find it! I parenthesize sub-expressions with some frequency, so that would be why I would see this problem frequency. Looking forward to the fix!

**Comment by bobbrow** [comment]
The signature help bug has been fixed and is in version 0.10.4.  Please give it a try and let us know if you are still having issues.

**Comment by thiagoh** [comment]
same issue here

<img width="1194" alt="screen shot 2017-04-20 at 4 39 17 pm" src="https://cloud.githubusercontent.com/assets/110336/25251608/fe146cda-25e7-11e7-9c03-17c78d8b2ffd.png">

**Comment by sean-mcmanus** [comment]
@thiagoh It's the same symptom (a crash), but we need more details to diagnose the cause. Can you file a new bug with the crash report `Users/…/Library/Logs/DiagnosticReports/<process><date><machinename>.crash`. Also, our pending update fixes some known crashes.

**Comment by VincentZhou98** [comment]
I still have this issue 
```
Process:               Microsoft.VSCode.CPP.Extension.darwin [12720]
Path:                  /Users/USER/*/Microsoft.VSCode.CPP.Extension.darwin
Identifier:            Microsoft.VSCode.CPP.Extension.darwin
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        Code Helper [11956]
Responsible:           Electron [9793]
User ID:               501

Date/Time:             2018-06-11 13:13:04.150 +0800
OS Version:            Mac OS X 10.11.6 (15G1611)
Report Version:        11
Anonymous UUID:        B8291642-8602-57B0-2B6A-A239B2F0FD6C

Sleep/Wake UUID:       745AEC45-DED7-421C-BF5E-60D2B0C8E173

Time Awake Since Boot: 190000 seconds
Time Since Wake:       2200 seconds

System Integrity Protection: enabled

Crashed Thread:        10

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff8fb14f8a __read_nocancel + 10
1   libsystem_c.dylib             	0x00007fff9bb45155 _sread + 16
2   libsystem_c.dylib             	0x00007fff9bb44769 __srefill1 + 24
3   libsystem_c.dylib             	0x00007fff9bb44884 __srget + 14
4   libsystem_c.dylib             	0x00007fff9bb4052b getc + 52
5   libc++.1.dylib                	0x000000010bffbacb std::__1::__stdinbuf<char>::__getchar(bool) + 121
6   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b471366 std::__1::basic_istream<char, std::__1::char_traits<char> >& std::__1::getline<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, char) + 134
7   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b42df9c vscode::message_handler::main_loop() + 1180
8   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b49a570 main + 208
9   libdyld.dylib                 	0x00007fff99f955ad start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff8fb14db6 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff99996728 _pthread_cond_wait + 767
2   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4d4ca5 neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long long, int&) + 1077
3   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4d10a5 microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) + 325
4   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b49da21 microsoft::vc::thread_pool::do_work(unsigned long) + 529
5   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b49e631 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, microsoft::vc::thread_pool::add_threads()::$_1> >(void*) + 49
6   libsystem_pthread.dylib       	0x00007fff9999599d _pthread_body + 131
7   libsystem_pthread.dylib       	0x00007fff9999591a _pthread_start + 168
8   libsystem_pthread.dylib       	0x00007fff99993351 thread_start + 13

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff8fb14db6 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff99996728 _pthread_cond_wait + 767
2   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4d4ca5 neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long long, int&) + 1077
3   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4d10a5 microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) + 325
4   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b49da21 microsoft::vc::thread_pool::do_work(unsigned long) + 529
5   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b49e631 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, microsoft::vc::thread_pool::add_threads()::$_1> >(void*) + 49
6   libsystem_pthread.dylib       	0x00007fff9999599d _pthread_body + 131
7   libsystem_pthread.dylib       	0x00007fff9999591a _pthread_start + 168
8   libsystem_pthread.dylib       	0x00007fff99993351 thread_start + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff8fb14db6 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff99996728 _pthread_cond_wait + 767
2   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4d4ca5 neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long long, int&) + 1077
3   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4d10a5 microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) + 325
4   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b49da21 microsoft::vc::thread_pool::do_work(unsigned long) + 529
5   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b49e631 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, microsoft::vc::thread_pool::add_threads()::$_1> >(void*) + 49
6   libsystem_pthread.dylib       	0x00007fff9999599d _pthread_body + 131
7   libsystem_pthread.dylib       	0x00007fff9999591a _pthread_start + 168
8   libsystem_pthread.dylib       	0x00007fff99993351 thread_start + 13

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff8fb14c02 __open + 10
1   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4d16b9 async_pipe_nix::read_sync_impl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 169
2   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b41900a async_pipe::read_sync(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 90
3   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b40ec98 bool comm_client::send_request<microsoft::cpp::intellisense::CompileRequest, microsoft::cpp::intellisense::CompileResponse>(microsoft::cpp::intellisense::CompileRequest&, microsoft::cpp::intellisense::CompileResponse&) + 504
4   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b40e71f intellisense_client::send_compilation_args() + 3503
5   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b40cbe4 intellisense_client::init() + 1124
6   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b40c5ec intellisense_client::intellisense_client(int, char const*, char const*, compilation_args const&, IntelliSenseMode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned long long, bool) + 796
7   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b423760 create_async_work(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int, std::__1::shared_ptr<browse_engine>, std::__1::shared_ptr<compilation_args_provider>, IntelliSenseMode, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::shared_ptr<intellisense_client>, std::__1::allocator<std::__1::shared_ptr<intellisense_client> > >)>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)>) + 2192
8   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b42a454 std::__1::__function::__func<intellisense_client_factory::create_async(char const*, char const*, char const*, int, std::__1::shared_ptr<browse_engine>, std::__1::shared_ptr<compilation_args_provider>, IntelliSenseMode, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::shared_ptr<intellisense_client>, std::__1::allocator<std::__1::shared_ptr<intellisense_client> > >)>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>)::$_0, std::__1::allocator<intellisense_client_factory::create_async(char const*, char const*, char const*, int, std::__1::shared_ptr<browse_engine>, std::__1::shared_ptr<compilation_args_provider>, IntelliSenseMode, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::shared_ptr<intellisense_client>, std::__1::allocator<std::__1::shared_ptr<intellisense_client> > >)>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>)::$_0>, void ()>::operator()() + 724
9   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b49edd8 std::__1::__function::__func<microsoft::vc::thread_pool::enqueue(std::__1::function<void ()>, std::__1::future<void>*)::$_2, std::__1::allocator<microsoft::vc::thread_pool::enqueue(std::__1::function<void ()>, std::__1::future<void>*)::$_2>, void ()>::operator()() + 24
10  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b49db42 microsoft::vc::thread_pool::do_work(unsigned long) + 818
11  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b49e631 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, microsoft::vc::thread_pool::add_threads()::$_1> >(void*) + 49
12  libsystem_pthread.dylib       	0x00007fff9999599d _pthread_body + 131
13  libsystem_pthread.dylib       	0x00007fff9999591a _pthread_start + 168
14  libsystem_pthread.dylib       	0x00007fff99993351 thread_start + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff8fb14db6 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff99996728 _pthread_cond_wait + 767
2   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4d47b4 neosmart::UnlockedWaitForEvent(neosmart::neosmart_event_t_*, unsigned long long) + 180
3   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4d482f neosmart::WaitForEvent(neosmart::neosmart_event_t_*, unsigned long long) + 63
4   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4d0f4e microsoft::vc::alertable_event::wait(unsigned int) + 30
5   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b49e4be std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, microsoft::vc::thread_pool::thread_pool()::$_0> >(void*, void*) + 94
6   libsystem_pthread.dylib       	0x00007fff9999599d _pthread_body + 131
7   libsystem_pthread.dylib       	0x00007fff9999591a _pthread_start + 168
8   libsystem_pthread.dylib       	0x00007fff99993351 thread_start + 13

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff8fb14db6 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff99996728 _pthread_cond_wait + 767
2   libc++.1.dylib                	0x000000010bfebe10 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b473176 vscode::message_deque<vscode::vscode_client_message>::pop_impl(bool) + 102
4   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b472b85 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, vscode::message_handler::main_loop()::$_7> >(void*) + 293
5   libsystem_pthread.dylib       	0x00007fff9999599d _pthread_body + 131
6   libsystem_pthread.dylib       	0x00007fff9999591a _pthread_start + 168
7   libsystem_pthread.dylib       	0x00007fff99993351 thread_start + 13

Thread 7:
0   libsystem_kernel.dylib        	0x00007fff8fb14db6 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff99996728 _pthread_cond_wait + 767
2   libc++.1.dylib                	0x000000010bfebe10 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b473776 vscode::message_deque<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::pop_impl(bool) + 102
4   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b473626 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, vscode::message_handler::main_loop()::$_8> >(void*) + 86
5   libsystem_pthread.dylib       	0x00007fff9999599d _pthread_body + 131
6   libsystem_pthread.dylib       	0x00007fff9999591a _pthread_start + 168
7   libsystem_pthread.dylib       	0x00007fff99993351 thread_start + 13

Thread 8:
0   libsystem_kernel.dylib        	0x00007fff8fb14de6 __psynch_mutexwait + 10
1   libsystem_pthread.dylib       	0x00007fff99995e4a _pthread_mutex_lock_wait + 89
2   libc++.1.dylib                	0x000000010c02443f std::__1::mutex::lock() + 9
3   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4b6c8f parser::update_file_if_needed(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, code_store::a_record_id<code_store::a_file_tag>&, bool) + 639
4   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4b68f9 parser::add_files(microsoft::vc::path_utf8&, bool, microsoft::vc::path_utf8 const&, bool, std::__1::unordered_set<code_store::a_record_id<code_store::a_file_tag>, std::__1::hash<code_store::a_record_id<code_store::a_file_tag> >, std::__1::equal_to<code_store::a_record_id<code_store::a_file_tag> >, std::__1::allocator<code_store::a_record_id<code_store::a_file_tag> > >&)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) const + 169
5   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4b5078 microsoft::vc::result_t parser::process_path<microsoft::vc::recursive_directory_iterator_utf8>(microsoft::vc::path_utf8 const&, bool, microsoft::vc::path_utf8 const&, bool, std::__1::function<microsoft::vc::result_t (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)>) + 456
6   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4a3ef5 parser::add_files(microsoft::vc::path_utf8&, bool, microsoft::vc::path_utf8 const&, bool, std::__1::unordered_set<code_store::a_record_id<code_store::a_file_tag>, std::__1::hash<code_store::a_record_id<code_store::a_file_tag> >, std::__1::equal_to<code_store::a_record_id<code_store::a_file_tag> >, std::__1::allocator<code_store::a_record_id<code_store::a_file_tag> > >&) + 357
7   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4a34d6 browse_engine::search_root(bool) + 966
8   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b44d678 vscode::message_handler::parse_root() + 648
9   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b473cc8 std::__1::__function::__func<vscode::message_handler::main_loop()::$_9, std::__1::allocator<vscode::message_handler::main_loop()::$_9>, void ()>::operator()() + 424
10  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b475773 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::function<void ()> > >(void*) + 51
11  libsystem_pthread.dylib       	0x00007fff9999599d _pthread_body + 131
12  libsystem_pthread.dylib       	0x00007fff9999591a _pthread_start + 168
13  libsystem_pthread.dylib       	0x00007fff99993351 thread_start + 13

Thread 9:
0   libsystem_kernel.dylib        	0x00007fff8fb14db6 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff99996728 _pthread_cond_wait + 767
2   libc++.1.dylib                	0x000000010bfebe10 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b473176 vscode::message_deque<vscode::vscode_client_message>::pop_impl(bool) + 102
4   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b475935 std::__1::__function::__func<vscode::message_handler::main_loop()::$_10, std::__1::allocator<vscode::message_handler::main_loop()::$_10>, void ()>::operator()() + 69
5   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b475773 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::function<void ()> > >(void*) + 51
6   libsystem_pthread.dylib       	0x00007fff9999599d _pthread_body + 131
7   libsystem_pthread.dylib       	0x00007fff9999591a _pthread_start + 168
8   libsystem_pthread.dylib       	0x00007fff99993351 thread_start + 13

Thread 10 Crashed:
0   libunwind.dylib               	0x000000010c0a9335 _Unwind_RaiseException + 93
1   libc++abi.dylib               	0x00007fff8edbca59 __cxa_throw + 104
2   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b912223 scout_parser_cpp_generated::name_id(bool&, unsigned long&) + 547
3   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b911cd7 scout_parser_cpp_generated::inner_identifier(bool&, unsigned long&, bool&) + 423
4   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b91178e scout_parser_cpp_generated::identifier_pre_ellipsis(an_identifier&) + 302
5   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b917fa8 scout_parser_cpp_generated::direct_declarator(a_type_specification&, a_declarator_info&, an_identifier&) + 136
6   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b91b64e scout_parser_cpp_generated::declarator(a_type_specification&, a_declarator_info&, an_identifier&) + 46
7   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b91a493 scout_parser_cpp_generated::init_declarator(a_type_specification&, a_declarator_info&, an_identifier&) + 83
8   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b91e3e1 scout_parser_cpp_generated::statement() + 2049
9   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b90c2a8 scout_parser_cpp_generated::statement_block(bool, a_source_point&) + 136
10  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b91d98e scout_parser_cpp_generated::compound_statement(bool, a_source_point&) + 142
11  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b91a948 scout_parser_cpp_generated::function_body(an_identifier const&, a_source_point&) + 200
12  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b90edc6 scout_parser_cpp_generated::init_declarator_list_or_function_definition(a_source_point const&, a_source_point&, a_type_specification&, a_declaration_info const&) + 1174
13  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b90a557 scout_parser_cpp_generated::simple_declaration(a_type_specification&, antlr::TokenRefCount<antlr::Token>, a_declaration_info const&) + 807
14  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b907481 scout_parser_cpp_generated::property_or_event_or_simple_declaration(a_type_specification&, antlr::TokenRefCount<antlr::Token>, a_declaration_info const&) + 545
15  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b905323 scout_parser_cpp_generated::general_declaration(a_type_specification&, antlr::TokenRefCount<antlr::Token>, a_declaration_info const&) + 659
16  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b904baf scout_parser_cpp_generated::general_declaration_with_error_recovery_inner(a_type_specification&, antlr::TokenRefCount<antlr::Token>, a_declaration_info const&) + 271
17  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b9047b8 scout_parser_cpp_generated::general_declaration_with_error_recovery(a_type_specification&, antlr::TokenRefCount<antlr::Token>, a_declaration_info const&) + 456
18  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b903b8d scout_parser_cpp_generated::declaration(antlr::TokenRefCount<antlr::Token>, a_declaration_info const&) + 493
19  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b903519 scout_parser_cpp_generated::declarations() + 169
20  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b8e1de8 scout_parser_base<scout_parser_cpp, scout_parser_cpp_generated, scout_parser_cpp_generatedTokenTypes>::translation_unit() + 72
21  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b8e1c29 run_scout_parser + 41
22  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b88a41e process_translation_unit + 814
23  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b60e122 edg_main + 162
24  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b8e376c perform_antlr_parse(int, char const**, a_scout_parser_interface&, edge::parse_lang) + 172
25  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b8e3aa8 tag_parse(int, char const**, char const*, edge::parse_lang, edge::snapshot_session const*, a_scout_parser_interface*) + 648
26  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4b7267 parser::update_file_if_needed(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, code_store::a_record_id<code_store::a_file_tag>&, bool) + 2135
27  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4a4f05 browse_engine::parse_file(char const*, code_store::a_record_id<code_store::a_file_tag> const&, std::__1::unordered_set<code_store::a_record_id<code_store::a_file_tag>, std::__1::hash<code_store::a_record_id<code_store::a_file_tag> >, std::__1::equal_to<code_store::a_record_id<code_store::a_file_tag> >, std::__1::allocator<code_store::a_record_id<code_store::a_file_tag> > >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::deque<microsoft::vc::path_utf8, std::__1::allocator<microsoft::vc::path_utf8> >&, parser&, std::__1::function<void ()>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const*, std::__1::shared_ptr<std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >) + 1509
28  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4aa2fd browse_engine::parse_file(char const*, std::__1::function<void ()>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const*, std::__1::shared_ptr<std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >) + 749
29  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b44f662 vscode::message_handler::parse_file(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::function<void ()>, std::__1::shared_ptr<vscode::message_handler::optional_parse_file_args>) + 194
30  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b475d8f std::__1::__function::__func<vscode::message_handler::main_loop()::$_11, std::__1::allocator<vscode::message_handler::main_loop()::$_11>, void ()>::operator()() + 767
31  Microsoft.VSCode.CPP.Extension.darwin	0x000000010b475773 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::function<void ()> > >(void*) + 51
32  libsystem_pthread.dylib       	0x00007fff9999599d _pthread_body + 131
33  libsystem_pthread.dylib       	0x00007fff9999591a _pthread_start + 168
34  libsystem_pthread.dylib       	0x00007fff99993351 thread_start + 13

Thread 11:
0   libsystem_kernel.dylib        	0x00007fff8fb14db6 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff99996728 _pthread_cond_wait + 767
2   libc++.1.dylib                	0x000000010bfebe10 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b476606 vscode::message_deque<int>::pop_impl(bool) + 102
4   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b47654d std::__1::__function::__func<vscode::message_handler::main_loop()::$_12, std::__1::allocator<vscode::message_handler::main_loop()::$_12>, void ()>::operator()() + 45
5   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b475773 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::function<void ()> > >(void*) + 51
6   libsystem_pthread.dylib       	0x00007fff9999599d _pthread_body + 131
7   libsystem_pthread.dylib       	0x00007fff9999591a _pthread_start + 168
8   libsystem_pthread.dylib       	0x00007fff99993351 thread_start + 13

Thread 12:
0   libsystem_kernel.dylib        	0x00007fff8fb14c02 __open + 10
1   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4d1a05 async_pipe_nix::read_async_impl(std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)>, std::__1::function<void (int)>) + 197
2   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b49b3e6 async_pipe::read_async(std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)>, std::__1::function<void (int)>) + 518
3   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b49b102 comm_server::wait_for_requests() + 178
4   Microsoft.VSCode.CPP.Extension.darwin	0x000000010b4158e1 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, intellisense_client::init()::$_0> >(void*) + 49
5   libsystem_pthread.dylib       	0x00007fff9999599d _pthread_body + 131
6   libsystem_pthread.dylib       	0x00007fff9999591a _pthread_start + 168
7   libsystem_pthread.dylib       	0x00007fff99993351 thread_start + 13

Thread 10 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007fd831c20a38  rcx: 0x0000000000000041  rdx: 0x00007fff54825738
  rdi: 0x0000700000519898  rsi: 0x000000010c0a9332  rbp: 0x0000700000519bd0  rsp: 0x0000700000519780
   r8: 0x00000000ffffffec   r9: 0x0000000000000014  r10: 0x00007fff54825950  r11: 0x0000000000000000
  r12: 0x00007fd831c20a90  r13: 0x00000000009f4000  r14: 0x00007fd831c20a18  r15: 0x0000700000519898
  rip: 0x000000010c0a9335  rfl: 0x0000000000010246  cr2: 0x000000010c0ad018
  
Logical CPU:     1
Error Code:      0x00000000
Trap Number:     13


Binary Images:
       0x10b3d9000 -        0x10ba9cff7 +Microsoft.VSCode.CPP.Extension.darwin (0) <E5B845E3-2BC8-35C9-ACDA-52F2D2910CDD> /Users/USER/*/Microsoft.VSCode.CPP.Extension.darwin
       0x10bfe4000 -        0x10c041ff3 +libc++.1.dylib (0) <9F1B7C12-6EA8-307A-999E-32E966ACD332> /usr/local/opt/llvm@5/lib/libc++.1.dylib
       0x10c0a3000 -        0x10c0acfff +libunwind.dylib (0) <57EE4994-9653-3087-8189-CB1B6FE8A039> /usr/local/opt/llvm@5/lib/libunwind.dylib
    0x7fff6fb7d000 -     0x7fff6fbb4a47  dyld (360.22) <C8E77F6D-CE86-3C5B-8576-2584A799B51E> /usr/lib/dyld
    0x7fff8a116000 -     0x7fff8a13fff7  libxpc.dylib (765.70.1) <4FB1311F-4032-3F56-BF0B-CFF45D78FB01> /usr/lib/system/libxpc.dylib
    0x7fff8a140000 -     0x7fff8a141fff  libsystem_blocks.dylib (65) <1244D9D5-F6AA-35BB-B307-86851C24B8E5> /usr/lib/system/libsystem_blocks.dylib
    0x7fff8b256000 -     0x7fff8b5b8f3f  libobjc.A.dylib (680) <7489D2D6-1EFD-3414-B18D-2AECCCC90286> /usr/lib/libobjc.A.dylib
    0x7fff8d2fa000 -     0x7fff8d360ff7  libsystem_network.dylib (583.50.1) <B52DAB73-92DC-3DA7-B9F4-B899D66445C1> /usr/lib/system/libsystem_network.dylib
    0x7fff8e875000 -     0x7fff8e876fff  libsystem_secinit.dylib (20) <32B1A8C6-DC84-3F4F-B8CE-9A52B47C3E6B> /usr/lib/system/libsystem_secinit.dylib
    0x7fff8ed99000 -     0x7fff8edc3ff7  libc++abi.dylib (307.4) <D24E06BF-6522-3C4A-BD0C-11C42BA4D8E8> /usr/lib/libc++abi.dylib
    0x7fff8f082000 -     0x7fff8f0affff  libdispatch.dylib (501.40.12) <C7499857-61A5-3D7D-A5EA-65DCC8C3DF92> /usr/lib/system/libdispatch.dylib
    0x7fff8f2bf000 -     0x7fff8f2c0ffb  libremovefile.dylib (41) <552EF39E-14D7-363E-9059-4565AC2F894E> /usr/lib/system/libremovefile.dylib
    0x7fff8fada000 -     0x7fff8faddfff  libsystem_sandbox.dylib (460.60.3) <2DDCB4AF-3037-34E5-A451-6846AFB9B85C> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff8fafe000 -     0x7fff8fb1cff7  libsystem_kernel.dylib (3248.70.3) <69D68230-7793-3D11-B49E-BA3A6D5137B8> /usr/lib/system/libsystem_kernel.dylib
    0x7fff8fcac000 -     0x7fff8fcb4fef  libsystem_platform.dylib (74.40.2) <29A905EF-6777-3C33-82B0-6C3A88C4BA15> /usr/lib/system/libsystem_platform.dylib
    0x7fff8fcd4000 -     0x7fff8fd4bfeb  libcorecrypto.dylib (335.50.1) <B5C05FD7-A540-345A-87BF-8E41848A3C17> /usr/lib/system/libcorecrypto.dylib
    0x7fff927e0000 -     0x7fff927e1fff  libDiagnosticMessagesClient.dylib (100) <4243B6B4-21E9-355B-9C5A-95A216233B96> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff93d33000 -     0x7fff93d35ff7  libsystem_configuration.dylib (802.40.13) <3DEB7DF9-6804-37E1-BC83-0166882FF0FF> /usr/lib/system/libsystem_configuration.dylib
    0x7fff942ef000 -     0x7fff942f7ffb  libsystem_dnssd.dylib (625.60.4) <80189998-32B0-316C-B5C5-53857486713D> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff9476f000 -     0x7fff94776ff7  libcompiler_rt.dylib (62) <A13ECF69-F59F-38AE-8609-7B731450FBCD> /usr/lib/system/libcompiler_rt.dylib
    0x7fff9661c000 -     0x7fff96645fff  libsystem_info.dylib (477.50.4) <FAA9226D-64DE-3769-A6D8-6CABA4B7FF4D> /usr/lib/system/libsystem_info.dylib
    0x7fff9681f000 -     0x7fff96823fff  libcache.dylib (75) <9548AAE9-2AB7-3525-9ECE-A2A7C4688447> /usr/lib/system/libcache.dylib
    0x7fff980e0000 -     0x7fff980ebff7  libcommonCrypto.dylib (60075.50.1) <93732261-34B4-3914-B7A2-90A81A182DBA> /usr/lib/system/libcommonCrypto.dylib
    0x7fff98a55000 -     0x7fff98a6cff7  libsystem_asl.dylib (323.50.1) <41F8E11F-1BD0-3F1D-BA3A-AA1577ED98A9> /usr/lib/system/libsystem_asl.dylib
    0x7fff98f69000 -     0x7fff98f72ff3  libsystem_notify.dylib (150.40.1) <D48BDE34-0F7E-34CA-A0FF-C578E39987CC> /usr/lib/system/libsystem_notify.dylib
    0x7fff991b2000 -     0x7fff991b7ff7  libmacho.dylib (875.1) <318264FA-58F1-39D8-8285-1F6254EE410E> /usr/lib/system/libmacho.dylib
    0x7fff99398000 -     0x7fff993b4ff7  libsystem_malloc.dylib (67.40.1) <5748E8B2-F81C-34C6-8B13-456213127678> /usr/lib/system/libsystem_malloc.dylib
    0x7fff99992000 -     0x7fff9999bff7  libsystem_pthread.dylib (138.10.4) <3DD1EF4C-1D1B-3ABF-8CC6-B3B1CEEE9559> /usr/lib/system/libsystem_pthread.dylib
    0x7fff99e3b000 -     0x7fff99e6affb  libsystem_m.dylib (3105) <08E1A4B2-6448-3DFE-A58C-ACC7335BE7E4> /usr/lib/system/libsystem_m.dylib
    0x7fff99f92000 -     0x7fff99f95ffb  libdyld.dylib (360.22) <7C1BBC59-FA8A-3BDF-B209-02167832E7D1> /usr/lib/system/libdyld.dylib
    0x7fff9a149000 -     0x7fff9a14bff7  libquarantine.dylib (80) <B3B7B630-9012-3DA3-9458-5C009625E606> /usr/lib/system/libquarantine.dylib
    0x7fff9a956000 -     0x7fff9a95efff  libcopyfile.dylib (127) <A48637BC-F3F2-34F2-BB68-4C65FD012832> /usr/lib/system/libcopyfile.dylib
    0x7fff9aba2000 -     0x7fff9aba2ff7  liblaunch.dylib (765.70.1) <96D7C3EE-82E2-39AB-870F-B317A030E86D> /usr/lib/system/liblaunch.dylib
    0x7fff9b86c000 -     0x7fff9b87dff7  libsystem_trace.dylib (201.10.3) <4F626911-011B-3E9C-8D61-C5EBA79013F0> /usr/lib/system/libsystem_trace.dylib
    0x7fff9b87e000 -     0x7fff9b87fffb  libSystem.B.dylib (1226.10.1) <160608FD-B79D-3B49-AFEA-53A10C0C86B3> /usr/lib/libSystem.B.dylib
    0x7fff9baf6000 -     0x7fff9baf8fff  libsystem_coreservices.dylib (19.2) <1B3F5AFC-FFCD-3ECB-8B9A-5538366FB20D> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff9bb01000 -     0x7fff9bb8efef  libsystem_c.dylib (1082.60.1) <28733D22-553E-3CBC-8D2C-EDCEB46E46AF> /usr/lib/system/libsystem_c.dylib
    0x7fff9bcf0000 -     0x7fff9bcf0ff7  libunc.dylib (29) <DDB1E947-C775-33B8-B461-63E5EB698F0E> /usr/lib/system/libunc.dylib
    0x7fff9e244000 -     0x7fff9e25bff7  libsystem_coretls.dylib (83.40.5) <C90DAE38-4082-381C-A185-2A6A8B677628> /usr/lib/system/libsystem_coretls.dylib
    0x7fff9f43f000 -     0x7fff9f485ff7  libauto.dylib (186) <999E610F-41FC-32A3-ADCA-5EC049B65DFB> /usr/lib/libauto.dylib
    0x7fff9fcd8000 -     0x7fff9fce0fff  libsystem_networkextension.dylib (385.40.36) <66095DC7-6539-38F2-95EE-458F15F6D014> /usr/lib/system/libsystem_networkextension.dylib
    0x7fffa0879000 -     0x7fffa0879ff7  libkeymgr.dylib (28) <8371CE54-5FDD-3CE9-B3DF-E98C761B6FE0> /usr/lib/system/libkeymgr.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 130379
    thread_create: 0
    thread_set_state: 12

VM Region Summary:
ReadOnly portion of Libraries: Total=109.7M resident=0K(0%) swapped_out_or_unallocated=109.7M(100%)
Writable regions: Total=52.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=52.6M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                  2048K        2 
Kernel Alloc Once                    4K        2 
MALLOC                            36.3M       15 
MALLOC guard page                   16K        4 
STACK GUARD                       56.0M       14 
Stack                             14.1M       19 
VM_ALLOCATE                          4K        2 
__DATA                            2992K       43 
__LINKEDIT                        95.4M        6 
__TEXT                            14.3M       43 
mapped file                         32K        2 
shared memory                       12K        4 
===========                     =======  ======= 
TOTAL                            221.2M      144 
```
My VSCode is Version 1.24.0 (1.24.0)

What is the problem?

**Comment by nygymankussainov** [comment]
<img width="1971" alt="Screen Shot 2019-08-17 at 10 13 04" src="https://user-images.githubusercontent.com/37148632/63207991-a7f71400-c0d7-11e9-8997-6cb4e9c23332.png">

I have the same issue

**Comment by michelleangela** [comment]
@nygymankussainov , you may be having this issue #4096, but it only seems to occur on macOS version 10.12. Can you confirm your OS by posting at issue #4096?
