### ISSUE TITLE
clang-format.exe can not use, always crash, force me to replace the format exe

### ISSUE THREAD

**Issue by WongBean** [microsoft/vscode-cpptools#2232]
Type: LanguageService
**----- Input information below -----**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Windows7
- VS Code Version: 1.23.1
- C/C++ Extension Version: 0.17.6
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Provide a code sample including configuration files such as c_cpp_properties.json*

**Expected behavior**

**Screenshots**

**Additional context**
*Call Stacks: For bugs like crashes, deadlocks, infinite loops, etc. that we are not able to repro and for which the call stack may be useful, please attach a debugger and/or create a dmp and provide the call stacks. Starting with 0.17.3, Windows binaries have symbols available in VS Code by setting your "symbolSearchPath" to "http://msdl.microsoft.com/download/symbols".*
Add any other context about the problem here including log messages in your Output window ("C_Cpp.loggingLevel": "Debug" in settings.json).

**Comment by sean-mcmanus** [comment]
Hmm, I don't know why it would crash. We just use the version at http://releases.llvm.org/6.0.0/LLVM-6.0.0-win32.exe . You can also set the "C_Cpp.clang_format_path" setting to the clang-format binary you want to use. What version do you use that doesn't crash?

**Comment by WongBean** [comment]
I use the version of LLVM is 6.0.0, when I enter .vscode\extensions\ms-vscode.cpptools-0.17.6\LLVM\bin, add input clang-format.exe --version in the windows cmd, then it crash

**Comment by bobbrow** [comment]
@sean-mcmanus this might be the dll dependency issue.

**Comment by sean-mcmanus** [comment]
Yeah, it's probably https://github.com/Microsoft/vscode-cpptools/issues/2255 -- vc++ 2015 redist DLLs are missing. A workaround would be to download the matching LLVM install for your OS at http://releases.llvm.org/download.html , and then set the C_Cpp.clang_format_path to point to the binary.

**Comment by sean-mcmanus** [comment]
If you uninstall the extension, close/reopen VS Code (because VS Code caches it), and then reinstall the extension you should get the correct clang-format dependencies (you should see 2 dlls next to the clang-format.exe at `C:\Users\<user>\.vscode\extensions\ms-vscode.cpptools-0.17.6\LLVM\bin`). I only tested on Win10 though, so it's possible there's some additional Win7 dependency so let us know if it doesn't work still.

**Comment by sean-mcmanus** [comment]
The clang-format.exe failure on Windows should be fixed with 0.17.7.

**Comment by loaden** [comment]
still missing some api-ms-win-crt-runtime***.dll, so it should does not work.

**Comment by sean-mcmanus** [comment]
@loaden Ah, sorry -- those must be installed on Win10 but not Win7. I'll look into adding those.

**Comment by sean-mcmanus** [comment]
@loaden Hmm...it works for me on new Win7 VM -- looks like some Windows Update installed those files into my Windows\SysWOW64 folder (September 2017). I'd recommend installing the Win7 updates if possible; otherwise, I'll see if I can get an OS without those updates.

UPDATE: Uninstalling the September 2017 update replaced it with binaries from November 2015. I'm assuming you have Win7 without SP1...not sure how to get that old version.

UPDATE: 9 Windows system dll's are missing (using a dependency walker) -- these binaries are available as part of a Windows update, so that is the recommended solution (https://stackoverflow.com/questions/33265663/api-ms-win-crt-runtime-l1-1-0-dll-is-missing-when-opening-microsoft-office-file ). LLVM bundles those dlls with its clang-format, but we'd prefer not to do that as of now.

**Comment by loaden** [comment]
@sean-mcmanus Sorry for late. I'm use Windows 7 with SP1, just did not installed any update packages. Copy all the api-ms-*.dll files from VSCode dir to the extensions\ms-vscode.cpptools-0.17.7\LLVM\bin should fixed that problem.  I thought the inno_updater.exe tool should have the same issue.

**Comment by bobbrow** [comment]
Please try to install [KB2999226](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows).  We will not be shipping these dlls with the extension.
