### ISSUE TITLE
Header autocomplete not working for compile_commands or provider API

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode-cpptools#2242]
With the addition of the Provider API, I noticed that header file intellisense does not use anything for providing intellisense other then the c_cpp_properties.json settings. This should be added for compile_commands and the provider API to provide uniformity.

**Comment by sean-mcmanus** [comment]
Header completion for compile_commands.json and custom configuration providers should be fixed with https://github.com/Microsoft/vscode-cpptools/releases/tag/0.19.1-insiders3 .

**Comment by ThadHouse** [comment]
This is not fixed, at least for API providers. I'm using `0.20.1` and the autocomplete is still using the recursive defaults, rather then grabbing them from the API.

@sean-mcmanus

**Comment by sean-mcmanus** [comment]
Is the source file you're invoking the `#include` completion in registered as having config data by the custom config provider, i.e. is it a .cpp/.c file and not .h or extensionless and do other features use the custom config provider info correctly for that file?

We're currently working on changing `#include` completion to show only the 1st level files and folders and not the recursive "folder/folder/.../file" like it currently does, so maybe that is what you're referring to? The current bits also can have some performance (and blocking) issues with large workspaces which we're working on fixing.

**Comment by ThadHouse** [comment]
Yes, all other semantic intellisense works, and it is properly using the config data sent by the API. Definitions internal to the compiler are showing up, so the API definitely is working.

Oh, I didn't realize it would always recurse, even if I was not passing recursive include directories. Most of our headers are in subfolders, and our compiler setup requires everything to be properly rooted to the first level folder.

**Comment by sean-mcmanus** [comment]
Okay, so it sounds like this should be fixed with https://github.com/Microsoft/vscode-cpptools/issues/2836 . Our plan is to get it into our next insiders release, maybe next week.
