### ISSUE TITLE
empty nested quotation mark strings in configurations stopped working

### ISSUE THREAD

**Issue by salda** [microsoft/vscode-cpptools#2258]
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Ubuntu 16.04 latest stable
- VS Code Version: latest stable
- C/C++ Extension Version: latest stable
- Other extensions you installed (and if the issue persists after disabling them): not worth effort filling this for now
- A clear and concise description of what the bug is.
The empty double quotation marks get passed incorrectly to Ubuntu terminal, but it has been already working for a long time before this/last week. 

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Run configuration 
        {
            "name": "Debug something wallet rpc wallet",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/debug/bin/something-wallet-rpc",
            "args": [
                "--rpc-bind-port", "19835",
                "--wallet-file", "wallet",
                "--password", "\\"\\"",
                "--log-level", "2"
            ],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]//,
            //"preLaunchTask": "wait some time"
        }

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
If I run the terminal directly and use "./build/debug/bin/something-wallet-rpc --rpc-bind-port 19835 --wallet-file wallet --password "" --log-level 2", it works as expected. The configuration has been working in the past. 

I prefer SO: https://stackoverflow.com/questions/51283841/vscode-empty-nested-quotation-mark-strings-in-configurations-stopped-working
I asked on VSCode first: https://github.com/Microsoft/vscode/issues/54042

**Comment by WardenGnaw** [comment]
Can you enable engine logging and share the output here?

**Comment by salda** [comment]
I prolly need to obfuscate a lot for that, but I will try to do it.

**Comment by salda** [comment]
@WardenGnaw I guess it's easily reproducible.
[C++_output.txt](https://github.com/Microsoft/vscode-cpptools/files/2192678/C%2B%2B_output.txt)

**Comment by WardenGnaw** [comment]
@salda Thank you for sharing the logging. 

Just to clarify. You want to pass in an empty string after the `--password` argument?

**Comment by salda** [comment]
@WardenGnaw Yes and I checked the commit and seems you hit the point and solved it :)

**Comment by sean-mcmanus** [comment]
Fixed with 0.17.7.

**Comment by salda** [comment]
So it's probably not solved yet. I have been writing the the `--password` argument manually all the time and been waiting when it starts to work, but it didn't yet. 
Was it tested before releasing?

Once again.. it worked perfectly in the past...

**Comment by sean-mcmanus** [comment]
@salda Was it working with 0.17.7? It might have regressed.

**Comment by salda** [comment]
@sean-mcmanus I don't know, it was working in latest version before I reported it in July.
