### ISSUE TITLE
Modifying conditional breakpoints while debugging does not work due to VSCode change

### ISSUE THREAD

**Issue by WardenGnaw** [microsoft/vscode-cpptools#2297]
VS Code version: 1.25.1

## Steps to reproduce
Create C++ project and create a conditional breakpoint that will be true. Start debugging. Once you hit the breakpoint, change it to a false statement. F5.

## Expected  behavior
Once it becomes a false statement, it should not hit the breakpoint.

## Actual behavior
It will always hit the breakpoint due to the original condition

## Issue reason:
VSCode changed how they updated breakpoints. Instead of removing then adding a new breakpoint, they use the same breakpoint id.

See: https://github.com/Microsoft/vscode/issues/42200

**Comment by letmaik** [comment]
This is also a problem if you start with a regular breakpoint and make it a conditional breakpoint. In that case, the condition is not applied and the breakpoint stays a regular breakpoint. I could verify this with `"engineLogging": true` in the debug console: no gdb commands are sent when modifying the breakpoint.

**Comment by salda** [comment]
How to upvote it?

**Comment by bobbrow** [comment]
Click the reaction icon and choose the 👍 

![image](https://user-images.githubusercontent.com/12818240/47446587-6411d780-d770-11e8-874b-84e6ee5affd7.png)

**Comment by salda** [comment]
Thanks, I did it before, just wasn't sure it's it.

**Comment by jerome-labidurie** [comment]
As a workaround, breakpoints can still be modified in gcc via the debugging console :
`-exec cond <breakpoint_number> <condition>`
eg:
`-exec cond 2 pStruct != 0x0`
obviously, it will not be visible in the GUI :(

**Comment by g3v** [comment]
The issue is still present. I thought I am losing it :)

**Comment by aenima1891** [comment]
Please, solve this issue.
It would be very useful during debugging

**Comment by nicole-mcg** [comment]
I am getting behaviour where once the conditional breakpoint is hit once, it is no longer conditional

**Comment by lbru** [comment]
Issue still reproducible on 1.40.2. Workaround described in https://github.com/microsoft/vscode-cpptools/issues/2297#issuecomment-484514159 still applies.

**Comment by abemud** [comment]
the issue is still here!

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/0.29.0-insiders .

**Comment by carrigiljavia** [comment]
Issue (The condition for a breakpoint failed to execute if expression is a string - Still failing #5676) retested with version https://github.com/microsoft/vscode-cpptools/releases/tag/0.29.0-insiders and this does not fix the error.
![2020-07-05_11-36-07](https://user-images.githubusercontent.com/25373218/86537646-53f34a80-beb6-11ea-8dae-d83a7fef9ca2.gif)

**Comment by WardenGnaw** [comment]
@carrigiljavia Are you using the debugger configuration `type: cppvsdbg`?

**Comment by carrigiljavia** [comment]
@WardenGnaw Yes sir. 
![image](https://user-images.githubusercontent.com/25373218/86845216-c7d85300-c06e-11ea-9bf8-721ee7a31505.png)

**Comment by sean-mcmanus** [comment]
Is this issue not fixed?

**Comment by WardenGnaw** [comment]
It is fixed for cppdbg. 

Tracking for cppvsdbg is at https://github.com/microsoft/vscode-cpptools/issues/5676
