### ISSUE TITLE
.browse.VC.db file deleted and recreated on each restart of code.

### ISSUE THREAD

**Issue by jmlewis1** [microsoft/vscode-cpptools#26]
I see you're storing a lot of information in a .browse.VC.db file.
This files takes hours to generate on large projects.  You can imagine my dismay when I realized that you're deleting this file, and recreating it from scratch every time I restart code.

**Comment by sridmad** [comment]
We should not be re-creating the database file. Can you give me an idea about the size of the project and how long it takes to complete?

**Comment by jmlewis1** [comment]
millions and millions of lines of code, thousands, and thousands of files.  I don't know how long it takes to complete, it's never completed parsing the whole tree.

I've done smaller examples, with just 100s of thousands of lines of code, with 100s of files.  That completes in several minutes, with a database that's ultimately about 16MB in size.

I can clearly see, after shutting down code, and restarting it, the database size immediately drops to 0, then starts counting back up in size again.

Also, ideally when you search for a file, it'd be nice if you used your database, and didn't do a directory tree walk, which is what I assume is going on by default.  Directory tree walk could take an hour, database lookup should be near instantaneous.

**Comment by rajesh-gali** [comment]
I am using Windows 7 system and I see the same issue. .db file is around 1.1GB and takes around 5 minutes to complete it.

**Comment by dalianzhu** [comment]
I see the same issue.It applies only to small projects.When I opened the Linux kernel (i use ubuntu 14.04 x64) , it's almost unusable. No function prompts, no code references.Please fix it. I really like it.

**Comment by sridmad** [comment]
Deletion and recreation of browse.db should be addressed in 0.6 version of the extension. Please re-open if you continue to see the bug.

**Comment by jmlewis1** [comment]
I don't think I can reopen, but I'm still seeing this issue.  

I just updated the cpptools extension to 0.7.1 , and VS Code to 1.3.1, and let it run creating my database for an hour or so.  The closed VS Code (while the database was still being created), then relaunched VS Code, and the database size dropped to 0, then started counting back up again.
