### ISSUE TITLE
isystem entries with no space after are ignored

### ISSUE THREAD

**Issue by bbalp** [microsoft/vscode-cpptools#2629]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Debian Stretch
- VS Code Version: 1.28.0
- C/C++ Extension Version: 0.19.0

When i have `isystem` entries in my `compile_commands.json` with no space between the keyword and the path, then entries are ignored. If I had a space between, then it works.

Here is my `compile_commands.json`:
```
[
  {
    "directory": "/tmp/project/build/obj",
    "arguments": [
      "/usr/bin/g++",
      "-m64",
      "-std=c++17",
      "-pedantic",
      "-Wall",
      "-isystem/tmp/project/build/deps/gsl/include",
      "-DDEBUG",
      "/tmp/project/src/main.cpp",
      "-c",
      "-o/tmp/project/build/obj/main.cpp.1.o"
    ],
    "file": "/tmp/project/src/main.cpp"
  }
]
```

**To Reproduce**
1. Add a space manually in the entry: `"-isystem /tmp/project/build/deps/gsl/include",`
2. Restart vscode
3. Related include directives are resolved correctly in `main.cpp`
4. Remove the space in the entry: `"-isystem/tmp/project/build/deps/gsl/include",`
5. Restart vscode
3. Related include directives are not resolved anymore in `main.cpp` (red squiggles)

I also tested by replacing `-isystem` with `-I` when there is no space separating the path, and it works.

**Expected behavior**
Should at least work with no space between the keyword and the path.

**Comment by sean-mcmanus** [comment]
Yeah, our code explicitly checks for "-isystem " with a space at the end. Looks like it should be pretty trivial to fix this.

UPDATE: The fix is expected to be in 0.19.1-insiders2 (or 0.19.1)...it was too late for 0.19.1-insiders.

**Comment by sean-mcmanus** [comment]
Should be fixed in https://github.com/Microsoft/vscode-cpptools/releases/tag/0.19.1-insiders2 .

**Comment by bbalp** [comment]
Well, I don't know what to say. It seems that nothing changed for me. The exact example above is still not working. I installed insiders2 vsix manually, restarted vscode, let the intellisense work a bit then the red squiggles appears again. Adding a space between isystem and the path can still fix the problem though, as previously mentioned.

**Comment by sean-mcmanus** [comment]
Sorry about that -- we tested/fixed it with a relative directory "./" instead of "/" so we didn't catch another "off-by-one" problem. It should be fixed in our pending 0.19.1-insiders3 for Thursday or Friday.

**Comment by sean-mcmanus** [comment]
-isystem without a space or . afterwards should be fixed with https://github.com/Microsoft/vscode-cpptools/releases/tag/0.19.1-insiders3 .

**Comment by bbalp** [comment]
Cool, just tested and it seems to work fine for me. Thank you! :)
