### ISSUE TITLE
IntelliSense-based Go to Declaration failed in this case

### ISSUE THREAD

**Issue by lh123** [microsoft/vscode-cpptools#2743]
**Type: LanguageService**
- C/C++ Extension Version: 0.20.0

## 1. Incorrect
```c++
void insert(int a) {
}

int main() {
    insert(0);//  IntelliSense-based Go to Declaration give incorrect result in here.
}
```

## 2. Correct
```c++
void insert(int a);

int main() {
    insert(0);//  IntelliSense-based Go to Declaration give correct result in here.
}

void insert(int a) {
}
```

**Comment by sean-mcmanus** [comment]
Sorry about this (and thanks for reporting it) -- it was caused by a silly "typo" error. We plan to release a fix in a few hours.

**Comment by sean-mcmanus** [comment]
Fixed with 0.20.1.

**Comment by lh123** [comment]
@sean-mcmanus 
In 0.20.1 I thinks this problem still exits.
```c++
#include <iostream>

void insert(int a) {

}

int main() {
    insert(0);//Go to Declaration At here.
}
```

**Comment by lh123** [comment]
@sean-mcmanus 
## In 0.20.1. I thinks this problem still exits.
## 1. Step to reproduce:
> 1. Add `#include <list>`.
> 2. A function named `insert` only defined.

## 2. Code:
```c++
#include <list>//Need include list to reproduce

void insert(int a) {//Need function name is 'insert'

}

int main() {
    insert(0);//Go to Declaration At here.
}
```

```c++
#include <list>

void otherName(int a) {

}

int main() {
    otherName(0); //Go to Declaration is correct.
}

```
## 3. Screenshort:
![image](https://user-images.githubusercontent.com/10697249/47834015-9c509000-ddd8-11e8-905b-ab5aff1c2d7a.png)

**Comment by sean-mcmanus** [comment]
The bug isn't reproing for me. Do you know what could be special about your repro? I'm using mingw 7.3. -- I'm not sure what else could be different (maybe 8.2 is required?). One known issue is that if you open a new file/TU and then use Go to Definition/Declaration before the red flame has finished it can fall back to the old results, but if your file is small like the sample shown, this is probably not what you're hitting.

**Comment by lh123** [comment]
@sean-mcmanus 
Thank you for your reply.

1. Yes, I am use MinGW-W64 8.2.0 in MSYS2.
2. Before I do Go to **Declaration**, I am sure that the red flame has disappeared.
3. Go to **Definition** works fine.
