### ISSUE TITLE
Language Server Crashing

### ISSUE THREAD

**Issue by MikuHatsune39** [microsoft/vscode-cpptools#2768]
Issue Type: <b>Bug</b>

When I open up vscode I get a popup saying:
"The language server crashed 5 times in the last 3 minutes. It will not be restarted."

Extension version: 0.20.1
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|

</details>

**Comment by sean-mcmanus** [comment]
We need a call stack (or a way to repro it). Does the bug repro with a folder when no C/C++ file is open but you have a c_cpp_properties.json (i.e. and an Edit Configuration command) Can you attach a debugger to the Microsoft.VSCode.CPP.Extension.exe process before it crashes? If not, can you clone our repo at https://github.com/Microsoft/vscode-cpptools/tree/release , put a breakpoint after the languageClient.start() line in https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/client.ts , do a Launch Extension, and then attach a debugger?

**Comment by sean-mcmanus** [comment]
We just found/fixed a crash on startup when custom configuration providers are used. Are you using a custom configuration provider such as CMake Tools?

**Comment by sean-mcmanus** [comment]
We fixed several crashes with 0.21.0-insiders (auto installed if `"C_Cpp.updateChannel": "Insiders"` is set, or the [offline vsix](https://github.com/Microsoft/vscode-cpptools/releases/tag/0.21.0-insiders)). Let us know if you find any problems with it still.

**Comment by johannesegger** [comment]
I installed 0.21.0-insiders but still have this problem on one of three machines (language server crashes as soon as .c file is opened).

I don't think I use a custom configuration provider, this extension is currently the only thing I have installed for C development.

Unfortunately I don't know how to get a stack trace. I installed [x64dbg](https://x64dbg.com/) and attached it to `Microsoft.VSCode.CPP.Extension.exe`. When I then clicked on `Debug -> Advanced -> Run (pass exceptions)` or `Debug -> Step over` often enough the debugger detaches and returns to its initial view. The same happens when I debug the process with Visual Studio and turn on all exceptions. Any ideas?

Extension version: 0.21.0-insiders
VS Code version: 1.29.1
OS version: Microsoft Windows 7 Enterprise

**Comment by sean-mcmanus** [comment]
@johannesegger You may be hitting a Win7-only crash we've gotten previous user reports on. We no longer get crash data on Win7 so we don't know how bad the crashing is and we don't get call stacks.

0. In the repro VS Code, open a workspace with no .c files open, but has a c_cpp_properties.json (so that the C/C++ extension process is running).
1. Click the Debug icon on the left of VS Code.
2. Click the Configure or Fix 'launch.json' button and select C++ Windows
3. Click "Add Configuration..." and select C++ (Attach) Windows.
4. Add line `"symbolSearchPath": "http://msdl.microsoft.com/download/symbols",`
5. Click the Start Debugging button and type Microsoft.VSCode.Extension.exe and select that process to debug.
6. Open a .c file to repro the crash.

Debugging with Visual Studio should work as well if the "Microsoft Symbol Servers" symbols checked.

But maybe there's something preventing debugging on Win7, since I haven't tried with that yet.

![image](https://user-images.githubusercontent.com/19859882/48865312-1941aa80-ed84-11e8-8d99-3a9886cb6fa3.png)

**Comment by johannesegger** [comment]
Thanks for your response and your help so far.

I tried your advice on a machine where it works anyway and also on the machine where it doesn't work. On the working machine I can select the process for debugging, on the non-working machine `Microsoft.VSCode.CPP.Extension.exe` isn't even running (even before opening the .c file). I used the same workspace with the same `c_cpp_properties.json`. On the non-working machine I then tried to start `Microsoft.VSCode.CPP.Extension.exe` which seems to work (the process doesn't quit and gives no output). Any ideas?

**Comment by sean-mcmanus** [comment]
@johannesegger On the non-working machine, are you getting the language server crashed message? If you do Help->Toggle Developer Tools you may see some error messages. After opening a workspace with no C/C++ files open, you may need to invoke a C/C++ command (e.g. "C/Cpp: Navigate..." for our extension to activate, although having a c_cpp_properties.json is supposed activate as well. If it's crashing during activation without opening a C/C++ file, you could clone our type script GitHub repo and set a breakpoint after the languageClient.start() line in https://github.com/Microsoft/vscode-cpptools/blob/release/Extension/src/LanguageServer/client.ts and then attach the debugger at that point.

**Comment by layzerar** [comment]
After investigation, I Found that the following style of comment in the header file will crash language server.

```cpp
	//////////////////////////////////////////////////////////////////////////monster
```

My code outline is something like:

```cpp
class Test {
public:
	method1();
	method2();
	//////////////////////////////////////////////////////////////////////////monster
	method3();
	method4();
};
```

The steps of to reproduce:

+ Add the comment line above
+ Reset IntelliSense Database
+ Close and reopen the workspace
+ Then, the IntelliSense will fallback to tag parser
+ Remove the comment line, IntelliSense will back to normal

Is this a bug of tokenizer?

**Comment by johannesegger** [comment]
I definitely have a different problem than @layzerar.
I followed your advice and started the developer tools and I found the following:

![image](https://user-images.githubusercontent.com/237707/49143568-94aed900-f2fb-11e8-901b-c787ac3c22dd.gif)

Here is the error again:

![image](https://user-images.githubusercontent.com/237707/49143621-b5772e80-f2fb-11e8-9033-4c0ce482d030.png)

Line 88 of clientCollection.js is the following:
![image](https://user-images.githubusercontent.com/237707/49143763-038c3200-f2fc-11e8-9515-f3f1cf4eb2c8.png)

This only happens when there's no .c file open at startup, but it's likely that this is completely unrelated to my actual problem.

**Comment by johannesegger** [comment]
But at no point I see `Microsoft.VSCode.CPP.Extension.exe` running

![image](https://user-images.githubusercontent.com/237707/49144093-caa08d00-f2fc-11e8-8a29-8a5d5f4c091e.gif)

**Comment by johannesegger** [comment]
The error (Cannot read property 'uri' of undefined) only occurs on the non-working machine because it's called from the `closed` handler of `LanguageClient` (see stack trace). So it's related, but not necessarily helpful.

**Comment by johannesegger** [comment]
I can set the breakpoint after `languageClient.start();` and can then attach the debugger, but I don't gain any insights from doing so because when I continue running the extension the debugger detaches because the process closes and the `closed` callback in the extension is triggered.

The problem is: I don't know why the process is closed or who closes it.

**Comment by layzerar** [comment]
The problem I described above seems not the root cause. It may be more complicated. Can you guys give some advices on how to debug this issue.

**Comment by johannesegger** [comment]
@layzerar For debugging the extensions and/or the language server process try the instructions [above](https://github.com/Microsoft/vscode-cpptools/issues/2768#issuecomment-440791063)

**Comment by sean-mcmanus** [comment]
@layzerar Yeah, sounds like we need a call stack or repro of the crash.

@johannesegger The process must be crashing soon after startup -- or it could be early exiting for some reason, which could explain why debugging isn't working. I tried Win7 and it's working for me -- it's possible your Win7 is not updated with SP1 or some other required updates, i.e. your SysWOW64 folder should have a bunch of api-ms-win DLLs. The Uri reference is a different bug (https://github.com/Microsoft/vscode-cpptools/pull/2875 ).

**Comment by layzerar** [comment]
After attach to the Microsoft.VSCode.CPP.Extension.exe, I found the process is still running. But I got the following logs from the debug console. Is this normal behaviour?

```
-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Loaded 'C:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.20.1\bin\Microsoft.VSCode.CPP.Extension.exe'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\user32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\win32u.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\gdi32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\gdi32full.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\msvcp_win.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\ucrtbase.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\shell32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\msvcrt.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\cfgmgr32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\SHCore.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\sspicli.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\cryptbase.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\bcryptprimitives.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\sechost.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\combase.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\windows.storage.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\advapi32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\shlwapi.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\kernel.appcore.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\profapi.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\powrprof.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\fltLib.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\ole32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\oleaut32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\mscoree.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\imm32.dll'. Symbols loaded.
The thread 4964 has exited with code 0 (0x0).
The thread 21044 has exited with code 0 (0x0).
The thread 12588 has exited with code 0 (0x0).
Exception thrown at 0x75CC1812 in Microsoft.VSCode.CPP.Extension.exe: Microsoft C++ exception: antlr::NoViableAltException at memory location 0x04F9D064.
Exception thrown at 0x75CC1812 in Microsoft.VSCode.CPP.Extension.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x75CC1812 in Microsoft.VSCode.CPP.Extension.exe: Microsoft C++ exception: antlr::NoViableAltException at memory location 0x04F9DC10.
Exception thrown at 0x75CC1812 in Microsoft.VSCode.CPP.Extension.exe: Microsoft C++ exception: antlr::NoViableAltException at memory location 0x04F9D064.
Exception thrown at 0x75CC1812 in Microsoft.VSCode.CPP.Extension.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x75CC1812 in Microsoft.VSCode.CPP.Extension.exe: Microsoft C++ exception: antlr::NoViableAltException at memory location 0x04F9D064.
Exception thrown at 0x75CC1812 in Microsoft.VSCode.CPP.Extension.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x75CC1812 in Microsoft.VSCode.CPP.Extension.exe: Microsoft C++ exception: antlr::NoViableAltException at memory location 0x04F9DC10.
Exception thrown at 0x75CC1812 in Microsoft.VSCode.CPP.Extension.exe: Microsoft C++ exception: antlr::NoViableAltException at memory location 0x04F9D064.
Exception thrown at 0x75CC1812 in Microsoft.VSCode.CPP.Extension.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
The thread 16060 has exited with code 0 (0x0).
The thread 14216 has exited with code 0 (0x0).
The thread 14868 has exited with code 0 (0x0).
```

**Comment by sean-mcmanus** [comment]
@layzerar Yes those are normal debug output. The exceptions are handled and used for flow control by our parser. The process is not crashing.

**Comment by layzerar** [comment]
But, the IntelliSense still fallback to tag parser. And the output window print the following text, which indicate the IntelliSense Engine is not responsing.

```
Failed to read response from server: 20
Failed to read response from server: 8
Failed to read response from server: 8
```

Any idea what happened?

**Comment by sean-mcmanus** [comment]
@layzerar Yeah, the Microsoft.VSCode.CPP.IntelliSense.Msvc.exe process is crashing. If it's crashing when a file is opened, then copy the contents of the file to a different file and open the file as empty (or non-crashing file contents) and then attach a debugger and then paste the crashing contents into the file to obtain a crash call stack.

**Comment by layzerar** [comment]
@sean-mcmanus Very strange, I try to paste the code to source file one by one, everything is working fine. After I restart VSCode, and then open the souce file, the Microsoft.VSCode.CPP.IntelliSense.Msvc.exe process crashes immediately.

**Comment by layzerar** [comment]
Thank goodness, I catch 2 stacktrace by WinDbg. I hope this is helpful.

Stacktrace 1:
```
[0x0]   Microsoft_VSCode_CPP_IntelliSense_Msvc!memmove + 0x4e   
[0x1]   Microsoft_VSCode_CPP_IntelliSense_Msvc!std::vector<a_tracked_region *,std::allocator<a_tracked_region *> >::erase + 0x2e   
[0x2]   Microsoft_VSCode_CPP_IntelliSense_Msvc!`a_region_tracker::build_sections'::`2'::a_region_set::process + 0x3a   
[0x3]   Microsoft_VSCode_CPP_IntelliSense_Msvc!a_region_tracker::build_sections + 0x16f   
[0x4]   Microsoft_VSCode_CPP_IntelliSense_Msvc!a_tracking_manager::region_tracker_for + 0x5b   
[0x5]   Microsoft_VSCode_CPP_IntelliSense_Msvc!edge::a_tracked_file_position::current_position + 0x39   
[0x6]   Microsoft_VSCode_CPP_IntelliSense_Msvc!an_error_ptr_cmp::operator() + 0x3b   
[0x7]   Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Tree<std::_Tset_traits<an_error *,an_error_ptr_cmp,std::allocator<an_error *>,0> >::_Insert_hint<an_error * &,std::_Tree_node<an_error *,void *> *> + 0x76   
[0x8]   Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Tree<std::_Tset_traits<an_error *,an_error_ptr_cmp,std::allocator<an_error *>,0> >::insert<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<an_error *> > > > + 0x32   
[0x9]   Microsoft_VSCode_CPP_IntelliSense_Msvc!a_file_error_tracker::process_pending_errors + 0x1a   
[0xa]   Microsoft_VSCode_CPP_IntelliSense_Msvc!an_error_manager::process_pending_errors + 0x11   
[0xb]   Microsoft_VSCode_CPP_IntelliSense_Msvc!edge::an_edge_translation_unit_impl::reinitialize_without_fallback + 0x3b7   
[0xc]   Microsoft_VSCode_CPP_IntelliSense_Msvc!edge::an_edge_translation_unit_impl::reinitialize + 0x17   
[0xd]   Microsoft_VSCode_CPP_IntelliSense_Msvc!edge::translation_unit::initialize + 0x160   
[0xe]   Microsoft_VSCode_CPP_IntelliSense_Msvc!edge_intellisense_server_impl::create_translation_unit + 0xbd   
[0xf]   Microsoft_VSCode_CPP_IntelliSense_Msvc!edge_intellisense_server_impl::handle_update_intellisense + 0x2f   
[0x10]   Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Func_impl_no_alloc<<lambda_9989b9b68229e91bc44ae358201c3e96>,void>::_Do_call + 0xc   
[0x11]   Microsoft_VSCode_CPP_IntelliSense_Msvc!work_queue::worker_proc + 0x7a   
[0x12]   Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Func_impl_no_alloc<<lambda_cd6ec53400d3f1066a03b3738e08d33d>,void>::_Do_call + 0xf   
[0x13]   Microsoft_VSCode_CPP_IntelliSense_Msvc!microsoft::vc::thread_pool::do_work + 0x13c   
[0x14]   Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_7a5c86eedba4f728bcdfee14fde4807b> >,std::default_delete<std::tuple<<lambda_7a5c86eedba4f728bcdfee14fde4807b> > > > >::_Go + 0x26   
```

Stacktrace 2:
```
[0x0]   ntdll_77b70000!RtlpLocateRelatedBlocks + 0xa0   
[0x1]   ntdll_77b70000!RtlpHpHeapHandleError + 0x44   
[0x2]   ntdll_77b70000!RtlpLogHeapFailure + 0x41   
[0x3]   ntdll_77b70000!RtlpAllocateHeap + 0x6d2   
[0x4]   ntdll_77b70000!RtlpAllocateHeapInternal + 0x179   
[0x5]   ntdll_77b70000!RtlAllocateHeap + 0x3e   
[0x6]   ntdll_77b70000!RtlDebugAllocateHeap + 0xdb   
[0x7]   ntdll_77b70000!RtlpAllocateHeap + 0xf9   
[0x8]   ntdll_77b70000!RtlpAllocateHeapInternal + 0x179   
[0x9]   ntdll_77b70000!RtlAllocateHeap + 0x3e   
[0xa]   Microsoft_VSCode_CPP_IntelliSense_Msvc!_calloc_base + 0x47   
[0xb]   Microsoft_VSCode_CPP_IntelliSense_Msvc!__vcrt_getptd_noexit + 0x4e   
[0xc]   Microsoft_VSCode_CPP_IntelliSense_Msvc!__vcrt_getptd + 0x5   
[0xd]   Microsoft_VSCode_CPP_IntelliSense_Msvc!__InternalCxxFrameHandler<__FrameHandler3> + 0x14   
[0xe]   Microsoft_VSCode_CPP_IntelliSense_Msvc!__CxxFrameHandler3 + 0x26   
[0xf]   ntdll_77b70000!ExecuteHandler2 + 0x26   
[0x10]   ntdll_77b70000!ExecuteHandler + 0x24   
[0x11]   ntdll_77b70000!KiUserExceptionDispatcher + 0x26   
[0x12]   0x2fcf468   
[0x13]   Microsoft_VSCode_CPP_IntelliSense_Msvc!`a_region_tracker::build_sections'::`2'::a_region_set::process + 0x3a   
[0x14]   Microsoft_VSCode_CPP_IntelliSense_Msvc!a_region_tracker::build_sections + 0x16f   
[0x15]   Microsoft_VSCode_CPP_IntelliSense_Msvc!a_tracking_manager::region_tracker_for + 0x5b   
[0x16]   Microsoft_VSCode_CPP_IntelliSense_Msvc!edge::a_tracked_file_position::current_position + 0x39   
[0x17]   Microsoft_VSCode_CPP_IntelliSense_Msvc!an_error_ptr_cmp::operator() + 0x3b   
[0x18]   Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Tree<std::_Tset_traits<an_error *,an_error_ptr_cmp,std::allocator<an_error *>,0> >::_Insert_hint<an_error * &,std::_Tree_node<an_error *,void *> *> + 0x76   
[0x19]   Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Tree<std::_Tset_traits<an_error *,an_error_ptr_cmp,std::allocator<an_error *>,0> >::insert<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<an_error *> > > > + 0x32   
[0x1a]   Microsoft_VSCode_CPP_IntelliSense_Msvc!a_file_error_tracker::process_pending_errors + 0x1a   
[0x1b]   Microsoft_VSCode_CPP_IntelliSense_Msvc!an_error_manager::process_pending_errors + 0x11   
[0x1c]   Microsoft_VSCode_CPP_IntelliSense_Msvc!edge::an_edge_translation_unit_impl::reinitialize_without_fallback + 0x3b7   
[0x1d]   Microsoft_VSCode_CPP_IntelliSense_Msvc!edge::an_edge_translation_unit_impl::reinitialize + 0x17   
[0x1e]   Microsoft_VSCode_CPP_IntelliSense_Msvc!edge::translation_unit::initialize + 0x160   
[0x1f]   Microsoft_VSCode_CPP_IntelliSense_Msvc!edge_intellisense_server_impl::create_translation_unit + 0xbd   
[0x23]   Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Func_impl_no_alloc<<lambda_cd6ec53400d3f1066a03b3738e08d33d>,void>::_Do_call + 0xf  
```

Version info of my vscode:
```
版本: 1.29.1 (user setup)
提交: bc24f98b5f70467bc689abf41cc5550ca637088e
日期: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
架构: x64
```

ms-vscode.cpptools: `0.20.1`

**Comment by johannesegger** [comment]
Thanks for your response. This issue seems to drift apart. Do you want me to create a new one?

The non-working machine has the following Windows edition:

![grafik](https://user-images.githubusercontent.com/237707/49211212-567aed80-f3bf-11e8-978c-f9a6439d8593.png)

And `C:\Windows\SysWOW64` contains the following files starting with `api-ms-win-`:
```
api-ms-win-core-console-l1-1-0.dll
api-ms-win-core-datetime-l1-1-0.dll
api-ms-win-core-debug-l1-1-0.dll
api-ms-win-core-delayload-l1-1-0.dll
api-ms-win-core-errorhandling-l1-1-0.dll
api-ms-win-core-fibers-l1-1-0.dll
api-ms-win-core-file-l1-1-0.dll
api-ms-win-core-file-l1-2-0.dll
api-ms-win-core-file-l2-1-0.dll
api-ms-win-core-handle-l1-1-0.dll
api-ms-win-core-heap-l1-1-0.dll
api-ms-win-core-interlocked-l1-1-0.dll
api-ms-win-core-io-l1-1-0.dll
api-ms-win-core-libraryloader-l1-1-0.dll
api-ms-win-core-localization-l1-1-0.dll
api-ms-win-core-localization-l1-2-0.dll
api-ms-win-core-localregistry-l1-1-0.dll
api-ms-win-core-memory-l1-1-0.dll
api-ms-win-core-misc-l1-1-0.dll
api-ms-win-core-namedpipe-l1-1-0.dll
api-ms-win-core-processenvironment-l1-1-0.dll
api-ms-win-core-processthreads-l1-1-0.dll
api-ms-win-core-processthreads-l1-1-1.dll
api-ms-win-core-profile-l1-1-0.dll
api-ms-win-core-rtlsupport-l1-1-0.dll
api-ms-win-core-string-l1-1-0.dll
api-ms-win-core-synch-l1-1-0.dll
api-ms-win-core-synch-l1-2-0.dll
api-ms-win-core-sysinfo-l1-1-0.dll
api-ms-win-core-threadpool-l1-1-0.dll
api-ms-win-core-timezone-l1-1-0.dll
api-ms-win-core-util-l1-1-0.dll
api-ms-win-core-xstate-l1-1-0.dll
api-ms-win-core-xstate-l2-1-0.dll
api-ms-win-crt-conio-l1-1-0.dll
api-ms-win-crt-convert-l1-1-0.dll
api-ms-win-crt-environment-l1-1-0.dll
api-ms-win-crt-filesystem-l1-1-0.dll
api-ms-win-crt-heap-l1-1-0.dll
api-ms-win-crt-locale-l1-1-0.dll
api-ms-win-crt-math-l1-1-0.dll
api-ms-win-crt-multibyte-l1-1-0.dll
api-ms-win-crt-private-l1-1-0.dll
api-ms-win-crt-process-l1-1-0.dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-stdio-l1-1-0.dll
api-ms-win-crt-string-l1-1-0.dll
api-ms-win-crt-time-l1-1-0.dll
api-ms-win-crt-utility-l1-1-0.dll
api-ms-win-downlevel-advapi32-l1-1-0.dll
api-ms-win-downlevel-advapi32-l2-1-0.dll
api-ms-win-downlevel-normaliz-l1-1-0.dll
api-ms-win-downlevel-ole32-l1-1-0.dll
api-ms-win-downlevel-shell32-l1-1-0.dll
api-ms-win-downlevel-shlwapi-l1-1-0.dll
api-ms-win-downlevel-shlwapi-l2-1-0.dll
api-ms-win-downlevel-user32-l1-1-0.dll
api-ms-win-downlevel-version-l1-1-0.dll
api-ms-win-security-base-l1-1-0.dll
api-ms-win-security-lsalookup-l1-1-0.dll
api-ms-win-security-sddl-l1-1-0.dll
api-ms-win-service-core-l1-1-0.dll
api-ms-win-service-management-l1-1-0.dll
api-ms-win-service-management-l2-1-0.dll
api-ms-win-service-winsvc-l1-1-0.dll
```

**Comment by sean-mcmanus** [comment]
@layzerar Yes, we're aware of that crash and it's a top hitter for us. It repros with Visual Studio as well. The region tracker for namespace/preprocessor/etc. regions is encountering an "end" without a beginning. Unfortunately, we don't think we can fix this without having a repro, i.e. a small isolated sample of code that causes this. Is there some sort of unusual code occurring, such as `#includes` inside of a scope?

@johannesegger Your machine specs match what I used. You can file a new issue if you want. I noticed your c_cpp_properties.json has no configurations in it, which might be causing a problem. Are you able to add a config?

**Comment by johannesegger** [comment]
Oh yeah, on the working machine it tells me that I have to add a config, I would expected the error to occur on the non-working machine once the process stays alive. But I can try adding a config on the non-working machine.

**Comment by layzerar** [comment]
@sean-mcmanus 
In my case, unexpectedly, it's a simple assignment statement in a setter method which cause the crash of IntelliSense process. If I comment the assignment statement, everything is okay. I find the fact by commenting changes line by line. Another notable thing is if I open problematic header file first, then open other source files it won't cause the break. I think this is the reason why just paste the code won't cause the break.

The outline of the problematic header file is very simple, contain one include guard, one include statement, one enum and one class. And the entire project can be compiled by vs2015 and vs2017.

I gave it try, but I cannot give out the isolated sample of code that causes this. If you wish, I can send you a dump file with full memory.

**Comment by sean-mcmanus** [comment]
@layzerar When the header file is opened first, we try to create a translation unit for that, possibly picking a different .c/cpp file as the source file, but if you open the source file first then the headers get associated with that cpp file. A dmp file could possibly contain the source code so you may not want to send us that. We have a [known bug](https://github.com/Microsoft/vscode-cpptools/issues/1525) with IntelliSense offsets being incorrect when UTF-8 characters > 1 byte are use, which could possibly lead to this crash -- could that be the case for you?

**Comment by layzerar** [comment]
@sean-mcmanus I sent the dump file to your email `seanmcm@microsoft.com` a few days ago. 
Is there any progress now?

**Comment by sean-mcmanus** [comment]
@layzerar Yeah, our next Insiders release might have a fix, but we're not 100% sure.

**Comment by sean-mcmanus** [comment]
Our latest Insiders release fixed some bugs which could lead to these crashes: https://github.com/Microsoft/vscode-cpptools/releases . If you're using VS Code Insiders or have http.proxySupport not set to "off", you might not get the 0.21.0-insiders2 update automatically with C_Cpp.updateChannel set to "Insiders".

**Comment by layzerar** [comment]
@sean-mcmanus I tried insiders2 just now. It really fix my problem. Nice work!

**Comment by brianleu** [comment]
@sean-mcmanus what does it mean if Microsoft.VSCode.Extension.exe doesn't show up as an available process to debug when I'm halted on the 'util.setProgress(...' as indicated above?

**Comment by sean-mcmanus** [comment]
@brianleu That is bad. It means the process failed to launch or crashed during initialization. Can you a file a new bug with more repro info?

**Comment by OlegZv** [comment]
@sean-mcmanus  Unfortunately insider 2 still throws me the same error 

https://github.com/Microsoft/vscode/issues/65709

**Comment by sean-mcmanus** [comment]
@OlegSomov Can you file a new bug at https://github.com/Microsoft/vscode-cpptools/issues ? We need more repro info or a call stack of the crashing process. Or maybe if you run something like Process Monitor for Microsoft.VSCode.CPP.Extension.exe.
