### ISSUE TITLE
Language service closing on Win7 SP1

### ISSUE THREAD

**Issue by johannesegger** [microsoft/vscode-cpptools#2878]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 7 Enterprise, SP1
- VS Code Version: 1.29.1
- C/C++ Extension Version: 0.21.0-insiders and 8c53c027cab1f5b110367cb08ab8286a1a98ea80
- Other extensions you installed (and if the issue persists after disabling them): [mkaufman.HTMLHint](https://marketplace.visualstudio.com/items?itemName=mkaufman.HTMLHint), [hdg.live-html-previewer](https://marketplace.visualstudio.com/items?itemName=hdg.live-html-previewer); Disabling them doesn't change anything.
- A clear and concise description of what the bug is.
  - After starting VSCode and opening a .c file I get the error message "The language server crashed 5 times in the last 3 minutes. It will not be restarted.". At no point I see `Microsoft.VSCode.CPP.Extension.exe` running in the Task Manager. When I set a breakpoint after `languageClient.start();` I can attach a debugger to `Microsoft.VSCode.CPP.Extension.exe`. When continuing running the extension the process seems to exit normally (i.e. the debugger output doesn't show any exceptions, only symbol loaded and thread exited messages). I can run `Microsoft.VSCode.CPP.Extension.exe` manually from the command line and it stays alive (i.e. it doesn't close itself and doesn't write anything to the console) which tells me it's not any anti-virus software (right?). For maybe some more details have a look at some comments I made in [this](https://github.com/Microsoft/vscode-cpptools/issues/2768) issue.

**To Reproduce**

![image](https://user-images.githubusercontent.com/237707/49143568-94aed900-f2fb-11e8-901b-c787ac3c22dd.gif)

**Expected behavior**

The error shouldn't occur and intellisense should work.

**Screenshots**

\-

**Additional context**

\-

**Comment by johannesegger** [comment]
As suggested [in the linked issue](https://github.com/Microsoft/vscode-cpptools/issues/2768#issuecomment-442981197) I added a configuration to `c_cpp_properties.json`. The file now looks like this:

```json
{
    "configurations": [
        {
            "name": "Win32",
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:\\Users\\eggj\\scoop\\apps\\gcc\\current\\bin\\gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

The compiler path is correct, i.e. gcc.exe is there.
Unfortunately I still get the language server crashed message.

**Comment by johannesegger** [comment]
I attached `x32dbg` to `Microsoft.VSCode.CPP.Extension.exe` and recorded the session. I couldn't find anything useful, but maybe you can:

![cxemmpp0oy](https://user-images.githubusercontent.com/237707/49282500-9d381880-f48f-11e8-8dac-b812898f2e37.gif)

After the session the x32dbg logs were this:

```
Database file: C:\scoop\apps\x64dbg\current\release\x32\db\Microsoft.VSCode.CPP.Extension.exe.dd32
Process Started: 010B0000 \\schulserver\lehrerhome$\Lehrer\EGGJ\Workspace\vscode-cpptools\Extension\bin\Microsoft.VSCode.CPP.Extension.exe
DLL Loaded: 77270000 C:\Windows\SysWOW64\ntdll.dll
Thread 113C created, Entry: microsoft.vscode.cpp.extension.015DCE01
Thread 1408 created, Entry: microsoft.vscode.cpp.extension.015DCE01
Thread 19A4 created, Entry: microsoft.vscode.cpp.extension.015DCE01
Thread 2050 created, Entry: microsoft.vscode.cpp.extension.015DCE01
Thread 193C created, Entry: microsoft.vscode.cpp.extension.015DCE01
Thread 1E90 created, Entry: microsoft.vscode.cpp.extension.015DCE01
Thread 1A18 created, Entry: microsoft.vscode.cpp.extension.015DCE01
Thread 1F44 created, Entry: microsoft.vscode.cpp.extension.015DCE01
Thread 2238 created, Entry: microsoft.vscode.cpp.extension.015DCE01
Thread 218C created, Entry: microsoft.vscode.cpp.extension.015DCE01
Thread 2314 created, Entry: microsoft.vscode.cpp.extension.015DCE01
Thread 1908 created, Entry: microsoft.vscode.cpp.extension.015DCE01
Thread 1BC8 created, Entry: microsoft.vscode.cpp.extension.015DCE01
DLL Loaded: 76520000 C:\Windows\SysWOW64\kernel32.dll
DLL Loaded: 74D40000 C:\Windows\SysWOW64\KernelBase.dll
DLL Loaded: 76B30000 C:\Windows\SysWOW64\user32.dll
DLL Loaded: 75220000 C:\Windows\SysWOW64\gdi32.dll
DLL Loaded: 74B60000 C:\Windows\SysWOW64\lpk.dll
DLL Loaded: 76330000 C:\Windows\SysWOW64\usp10.dll
DLL Loaded: 74C90000 C:\Windows\SysWOW64\msvcrt.dll
DLL Loaded: 74DB0000 C:\Windows\SysWOW64\advapi32.dll
DLL Loaded: 75200000 C:\Windows\SysWOW64\sechost.dll
DLL Loaded: 75110000 C:\Windows\SysWOW64\rpcrt4.dll
DLL Loaded: 74990000 C:\Windows\SysWOW64\sspicli.dll
DLL Loaded: 74980000 C:\Windows\SysWOW64\cryptbase.dll
DLL Loaded: 756C0000 C:\Windows\SysWOW64\shell32.dll
DLL Loaded: 75490000 C:\Windows\SysWOW64\shlwapi.dll
DLL Loaded: 749F0000 C:\Windows\SysWOW64\ole32.dll
DLL Loaded: 753F0000 C:\Windows\SysWOW64\oleaut32.dll
DLL Loaded: 6F830000 C:\Windows\SysWOW64\mscoree.dll
DLL Loaded: 74C00000 C:\Windows\SysWOW64\imm32.dll
DLL Loaded: 76450000 C:\Windows\SysWOW64\msctf.dll
DLL Loaded: 72BA0000 C:\Windows\SysWOW64\api-ms-win-core-synch-l1-2-0.dll
Thread 1120 created, Entry: <ntdll.DbgUiRemoteBreakin>
Attach breakpoint reached!
Thread 1120 exit
Thread 1E90 exit
Thread 218C exit
Thread 1BC8 exit
Thread 1408 exit
Thread 202C exit
Thread 2238 exit
Thread 1F44 exit
Thread 1908 exit
Thread 2050 exit
Thread 193C exit
Thread 2314 exit
Thread 113C exit
Thread 1A18 exit
Process stopped with exit code 0xC0000417
Saving database to C:\scoop\apps\x64dbg\current\release\x32\db\Microsoft.VSCode.CPP.Extension.exe.dd32 0ms
Debugging stopped!
```

**Comment by sean-mcmanus** [comment]
I don't see anything strange in that video, but the "0xC000417" return code makes it appear that the C-runtime is aborting due to invalid input (https://stackoverflow.com/questions/3467444/invalid-cruntime-parameter-itoa-s?noredirect=1), but I don't know why it isn't able to give a call stack. Do you know if you were able to get symbols to load from http://msdl.microsoft.com/download/symbols ? Is there a reason you're not using the VS Code debugger to attach, i.e. did you have a config problem? Also, I noticed "apphelp.dll" isn't loading for you after the "api-ms-" dll loads.

Do you get any useful error logging when you [enable logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and set C_Cpp.loggingLevel to the hidden value of "9", assuming the "Debug" value isn't enough? Maybe next week we could publish a debug build with assertions enabled to see if that gives any info.

**Comment by johannesegger** [comment]
I tried debugging with VSCode, but it doesn't give as much information as x32dbg (in VSCode all I got was basically the log output of x32dbg which you see above - symbols loaded and threads exited). So I'm sure that symbols got loaded in VSCode, but I forgot to set the symbol server in x32dbg (don't know yet where I can set that - will try that next week).

I will try enabling logging and setting the log level next week when I'm again at that (stupid) non-working machine.

A debug build of `Microsoft.VSCode.CPP.Extension.exe` would be great, I'm sure we get more information out of it, thanks a lot.

**Comment by johannesegger** [comment]
Debugging with VSCode gives me the following logs:

```
-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Loaded '\\schulserver\lehrerhome$\Lehrer\EGGJ\Workspace\vscode-cpptools\Extension\bin\Microsoft.VSCode.CPP.Extension.exe'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\user32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\gdi32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\lpk.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\usp10.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\msvcrt.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\advapi32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\sechost.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\sspicli.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\cryptbase.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\shell32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\shlwapi.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\ole32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\oleaut32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\mscoree.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\imm32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\msctf.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\api-ms-win-core-synch-l1-2-0.dll'. Symbols loaded.
The thread 8508 has exited with code 0 (0x0).
The thread 5436 has exited with code -1073740777 (0xc0000417).
The thread 6064 has exited with code -1073740777 (0xc0000417).
The thread 4812 has exited with code -1073740777 (0xc0000417).
The thread 7052 has exited with code -1073740777 (0xc0000417).
The thread 3860 has exited with code -1073740777 (0xc0000417).
The thread 5100 has exited with code -1073740777 (0xc0000417).
The thread 5892 has exited with code -1073740777 (0xc0000417).
The thread 8548 has exited with code -1073740777 (0xc0000417).
The thread 8992 has exited with code -1073740777 (0xc0000417).
The thread 7036 has exited with code -1073740777 (0xc0000417).
The thread 7796 has exited with code -1073740777 (0xc0000417).
The thread 8592 has exited with code -1073740777 (0xc0000417).
The thread 8380 has exited with code -1073740777 (0xc0000417).
The program '[4048] Microsoft.VSCode.CPP.Extension.exe' has exited with code -1073740777 (0xc0000417).
```

So symbols got loaded it seems.

I tried to get debug output, but the extension doesn't seem to log anything at all. What did I do wrong?

![1ghfo3s2of](https://user-images.githubusercontent.com/237707/49426112-d201e380-f79f-11e8-9cf7-52c06fa111a6.gif)

**Comment by johannesegger** [comment]
0.21.0-insiders2 doesn't work for me unfortunately.

![error](https://user-images.githubusercontent.com/237707/50211609-5b590e80-0379-11e9-8471-7a16f3f5c692.png)

**Comment by sean-mcmanus** [comment]
Yeah, I didn't expect 0.21-insiders2 to fix this -- it looks like the process is crashing before our logging system is initialized. My best guess is that your C runtime is incompatible or too old/buggy. Windows 10 ships a new "Universal" C runtime, but if you want to stay on Win7 you could try installing a C runtime from something like the links at https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/microsoft-visual-c-runtime-library-error-in/9f6ae061-102b-402a-b3f7-89fda80cd0cd .

**Comment by johannesegger** [comment]
Ok, I can try that soon. *I* don't really want to stay on Win7, but at the moment it seems I have to.

I'll try upgrading according to the link suggested, but I won't be at the Win7 machine for two weeks.

**Comment by johannesegger** [comment]
Is this what you meant? This has already been installed.

![explorer_k6t24v5csl](https://user-images.githubusercontent.com/237707/50816624-67edd880-1321-11e9-9f60-ba11720911f5.png)

**Comment by sean-mcmanus** [comment]
Yeah, it looks like yoiu have the VC++ redists. Have you tried 0.21.0-insiders3 yet? We fixed 4 more crashes with that and signed the binary in case your virus scan is blocking it from working.

Another user reported an invalid parameter crash (but on Win10) at https://github.com/Microsoft/vscode-cpptools/issues/2972 but we still haven't gotten enough info to fix it.

**Comment by johannesegger** [comment]
I tried `0.21.0-insiders3` just now. Unfortunately it's still the same. `Microsoft.VSCode.CPP.Extension.exe` isn't even running when I only open `c_cpp_properties.json`. The error message comes as soon as I open a `.c` file.

**Comment by sean-mcmanus** [comment]
Are you doing Open folder or open file? Our extension process should activate if Open folder is done and a `./vscode/c_cpp_properties.json` exists.

@bobbrow Do you have any other troubleshooting ideas?

**Comment by johannesegger** [comment]
It's `Open folder`. When I do the same on the Win10 machine I can see the process running (I don't even need to open `c_cpp_properties.json` - it's enough when the file exists), but on the Win7 machine it's not running, but I can't tell if it's already crashed or not even started. The error message then comes as soon as I open a .c file.

**Comment by bobbrow** [comment]
From your log: *Error code: (NTSTATUS) 0xc0000417 (3221226519) - An invalid parameter was passed to a C runtime function.*
  * I didn't see the VC++ 2015 redist in your list.  We do build against the 2017 CRT, but perhaps there is some other dependency lingering.

**Comment by sean-mcmanus** [comment]
@bobbrow Ah, yeah, we have a dependency on mscoree.dll for support of the /clr cl.exe flag might pull in a dependency on the VC 2015 libs -- it's shipped in the Microsoft .NET 4.6.1 SDK. Maybe we need to ship that DLL next to our binary? I can investigate this on my Win7 VM.

**Comment by johannesegger** [comment]
.NET 4.6.1 SDK is already installed.

When installing the VC++ 2015 redist from https://www.microsoft.com/en-us/download/details.aspx?id=52685 I get an error that says that a newer version is already installed.

I also tried adding most of the C++ components that I found in the Visual Studio installer, but I didn't find the VC++ 2015 redist in the list of installed apps.

**Comment by sean-mcmanus** [comment]
That link is the incorrect "RC" (Release Candidate version) of the redist (released a month before the final version), but if it says you have a newer version then it sounds like it think you have the non-RC already. But if you're not seeing that in your installed programs then it sounds like the installer is in a buggy state. However, my Win7 VM doesn't have the VC++ 2015 redist installed at all and our extension is working fine on it. I also have the Microsoft .NET Framework 4.5.2. And I have a bunch of Windows updates.

I noticed that the apphelp.dll doesn't appear in your logs. Do you have that on your machine?

```
Loaded 'C:\Windows\SysWOW64\api-ms-win-core-synch-l1-2-0.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\SysWOW64\apphelp.dll'. Cannot find or open the PDB file.
The thread 4088 has exited with code 0 (0x0).
```

**Comment by johannesegger** [comment]
Yep, I can see apphelp.dll.

![grafik](https://user-images.githubusercontent.com/237707/51193309-dd8d1200-18e8-11e9-8aa2-ec5a43896899.png)

We're missing .NET Framework 4.5.2. Do you think this might be a problem?

![grafik](https://user-images.githubusercontent.com/237707/51193393-0c0aed00-18e9-11e9-8654-f9dc1a93490c.png)

`apphelp.dll` isn't even loading for me:

```
-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Loaded '\\schulserver\lehrerhome$\Lehrer\EGGJ\Workspace\vscode-cpptools\Extension\bin\Microsoft.VSCode.CPP.Extension.exe'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\user32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\gdi32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\lpk.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\usp10.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\msvcrt.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\advapi32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\sechost.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\sspicli.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\cryptbase.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\shell32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\shlwapi.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\ole32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\oleaut32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\mscoree.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\imm32.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\msctf.dll'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\api-ms-win-core-synch-l1-2-0.dll'. Symbols loaded.
The thread 21280 has exited with code 0 (0x0).
The thread 12284 has exited with code -1073740777 (0xc0000417).
The thread 9180 has exited with code -1073740777 (0xc0000417).
The thread 20740 has exited with code -1073740777 (0xc0000417).
The thread 20532 has exited with code -1073740777 (0xc0000417).
The thread 20700 has exited with code -1073740777 (0xc0000417).
The thread 21312 has exited with code -1073740777 (0xc0000417).
The thread 11220 has exited with code -1073740777 (0xc0000417).
The thread 9072 has exited with code -1073740777 (0xc0000417).
The thread 20664 has exited with code -1073740777 (0xc0000417).
The thread 268 has exited with code -1073740777 (0xc0000417).
The thread 17192 has exited with code -1073740777 (0xc0000417).
The thread 15452 has exited with code -1073740777 (0xc0000417).
The thread 9980 has exited with code -1073740777 (0xc0000417).
The program '[20696] Microsoft.VSCode.CPP.Extension.exe' has exited with code -1073740777 (0xc0000417).

```

**Comment by sean-mcmanus** [comment]
I uninstalled the .NET 4.5.2, but everything is still working for me. I also installed .NET 4.7.2.

My only guess is that maybe you need some Windows update? Did you install all the optional updates?

Are you able to get a repro on a clean Windows 7 VM? The OS could be in some corrupted state.

**Comment by johannesegger** [comment]
Yep, I can try starting with a clean VM and then step by step trying to configure it like the non-working machine and see if and when it breaks. That'll take some time for sure.

**Comment by Colengms** [comment]
There hasn't been activity on this issue for quite a while.  If there is still an issue here, please re-open or open a new issue.
