### ISSUE TITLE
Formatting code on save pastes garbage from clipboard.

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#2941]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.30
- C/C++ Extension Version: v0.20.1
- Other extensions you installed (and if the issue persists after disabling them):
   cmake v0.0.17
  cmake-tools v1.1.3 
  code-settings-sync v3.2.4
  cpptools v0.20.1
  dark-plus-material v1.4.5
  Doxygen v1.0.0
  gitlens v9.2.1
  hg v1.2.3
  linkerscript v1.0.0
  material-icon-theme v3.6.1
  meson v1.1.1
  plantuml v2.10.1
  python v2018.12.1
  vsc-material-theme v2.6.2

The issue persist after disabling cmake-tools extension

- A clear and concise description of what the bug is.

**To Reproduce**

1- Enable FormatOnSave
2- Edit multiple files on a folder using the clipboard. 
3- Once in a while when you save reformatting the file results in trashing the content.

**Expected behavior**

**Screenshots**

**Additional context**

--------------------
Done.

**Comment by sean-mcmanus** [comment]
Does this bug repro with 0.21.0-insiders2 at https://github.com/Microsoft/vscode-cpptools/releases ?

**Comment by sean-mcmanus** [comment]
If you're still hitting this issue, I would recommend setting C_Cpp.formatting to "Disabled" and using the "Clang-Format" extensions to format. I don't believe the corruption is caused by formatting, but by corruption to our internal document text buffer object which is passed as input to the formatting code (i.e. correctly formatting corrupted input). We have some "debug corruption" code -- maybe we could add a flag to enable users to turn that on, or maybe we should try to enable that by default so users get the "Document corruption detected" message so they can undo their formatting.

**Comment by sean-mcmanus** [comment]
If you [set Debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) you can see the formatting input and raw output to see at what point the corruption occurs.

**Comment by ghost** [comment]
I've tried with vscode insiders (same behaviour) but not with the extension insider.

I'll switch on the debug logging and paste the result as soon as it is possible.

**Comment by ghost** [comment]
I've installed the extension 0.21.0-insiders2 and it happened again. 
It added a straw endif  to a header

>
>  **endif**
>#endif

I think that the interesting line in the log is 

> Formatting diffed output:   endif

PS.
I havent appended the full log cause it is our internal software, but if it is interesting I'll try to edit generic software to replicate

**Comment by ghost** [comment]
Wait... I've opened the workspace from a simbolic link. and sometimes file are reopened using the full path. Could this be related to the problem ?

**Comment by ghost** [comment]
It seems that not using symbolic link into the path the problem has been fixed.

**Comment by sean-mcmanus** [comment]
Oh, but that means we still have a bug in our code. However, I tried opening a symlink folder (on Linux), but I still wasn't able to repro the bug (i.e. via open files, editing, and then format/saving). And I don't see any files getting opened "using the full path".

**Comment by ghost** [comment]
It was by no means systematic and I don't know if it is important but involved cmake-tools and a compilation database. Anyway today, without the symbolic link, a full day without the bug.
