### ISSUE TITLE
Recursive includes don't add paths used by forcedInclude files

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2986]
Use a forcedInclude file that has a `#include` to a non-local file that is under a recursive include, e.g. if the includePath is "${workspaceFolder}/**", then the forcedInclude could use `"#include <subfolder/file.h>"`.

Bug: The subfolder is incorrectly not getting added to the includePath for IntelliSense.

This was initially reported in bug https://github.com/Microsoft/vscode-cpptools/issues/2610 .

**Comment by sean-mcmanus** [comment]
Fixed with our latest [0.21.0-insiders3](https://github.com/Microsoft/vscode-cpptools/releases). Setting `C_Cpp.updateChannel` to `"Insiders"` is another way to get the update.

**Comment by JJChasel** [comment]
> Fixed with our latest [0.21.0-insiders3](https://github.com/Microsoft/vscode-cpptools/releases). Setting `C_Cpp.updateChannel` to `"Insiders"` is another way to get the update.

Does this merge in the latest win32 release? I download it but this issue still exist as follow
- Folder Structure:
- proj
  - someheader.h
  - core
    - src
      - test.c
    - inc
      - test.h

and where
```C
// test.c
#include "inc/test.h"
// codes
```
When NOT force include someheader.h, it works will. After add forced include to the config file, it can't found test.h

**Comment by sean-mcmanus** [comment]
@JJChasel Thanks a lot for reporting this -- your repro is different from this bug's, but it's a regression, seemingly caused by the fix for this bug -- we'll try to fix it for 0.21.0.

**Comment by sean-mcmanus** [comment]
@JJChasel Update -- the bug you reported has been fixed for our next release...expected "soon".

**Comment by sean-mcmanus** [comment]
@JJChasel The bug you found with 0.21.0-insiders3 should be fixed now with 0.21.0.
