### ISSUE TITLE
Intellisense won't work: "Failed to create IntelliSense client"

### ISSUE THREAD

**Issue by JoaoVictorDaijo** [microsoft/vscode-cpptools#3139]
So I'm a noob here I'm still studying so I might have some problems to describe my issue.

I'm trying to use Intellisense but it just won't work. I think I configured my c_pp_properties in the correct way. Here it is (Yes I know I have multiple entries in the include, that was me trying to fix the problem):

`{

    "configurations": [
        {

            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\\MinGW\\lib\\gcc\\mingw32\\8.2.0\\include\\",
                "C:\\MinGW\\include",
                "C:\\MinGW\\",
                "C:\\MinGW\\lib\\gcc\\mingw32\\8.2.0\\include\\c++"
            ],

            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],

            "compilerPath": "C:\\MinGW\\bin\\gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceFolder}",
                    "C:\\MinGW\\lib\\gcc\\mingw32\\8.2.0\\include\\c++"
                ],

                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }

        }

    ],

    "version": 4

}`

When I read the Visual Studio Code console output for C++ it constantly gives me this error over and over:
Failed to spawn IntelliSense process: Unable to start child process!
Failed to spawn IntelliSense process: Unable to start child process!
Failed to create IntelliSense client. Can't create intellisense client for E:\ONEDRIVE\DOCUMENTOS\TRABALHO\MAIN.CPP

I searched for this error, looks like it's related to the use of some symbols in the folders, a guy had some kanji characters in his folder and got the same issue, another person had a space in his username in Windows 10 and got this issue too.

So I created a new user with no spaces open the same project, in the same location with the same .json and intellisense worked fine. 
I'm not sure if there's another fix for this but creating a new user is far from ideal, it's taking space from my SSD and I can't move all my stuff to this new user so I have to login into this user to fix Intellisense.

Of course it might be something else that was fixed creating a user. I can create another user with spaces again and check if Intellisense stops if needed.

**Comment by sean-mcmanus** [comment]
Can you try out 0.22.0-insiders? It may have fixed this. You can get it via setting the C_Cpp.updateChannel setting to "Insiders", or downloading it manually from https://github.com/Microsoft/vscode-cpptools/releases .

If it's still broken, the known workaround is to delete the document in `C:\Users\` that is the same as the first word in your user name.

**Comment by JoaoVictorDaijo** [comment]
I changed the setting to insider, installed 0.22.0-insiders, reloaded the window as asked even closed and opened Visual Code unfortunately still the same issue and also the same problem showing in the console.
What this file do? I can just delete it with no issues?

Edit: Yes I moved that file to another place and this fixed my issue. But I still have the same question can I just delete this file and don't care at all? Because it fixed my problem.

A shame the insider build didn't fix the issue, I can hold that file and test more builds as you release to check if the bug is nailed.

**Comment by sean-mcmanus** [comment]
Thanks for letting us know the bug wasn't fixed with 0.22.0-insiders (the issue we fixed must have been unrelated). We do intend to fix the bug -- we're just not sure when yet. Previously it was reported as https://github.com/Microsoft/vscode-cpptools/issues/3052 and https://github.com/Microsoft/vscode-cpptools/issues/1377 .

I don't know what the file is or what program created the file. Other users have reported that they deleted the file and it fixed their IntelliSense. You could also try moving it to a different location or renaming it.

**Comment by sean-mcmanus** [comment]
The bug with IntelliSense not working on Windows when the username has a space in it should be fixed with 0.22.0-insiders2: https://github.com/Microsoft/vscode-cpptools/releases .

**Comment by orblazer** [comment]
Hello,
This bug is still present in `0.25.1`. The error :
```
Failed to create IntelliSense client. Can't create intellisense client for C:\USERS\DORIA\DOCUMENTS\UNREAL PROJECTS\BEATRYTHMIC\SOURCE\BEATRYTHMIC\FILEBPFUNCTIONLIBRARY.H
```

Thanks.

**Comment by ranjithpp** [comment]
i am on 1.39.2 vs code, 
Can't create IntelliSense client for <filename> error is coming.

**Comment by sean-mcmanus** [comment]
@ranjithpp Can you create a new bug with more repro details? "Failed to create IntelliSense client" is just a general symptom.

**Comment by felwolff** [comment]
I may have a similar problem here. I get the "Failed to create IntelliSense client for .../config.h", where config.h is created by autotools. This results in many inactive code region which are protected by ifdefs defined in config.h. This is super annoying and pretty hard to work with. 
Unfortunately, it's hard to reproduce, it only occurs in this one project. I'm using v0.26.2-insider. How can I collect more information about this issue?

**Comment by ariesdevil** [comment]
Encounter the same error just now.
