### ISSUE TITLE
[WSL] Debugger throwing errors - Command failed...$(uname) was unexpected at this time

### ISSUE THREAD

**Issue by EsmeAioli** [microsoft/vscode-cpptools#3150]
Type: Debugger
**Input information below**

There seems to be similar issues with gdb, but I'm definitely never seen this issue before. 
![image](https://user-images.githubusercontent.com/24488417/52556556-e27dac80-2e27-11e9-9639-ed46a579ac45.png)

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Windows 10, Version 1709; Ubuntu 18.04
- VS Code Version: 1.31.0 (on Windows)
- C/C++ Extension Version: 0.21.0

- Not really sure why clicking debug gives me this error. Thought I sat on the keyboard or something but as far as I've checked, don't think it's an issue on my end

**To Reproduce**
This is only a section of config.json. There's some configs from the Perl Debugger there too. Just attach debuggers for local and remote debugging. ~~Of note is that that debugger isn't quite working properly either - the yellow line showing where the debugger is in the code, and the stuff in inspect isn't quite showing all. Doing the same thing on my version of VSCode on Mac is having it work fine.~~ (This ended up being a different, separate issue that I fixed) 
"version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Bash on Windows Attach",
            "type": "cppdbg",
            "request": "attach", 
            "program": "/mnt/z/sgsxeris006/limxuan/Personal_Workspace/Scratch_Files/intellis", //i edited
            "processId": "${command:pickRemoteProcess}",
            "pipeTransport": {
                "debuggerPath": "/usr/bin/gdb",
                "pipeProgram": "${env:windir}\\sysnative\\bash.exe",
                "pipeArgs": ["-c"],
                "pipeCwd": ""
            },
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "sourceFileMap": {
                "/mnt/z": "z:\\"
            }
        },

1. Honestly all I did was to config with the settings stated in [here](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/Windows%20Subsystem%20for%20Linux.md) 
2. Clicked run, and this came up. 

**Additional context**
Can't get any log files, or debug errors - cause there are none, just that one popup. Wondering if it's similar to the issues in #2870 and https://github.com/Microsoft/WSL/issues/3679 

Any help would be great, thanks!

**Comment by pieandcakes** [comment]
@WardenGnaw can you look into this?

**Comment by flxflx** [comment]
Same problem here; same software versions except for Ubuntu being 16.04.

**Comment by flxflx** [comment]
The problem seems to be with `"processId":"${command:pickRemoteProcess}"`. Specifying the PID directly  solved this for me.

**Comment by sean-mcmanus** [comment]
Should be fixed with the latest insiders: https://github.com/Microsoft/vscode-cpptools/releases

**Comment by rakesh-mth** [comment]
It is not fixed for me even after switch to version 0.22.0-insiders2. Still have to use pid instead.


![image](https://user-images.githubusercontent.com/46665723/53967707-b8847680-40c3-11e9-8a2a-1ce6c6dbdfb5.png)

**Comment by WardenGnaw** [comment]
@rakesh-mth This issue was for the WSL scenario and has been resolved. Can you open a new issue and specify your host (Since you are using plink, it should be Windows) and remote machine OS?

**Comment by rakesh-mth** [comment]
@WardenGnaw Sure will open another issue. Host is windows 10 1803 and Remote machine is ubuntu 16.04.
