### ISSUE TITLE
Linux Debugger overrides setup command options

### ISSUE THREAD

**Issue by nsnerurkar** [microsoft/vscode-cpptools#3324]
Type: Debugger

- OS and Version: Debian 9
- VS Code Version: 1.32.3
- C/C++ Extension Version: 0.21.0

I work with applications which have dependencies on a large number of shared libraries. Usually, when using gdb outside of VSCode, I use "set auto-solib-add off" so that the software attaches faster. 

I added the following snippet in my launch.json -

"setupCommands":[
{"text": "set auto-solib-add off", 
 "description": "Turn off solib add",
 "ignoreFailures": true
}]

It seems when vscode launches gdb, it runs this command and then automatically overrides it with "set auto-solib-add on". 

**To Reproduce**
1. Create an attach configuration
2. add setupcommands as above

**Additional Info**
Snippet from log -
1: (838) <-1001-gdb-set target-async on
1: (839) ->1001^done
1: (839) ->(gdb)
1: (840) 1001: elapsed time 2
1: (847) <-1002-enable-pretty-printing
1: (848) ->1002^done
1: (848) ->(gdb)
1: (848) 1002: elapsed time 0
1: (849) <-1003-interpreter-exec console "set auto-solib-add off"
1: (849) ->1003^done
1: (850) ->(gdb)
1: (850) 1003: elapsed time 0
1: (850) <-1004-interpreter-exec console "set pagination off"
1: (850) ->=cmd-param-changed,param="pagination",value="off"
1: (851) ->1004^done
1: (851) ->(gdb)
1: (851) 1004: elapsed time 0
1: (851) <-1005-gdb-set auto-solib-add on
1: (851) ->1005^done
1: (851) ->(gdb)
1: (851) 1005: elapsed time 0

**Comment by WardenGnaw** [comment]
We have the capabilities for that in [MIEngine](https://github.com/Microsoft/MIEngine/commit/65b8ce405021b8e36c0dfb192a4ce181e96029fd) at the moment, but is not available through the VS Code extension. 

Work for this would be adding the following to our launch.json and have AD7 send it to MIEngine.
```
boolean SymbolInfoLoadAll 
string[] SymbolInfoExceptionList 
```

**Comment by penagos** [comment]
> We have the capabilities for that in [MIEngine](https://github.com/Microsoft/MIEngine/commit/65b8ce405021b8e36c0dfb192a4ce181e96029fd) at the moment, but is not available through the VS Code extension.
> 
> Work for this would be adding the following to our launch.json and have AD7 send it to MIEngine.
> 
> ```
> boolean SymbolInfoLoadAll 
> string[] SymbolInfoExceptionList 
> ```

Is there plans to support this in a future release?

**Comment by rlivings39** [comment]
Without the ability to add `set auto-solib-add off` in my `.gdbinit` starting up our software in the debugger becomes painfully slow. It can reach on the order of over a minute or two making the edit-debug-test cycle painfully slow. Please consider adding this.

**Comment by asdoi981x** [comment]
> Without the ability to add `set auto-solib-add off` in my `.gdbinit` starting up our software in the debugger becomes painfully slow. It can reach on the order of over a minute or two making the edit-debug-test cycle painfully slow. Please consider adding this.

Facing exactly the same issue here. Hopefully this will be added soon.

**Comment by rlivings39** [comment]
Thanks @WardenGnaw !

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.0-insiders .

**Comment by sean-mcmanus** [comment]
Fixed with 0.26.0.

**Comment by azertyalex** [comment]
I'm running version 1.1.3 and have the same issue
This is my config
```json
"configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/browser/build/browser",
            "args": [""],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true,
                },
                {
                    "description": "Disable loading symbols of shared libraries",
                    "text": "set auto-solib-add off",
                    "ignoreFailures": true,
                }
            ]
        }
]
```

Adding `set auto-solib-add off` to my .gdbinit file works though. Could this be broken again?

**Comment by KristoferHansson** [comment]
@WardenGnaw 
Running version v1.2.2 and it seems like the issue is still here

under configurations/setupCommands:
            {
               "description": "disable default loading of shared library symbols: set auto-solib-add 0",
               "text": "**set auto-solib-add 0**",
               "ignoreFailures": true,
            },

```
1: (352) <-1004-interpreter-exec console "set auto-solib-add 0"
1: (352) ->1004^done
...
1: (361) <-1009-gdb-set auto-solib-add on
1: (362) ->1009^done
1: (362) ->(gdb)
```

```
-exec show auto-solib-add
1: (555330) <-1471-interpreter-exec console "show auto-solib-add"
1: (555331) ->~"Autoloading of shared library symbols is on.\n"
1: (555331) ->1471^done
1: (555331) ->(gdb)
1: (555331) 1471: elapsed time 0
Autoloading of shared library symbols is on.
```
@azertyalex:
using symbolLoadInfo in launch.json seems to work but still seems to give a bit strange debug output
```
 "symbolLoadInfo":{
            "loadAll": false,
            "exceptionList": ""
         },
```

Whit this I'm now getting one of these for each shared library it want's to load but doesn't/fails:
```
1: (12982) Send Event AD7ModuleLoadEvent
Loaded '/opt/x86-our-linux/usr/lib/libxxxx.so.x'. Cannot find or open the symbol file.
...
...
1: (13049) Send Event AD7ModuleLoadEvent
Loaded '/opt/x86-our-linux/usr/lib/libzzzz.so.0'. Cannot find or open the symbol file.

```

**Comment by samuelpmish** [comment]
I'm hitting the same problem as well. Running `gdb` directly on an executable starts up instantly, but debugging through vscode takes a couple of minutes to load a bunch of shared system libraries.

I have 
```json
{
    "description": "Disable loading symbols of shared libraries",
    "text": "set auto-solib-add off",
    "ignoreFailures": true,
}
```

in my launch.json under `setupCommands`.

adding `set auto-solib-add off` to .gdbinit doesn't seem to help either.

**Comment by borjamunozf** [comment]
Same issue over here. Tested also with .gdbinit but the auto-solib-add-off is not being considered.
