### ISSUE TITLE
Extension stops after a while

### ISSUE THREAD

**Issue by aleexf** [microsoft/vscode-cpptools#3543]
**Type: LanguageService**

**Describe the bug**
- OS and Version: _macOS Mojave 10.14.4_
- VS Code Version: _1.33.1_
- C/C++ Extension Version: _0.23.0-insiders_
- Other extensions you installed (and if the issue persists after disabling them): _Visual Studio IntelliCode - Preview, Debugger for Java, Java Dependency Viewer, Java Extension Pack, Java Test Runner, Language Support for Java(TM) by Red Hat, Maven for Java_ (all are disabled).
- A clear and concise description of what the bug is: The extension stops it work unexpectedly after a while (about 15 minutes). It looks like the process is not responding. At this time the errors doesn't disappear even if I erase all code from the file, new errors don't appears, autocomplete doesn't work.

**Expected behavior**

**Screenshots**

<details> 
<img width="1278" alt="Снимок экрана 2019-04-26 в 9 43 26" src="https://user-images.githubusercontent.com/25154338/56798520-92579900-681f-11e9-964d-6586db87f7ff.png">
<img width="1280" alt="Снимок экрана 2019-04-26 в 9 43 46" src="https://user-images.githubusercontent.com/25154338/56798521-92579900-681f-11e9-8d7c-d5ce69cc326c.png">
<img width="1280" alt="Снимок экрана 2019-04-26 в 9 44 48" src="https://user-images.githubusercontent.com/25154338/56798522-92579900-681f-11e9-8d5e-99eda76c0309.png">
<img width="1280" alt="Снимок экрана 2019-04-26 в 12 32 54" src="https://user-images.githubusercontent.com/25154338/56798523-92579900-681f-11e9-84e5-80e42d3cc792.png">
</details>

**Additional context**

The only one crash report I found in console. It seems to be old but, maybe, it's the same bug.
[Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin_2019-04-14-192938_mac-aleex.crash.log](https://github.com/Microsoft/vscode-cpptools/files/3121808/Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin_2019-04-14-192938_mac-aleex.crash.log)

**Comment by sean-mcmanus** [comment]
That crash is from the IntelliSense process. It could potentially cause IntelliSense features to fail, but if the crash is 12 days old then it would be unrelated, right? Are you continuing to get that crash in your Mac crash logs? That particular crash appears to be one of our highest hitting crash in 0.23.0-insiders and reproed only rarely with 0.22.1.

**Comment by aleexf** [comment]
I don't have crash reports anymore, but I still get described above error. What data can I provide you to fix the bug? (And how to collect it?)

**Comment by sean-mcmanus** [comment]
Do you see any errors when you do "Toggle Developer Tools"? Do Microsoft.VSCode.Cpp. processes exist? Are they using high memory or CPU? If you [enable Debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) do you see any strange output or is it responding with messages?

**Comment by sean-mcmanus** [comment]
We fixed some crashes with 0.23.0-insiders2 https://github.com/Microsoft/vscode-cpptools/releases/tag/0.23.0-insiders2 .

**Comment by aleexf** [comment]
I updated the extension to version 0.23.0-insiders2, but the problem remained. As you said, I collected some logs for you.
<details>
CPU usage:
<img width="865" alt="CPU usage" src="https://user-images.githubusercontent.com/25154338/57131953-b29ad100-6da6-11e9-9528-63ef1cfaa4bb.png">
RAM usage(ГБ = GB in English):
<img width="658" alt="RAM usage" src="https://user-images.githubusercontent.com/25154338/57131954-b3336780-6da6-11e9-8d88-5e0f33acc98b.png">

[devtools.log](https://github.com/Microsoft/vscode-cpptools/files/3141463/devtools.log)

[output.log](https://github.com/Microsoft/vscode-cpptools/files/3141464/output.log)

</details>

**Comment by sean-mcmanus** [comment]
Where are the logs?

**Comment by aleexf** [comment]
Under the spoiler in my previous comment there are two files: logs from "output" tab in editor (called _output.log_) and log from developer tools console(called _devtools.log_).

**Comment by sean-mcmanus** [comment]
From the logs it looks like a deadlock may be occurring (stuck waiting for a response from after sending the edits to the IntelliSense process). If you forcibly kill the Microsoft.VSCode.CPP.IntelliSense.darwin process and then make an edit to the file, does it cause a new process to be spawned that is no longer stuck? If so, that would indicate the IntelliSense process is deadlocked. If you could attach a debugger to that IntelliSense process (while it's stuck) and provide a call stack that could help locate where the deadlock is occurring.

**Comment by aleexf** [comment]
Yes, if I kill the process and edit the file new process spawns and all works good. Here is call stack:
[«Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin».txt](https://github.com/microsoft/vscode-cpptools/files/3192339/Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin.txt)

**Comment by sean-mcmanus** [comment]
@aleexf Those call stacks show no work -- it's just waiting for requests. Is the problem with the Microsoft.VSCode.CPP.Extension.darwin getting stuck?

**Comment by aleexf** [comment]
This error sometimes appears in the "output" section:

[Microsoft.VSCode.CPP.IntelliSense.output.log](https://github.com/microsoft/vscode-cpptools/files/3334745/Microsoft.VSCode.CPP.IntelliSense.output.log)

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
