### ISSUE TITLE
Go to definition and intellisense

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3549]
**Type: LanguageService**

**Describe the bug**
- VS Code Version: 1.31
- C/C++ Extension Version: 0.21
![33333捕获](https://user-images.githubusercontent.com/39362073/56861260-ce326000-69d1-11e9-9332-409375a6d13d.PNG)

Code as above.

- A small bug: symbol behind #ifndef can't go to definition. I think it's the same with symbols behind "goto".

- If DT_VOID isn't defined, symbol P and ulLen can't go to definition and it doesn't show wave line under symbol "DT_VOID".

**Comment by Lennon925** [comment]
I found another 2 scenarios about template and generic but it isn't always reproduced. In simple code, it's ok, but in my business project code, it can't go to definition. Code as below and for reference only.

![111111](https://user-images.githubusercontent.com/39362073/56861652-6d0c8b80-69d5-11e9-9567-d2adf069f957.PNG)
![222222222](https://user-images.githubusercontent.com/39362073/56861655-6e3db880-69d5-11e9-8022-51ded00248f2.PNG)

GTEST_FORMAT_CHAR_PTR_IMPL_ and GTEST_10_TYPENAMES_ can't go to definition.

**Comment by sean-mcmanus** [comment]
It sounds like you're saying Go to Definition isn't finding the definitions in the inactive regions. VS is fallbacking back to using the "Tag Parser" results -- should be easily fixable.

The lack of squiggles in the template is being tracked by https://github.com/Microsoft/vscode-cpptools/issues/1946 , so you could upvote that.

I didn't understand what bug your last 2 screenshots was supposed to illustrate.

**Comment by Lennon925** [comment]
> It sounds like you're saying Go to Definition isn't finding the definitions in the inactive regions. VS is fallbacking back to using the "Tag Parser" results -- should be easily fixable.
> 
> The lack of squiggles in the template is being tracked by #1946 , so you could upvote that.
> 
> I didn't understand what bug your last 2 screenshots was supposed to illustrate.

In my last screenshots, I mean that parts with wave line in picture can't find definition in my own project but if I copy this part code to a simple project, its behavior is OK. It's not stable. 

If I remove template<typename T> and template<GTEST_10_TYPENAMES_(T)> these lines, parts with wave line can find definition. So I guess they are related with template. Maybe they are caused by the same reason.

**Comment by sean-mcmanus** [comment]
What is the squiggle error? That could be breaking it. I tried Go to Def on a macro of a template and it worked for me.

**Comment by sean-mcmanus** [comment]
This Go to Def issue should be fixed with 0.23.0-insiders2: https://github.com/Microsoft/vscode-cpptools/releases/tag/0.23.0-insiders2

We've got some high priority memory leak and performance problems so we haven't had time to investigate the other Go to Def issues you reported yet, so those will probably get delayed to our next release.

**Comment by Lennon925** [comment]
> This Go to Def issue should be fixed with 0.23.0-insiders2: https://github.com/Microsoft/vscode-cpptools/releases/tag/0.23.0-insiders2
> 
> We've got some high priority memory leak and performance problems so we haven't had time to investigate the other Go to Def issues you reported yet, so those will probably get delayed to our next release.

Symbol P and ulLen still can't go to definition in 0.23.0-insiders2.

**Comment by sean-mcmanus** [comment]
That is a different root cause -- it's due to the fact that IntelliSense (and therefore local variables) are not available for templates. We're tracking that with https://github.com/microsoft/vscode-cpptools/issues/1946 .
