### ISSUE TITLE
c++ Debugging with vscode too slow.

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-cpptools#363]
_From @AbelaroJiang on November 23, 2016 2:15_

- VSCode Version:1.7.1
- OS Version:Centos7.2

When I use the vscode to debug c++ program on Centsos7.2. It seem to very slow to jump next break points.

pls help check this and fix it soon. thanks a lot.

_Copied from original issue: Microsoft/vscode#15932_

**Comment by pieandcakes** [comment]
@AbelaroJiang Can you provide a test application and any specifics? I've tried it on CentOS7.2 and I don't see the slowness you are mentioning.

**Comment by aengusjiang** [comment]
Our team working on a c++ project. This application size is a about 6~8Mb. When I first time debug the app, it is very soon. but it seem to slow when I use it for a period of time. About 2~5s to jump the next break point. I really don't know for what reason. But it have no this problem when I use the gdb directly.

that all.

**Comment by peterazmanov** [comment]
I experience painfully slow debugging with vscode too.
I noticed that the deeper my call stack the slower the process is. I have a vague suspicion that vscode updates local variables for each position in call stack or something like that.

**Comment by pieandcakes** [comment]
If you both enable `"logging": { "trace": true, "traceResponse": true }` you can see what is being requested if that will give more info.

**Comment by kiransj** [comment]
When the call is very deep "Step Over" takes more than 10 seconds while the same line when the call stack is not very deep take less than .05s. Then the delay was seen my call stack was 25 function deep.

Issue seen with Ubuntu 14.04 
Vscode version
Version 1.13.0
Commit 376c52b955428d205459bea6619fc161fc8faacf
Date 2017-06-08T16:41:25.571Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

**Comment by dirkseidel** [comment]
Same problem here. Slow stepping with deep call stack.
It would be a great improvement to be able to disable the refreshing of the local variables and have an extra button/short cut to explicitly do that refresh if needed.

**Comment by pieandcakes** [comment]
@dirkseidel  I have made a change that will be in the next update that should improve this. It is a combination of deep callstack and us trying to provide useful information in the callstack frame. The problem is calls to get the type and name of the variables in each frame actually take more time (especially if is a large simple object) because the call to gdb that we were using to get that information also gives us the values. I have made a change to convert it to be more chatty but to be a faster call to get the information as it only gets the name of the variable and the type and not the value. Please let me know once it goes out if it has improved for you.

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4.

**Comment by htyu** [comment]
Hello, has this fix been released? I'm still experiencing slow C++ debugging with gdb.

**Comment by pieandcakes** [comment]
@hoyFB this was released in 0.14.4. It specifically fixes this issue. If you have a problem with slowness, please file a more detailed new issue.

**Comment by htyu** [comment]
@pieandcakes Thanks for the information. I'm attaching a trace log here. The problem was that after hitting a break point, stepping over a statement took a few seconds. The last break point in the log is

Thread 2 "ld.lld" hit Breakpoint 50, llvm::BranchProbabilityInfo::printEdgeProbability (this=0x7ffff544a250, OS=..., Src=0x7ffff000ef30, Dst=0x7ffff000a460) at /home/hoy/local/server-llvm/llvm-project/llvm/lib/Analysis/BranchProbabilityInfo.cpp:966
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"966\t  OS << \"edge \" << Src->getName() << \" -> \" << Dst->getName()\n"},"seq":400}
966	  OS << "edge " << Src->getName() << " -> " << Dst->getName()

and it looks that stepping over from there triggered a stack walk.

Thanks for taking a look!

[vscode.dbg.log](https://github.com/microsoft/vscode-cpptools/files/4177568/vscode.dbg.log)

**Comment by ChrisGy** [comment]
I found a solution that worked for me. In your `.gdbinit` or VScode launch `setupCommands`, set a backtrace limit. For me, 5 was enough:

```bash
set backtrace limit 5
```
