### ISSUE TITLE
cant format code over Remote-SSH

### ISSUE THREAD

**Issue by starsharp06sharp** [microsoft/vscode-cpptools#3801]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 7 Professional 64bit
- Remote OS Version: CentOS 7 x86-64
- VS Code Version: 1.35.1
- C/C++ Extension Version: 0.23.1
- Other extensions you installed (and if the issue persists after disabling them):
Remote Development
Remote - SSH
- A clear and concise description of what the bug is.

**To Reproduce**
1.Connect to remote host by "Remote - SSH" plugin and open a directory
2. Open an CPP file an run "Format document"

**Expected behavior**
The file should have been formated on remote host, but output indicate that our extension has called clang-format on my windows PC:
```
Formatting failed:
C:\Program Files\LLVM\bin\clang-format.exe -style=google -fallback-style=google -sort-includes=0 -assume-filename=/data/home/leolzheng/git_repo/video_pay_added_value/diamond_proj/spp_wenman_ticket/src/common.h
  Can't find or run process_name
```

**Screenshots**
![image](https://user-images.githubusercontent.com/11514437/59822898-c7372680-935e-11e9-8d48-746903039b42.png)

**Additional context**
config on my Windows PC is like:
```
"C_Cpp.clang_format_path": "C:\Program Files\LLVM\bin\clang-format.exe"
```
but there is not such config on my remote server, and local config should not affect extensions on remote server , as I understand.

**Comment by sean-mcmanus** [comment]
I suspect this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/3774 .

**Comment by sean-mcmanus** [comment]
Can you just add `"C_Cpp.clang_format_path": ""` to your Remote settings? That seemed to fix it for me.

UPDATE: Also, fixed with 0.24.0-insiders2, but the vsix needs to be manually installed on the remote side.

**Comment by starsharp06sharp** [comment]
this method works for me as well, thx

**Comment by shelper** [comment]
i think this issue still exists, i am having 0.27.0, 
if i use default for both wsl and local, it is fine
if i put "clang-format" and i  do have clang-format installed on my wsl, this fails and gives the same error message of "cannot find /runprocess_name"

**Comment by sean-mcmanus** [comment]
@shelper What do you mean by "use default" and "put clang-format"? What are you setting exactly?

**Comment by shelper** [comment]
use default means it is empty, it uses the clang-format comes with the cpp tools. 
if changed to "clang-format" and i have "clang-format" installed in WSL  and is in the PATH. then it will fail

**Comment by sean-mcmanus** [comment]
The C_Cpp.clang_format_path descriptions says "The full path of the clang-format executable. If not specified, and clang-format is available in the environment path, that is used. If not found in the environment path, a copy of clang-format bundled with the extension will be used.". So it's "by design" that using "clang-format" won't work (instead of "" or "/usr/bin/clang-format"). Is there a reason you need the relative paths to be supported?

**Comment by shelper** [comment]
sorry, i misunderstood the line
nevermind. and thanks for explanation
