### ISSUE TITLE
Could not load source ... 'SourceRequest' not supported..

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode-cpptools#3831]
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-24-generic

- C/C++ Extension Version: 0.24.0

````json
{
	"version": "0.2.0",
	"configurations": [
		{ 
			"name": "(gdb) Attach",
			"type": "cppdbg",
			"request": "attach",
			"program": "${workspaceRoot}/out/Debug/electron",
			"processId": "${command:pickProcess}",
			"MIMode": "gdb",
			"logging": {
				"trace": true,
				"traceResponse": true,
				"engineLogging": true
			 },

			"setupCommands": [
				{
					"description": "Enable pretty-printing for gdb",
					"text": "-enable-pretty-printing",
					"ignoreFailures": true
				}
			]
		}
    ]
}
````

- attach to gdb process
- click pause
- double click on stack frame

it opens a source window with the following contents:

> Could not load source './../../content/app/content_main.cc': 'SourceRequest' not supported..

that path is relative to the executable, and the file exists and is readable.

````
<--   C (pause-9): {"command":"pause","arguments":{"threadId":10539},"type":"request","seq":9}
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76758) ->~\"\\nProgram\"\n"},"seq":920,"type":"event"}
1: (76758) ->~"\nProgram"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76759) ->~\" received signal SIGINT, Interrupt.\\n\"\n"},"seq":922,"type":"event"}
1: (76759) ->~" received signal SIGINT, Interrupt.\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76759) ->~\"0x00007f1749e7eeb1 in __libc_pause () at ../sysdeps/unix/sysv/linux/pause.c:30\\n\"\n"},"seq":924,"type":"event"}
1: (76759) ->~"0x00007f1749e7eeb1 in __libc_pause () at ../sysdeps/unix/sysv/linux/pause.c:30\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76759) ->~\"30\\tin ../sysdeps/unix/sysv/linux/pause.c\\n\"\n"},"seq":926,"type":"event"}
1: (76759) ->~"30\tin ../sysdeps/unix/sysv/linux/pause.c\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76759) ->*stopped,reason=\"signal-received\",signal-name=\"SIGINT\",signal-meaning=\"Interrupt\",frame={addr=\"0x00007f1749e7eeb1\",func=\"__libc_pause\",args=[],file=\"../sysdeps/unix/sysv/linux/pause.c\",fullname=\"/build/glibc-OTsEL5/glibc-2.27/nptl/../sysdeps/unix/sysv/linux/pause.c\",line=\"30\"},thread-id=\"1\",stopped-threads=\"all\",core=\"1\"\n"},"seq":928,"type":"event"}
1: (76759) ->*stopped,reason="signal-received",signal-name="SIGINT",signal-meaning="Interrupt",frame={addr="0x00007f1749e7eeb1",func="__libc_pause",args=[],file="../sysdeps/unix/sysv/linux/pause.c",fullname="/build/glibc-OTsEL5/glibc-2.27/nptl/../sysdeps/unix/sysv/linux/pause.c",line="30"},thread-id="1",stopped-threads="all",core="1"
--> E (output): {"event":"output","body":{"category":"stdout","output":"\nProgram"},"seq":930,"type":"event"}

Program
--> E (output): {"event":"output","body":{"category":"stdout","output":" received signal SIGINT, Interrupt.\n"},"seq":933,"type":"event"}
 received signal SIGINT, Interrupt.
0x00007f1749e7eeb1 in __libc_pause () at ../sysdeps/unix/sysv/linux/pause.c:30
--> R (pause-9): {"request_seq":9,"success":true,"command":"pause","body":{},"seq":931,"type":"response"}
--> E (output): {"event":"output","body":{"category":"stdout","output":"30\tin ../sysdeps/unix/sysv/linux/pause.c\n"},"seq":937,"type":"event"}
30	in ../sysdeps/unix/sysv/linux/pause.c
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76762) <-1012-stack-list-frames 0 1000\n"},"seq":939,"type":"event"}
1: (76762) <-1012-stack-list-frames 0 1000
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76762) ->&\"warning: (Internal error: pc 0x7f1769c5246a in read in CU, but not in symtab.)\\n\"\n"},"seq":941,"type":"event"}
1: (76762) ->&"warning: (Internal error: pc 0x7f1769c5246a in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76763) ->&\"warning: (Internal error: pc 0x7f1769c5246a in read in CU, but not in symtab.)\\n\"\n"},"seq":943,"type":"event"}
1: (76763) ->&"warning: (Internal error: pc 0x7f1769c5246a in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76763) ->&\"warning: (Internal error: pc 0x7f1769c52300 in read in CU, but not in symtab.)\\n\"\n"},"seq":945,"type":"event"}
1: (76763) ->&"warning: (Internal error: pc 0x7f1769c52300 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76763) ->&\"warning: (Internal error: pc 0x7f1769c5246a in read in CU, but not in symtab.)\\n\"\n"},"seq":947,"type":"event"}
1: (76763) ->&"warning: (Internal error: pc 0x7f1769c5246a in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76763) ->&\"warning: (Internal error: pc 0x7f1769c5246a in read in CU, but not in symtab.)\\n\"\n"},"seq":949,"type":"event"}
1: (76763) ->&"warning: (Internal error: pc 0x7f1769c5246a in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76764) ->&\"warning: (Internal error: pc 0x7f1769c5246a in read in CU, but not in symtab.)\\n\"\n"},"seq":951,"type":"event"}
1: (76764) ->&"warning: (Internal error: pc 0x7f1769c5246a in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76764) ->&\"warning: (Internal error: pc 0x7f1769c5246a in read in CU, but not in symtab.)\\n\"\n"},"seq":953,"type":"event"}
1: (76764) ->&"warning: (Internal error: pc 0x7f1769c5246a in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76764) ->&\"warning: (Internal error: pc 0x7f176ccf18e0 in read in CU, but not in symtab.)\\n\"\n"},"seq":955,"type":"event"}
1: (76764) ->&"warning: (Internal error: pc 0x7f176ccf18e0 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76764) ->&\"warning: (Internal error: pc 0x7f176ccf18e0 in read in CU, but not in symtab.)\\n\"\n"},"seq":957,"type":"event"}
1: (76764) ->&"warning: (Internal error: pc 0x7f176ccf18e0 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76765) ->&\"warning: (Internal error: pc 0x7f176ccf1830 in read in CU, but not in symtab.)\\n\"\n"},"seq":959,"type":"event"}
1: (76765) ->&"warning: (Internal error: pc 0x7f176ccf1830 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76765) ->&\"warning: (Internal error: pc 0x7f176ccf18e0 in read in CU, but not in symtab.)\\n\"\n"},"seq":961,"type":"event"}
1: (76765) ->&"warning: (Internal error: pc 0x7f176ccf18e0 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76765) ->&\"warning: (Internal error: pc 0x7f176ccf18e0 in read in CU, but not in symtab.)\\n\"\n"},"seq":963,"type":"event"}
1: (76765) ->&"warning: (Internal error: pc 0x7f176ccf18e0 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76765) ->&\"warning: (Internal error: pc 0x7f176ccf18e0 in read in CU, but not in symtab.)\\n\"\n"},"seq":965,"type":"event"}
1: (76765) ->&"warning: (Internal error: pc 0x7f176ccf18e0 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76765) ->&\"warning: (Internal error: pc 0x7f176ccf18e0 in read in CU, but not in symtab.)\\n\"\n"},"seq":967,"type":"event"}
1: (76765) ->&"warning: (Internal error: pc 0x7f176ccf18e0 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76765) ->&\"warning: (Internal error: pc 0x7f176ccf272f in read in CU, but not in symtab.)\\n\"\n"},"seq":969,"type":"event"}
1: (76765) ->&"warning: (Internal error: pc 0x7f176ccf272f in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76766) ->&\"warning: (Internal error: pc 0x7f176ccf272f in read in CU, but not in symtab.)\\n\"\n"},"seq":971,"type":"event"}
1: (76766) ->&"warning: (Internal error: pc 0x7f176ccf272f in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76766) ->&\"warning: (Internal error: pc 0x7f176ccf24b0 in read in CU, but not in symtab.)\\n\"\n"},"seq":973,"type":"event"}
1: (76766) ->&"warning: (Internal error: pc 0x7f176ccf24b0 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76766) ->&\"warning: (Internal error: pc 0x7f176ccf272f in read in CU, but not in symtab.)\\n\"\n"},"seq":975,"type":"event"}
1: (76766) ->&"warning: (Internal error: pc 0x7f176ccf272f in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76766) ->&\"warning: (Internal error: pc 0x7f176ccf272f in read in CU, but not in symtab.)\\n\"\n"},"seq":977,"type":"event"}
1: (76766) ->&"warning: (Internal error: pc 0x7f176ccf272f in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76766) ->&\"warning: (Internal error: pc 0x7f176ccf272f in read in CU, but not in symtab.)\\n\"\n"},"seq":979,"type":"event"}
1: (76766) ->&"warning: (Internal error: pc 0x7f176ccf272f in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76767) ->&\"warning: (Internal error: pc 0x7f176ccf272f in read in CU, but not in symtab.)\\n\"\n"},"seq":981,"type":"event"}
1: (76767) ->&"warning: (Internal error: pc 0x7f176ccf272f in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76767) ->&\"warning: (Internal error: pc 0x7f176ccef407 in read in CU, but not in symtab.)\\n\"\n"},"seq":983,"type":"event"}
1: (76767) ->&"warning: (Internal error: pc 0x7f176ccef407 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76767) ->&\"warning: (Internal error: pc 0x7f176ccef407 in read in CU, but not in symtab.)\\n\"\n"},"seq":985,"type":"event"}
1: (76767) ->&"warning: (Internal error: pc 0x7f176ccef407 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76767) ->&\"warning: (Internal error: pc 0x7f176ccef3c0 in read in CU, but not in symtab.)\\n\"\n"},"seq":987,"type":"event"}
1: (76767) ->&"warning: (Internal error: pc 0x7f176ccef3c0 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76767) ->&\"warning: (Internal error: pc 0x7f176ccef407 in read in CU, but not in symtab.)\\n\"\n"},"seq":989,"type":"event"}
1: (76767) ->&"warning: (Internal error: pc 0x7f176ccef407 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76768) ->&\"warning: (Internal error: pc 0x7f176ccef407 in read in CU, but not in symtab.)\\n\"\n"},"seq":991,"type":"event"}
1: (76768) ->&"warning: (Internal error: pc 0x7f176ccef407 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76768) ->&\"warning: (Internal error: pc 0x7f176ccef407 in read in CU, but not in symtab.)\\n\"\n"},"seq":993,"type":"event"}
1: (76768) ->&"warning: (Internal error: pc 0x7f176ccef407 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76768) ->&\"warning: (Internal error: pc 0x7f176ccef407 in read in CU, but not in symtab.)\\n\"\n"},"seq":995,"type":"event"}
1: (76768) ->&"warning: (Internal error: pc 0x7f176ccef407 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76768) ->1012^done,stack=[frame={level=\"0\",addr=\"0x00007f1749e7eeb1\",func=\"__libc_pause\",file=\"../sysdeps/unix/sysv/linux/pause.c\",fullname=\"/build/glibc-OTsEL5/glibc-2.27/nptl/../sysdeps/unix/sysv/linux/pause.c\",line=\"30\"},frame={level=\"1\",addr=\"0x00007f1769c5246b\",func=\"content::WaitForDebugger(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > const&)\",file=\"../../content/common/content_switches_internal.cc\",fullname=\"./../../content/common/content_switches_internal.cc\",line=\"119\"},frame={level=\"2\",addr=\"0x00007f176c7d79ce\",func=\"content::(anonymous namespace)::HandleRendererErrorTestParameters(base::CommandLine const&)\",file=\"./../../content/renderer/renderer_main.cc\",fullname=\"././../../content/renderer/renderer_main.cc\",line=\"76\"},frame={level=\"3\",addr=\"0x00007f176c7d7386\",func=\"content::RendererMain(content::MainFunctionParams const&)\",file=\"./../../content/renderer/renderer_main.cc\",fullname=\"././../../content/renderer/renderer_main.cc\",line=\"126\"},frame={level=\"4\",addr=\"0x00007f176ccf18e1\",func=\"content::RunOtherNamedProcessTypeMain(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > const&, content::MainFunctionParams const&, content::ContentMainDelegate*)\",file=\"../../content/app/content_main_runner_impl.cc\",fullname=\"./../../content/app/content_main_runner_impl.cc\",line=\"576\"},frame={level=\"5\",addr=\"0x00007f176ccf2730\",func=\"content::ContentMainRunnerImpl::Run(bool)\",file=\"../../content/app/content_main_runner_impl.cc\",fullname=\"./../../content/app/content_main_runner_impl.cc\",line=\"873\"},frame={level=\"6\",addr=\"0x00007f176ccef408\",func=\"content::ContentServiceManagerMainDelegate::RunEmbedderProcess()\",file=\"../../content/app/content_service_manager_main_delegate.cc\",fullname=\"./../../content/app/content_service_manager_main_delegate.cc\",line=\"52\"},frame={level=\"7\",addr=\"0x00007f1741b5374e\",func=\"service_manager::Main(service_manager::MainParams const&)\",file=\"../../services/service_manager/embedder/main.cc\",fullname=\"./../../services/service_manager/embedder/main.cc\",line=\"422\"},frame={level=\"8\",addr=\"0x00007f176ccf1333\",func=\"content::ContentMain(content::ContentMainParams const&)\",file=\"../../content/app/content_main.cc\",fullname=\"./../../content/app/content_main.cc\",line=\"19\"},frame={level=\"9\",addr=\"0x0000560cf4bd51e6\",func=\"main\",file=\"../../electron/shell/app/atom_main.cc\",fullname=\"./../../electron/shell/app/atom_main.cc\",line=\"206\"}]\n"},"seq":997,"type":"event"}
1: (76768) ->1012^done,stack=[frame={level="0",addr="0x00007f1749e7eeb1",func="__libc_pause",file="../sysdeps/unix/sysv/linux/pause.c",fullname="/build/glibc-OTsEL5/glibc-2.27/nptl/../sysdeps/unix/sysv/linux/pause.c",line="30"},frame={level="1",addr="0x00007f1769c5246b",func="content::WaitForDebugger(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > const&)",file="../../content/common/content_switches_internal.cc",fullname="./../../content/common/content_switches_internal.cc",line="119"},frame={level="2",addr="0x00007f176c7d79ce",func="content::(anonymous namespace)::HandleRendererErrorTestParameters(base::CommandLine const&)",file="./../../content/renderer/renderer_main.cc",fullname="././../../content/renderer/renderer_main.cc",line="76"},frame={level="3",addr="0x00007f176c7d7386",func="content::RendererMain(content::MainFunctionParams const&)",file="./../../content/renderer/renderer_main.cc",fullname="././../../content/renderer/renderer_main.cc",line="126"},frame={level="4",addr="0x00007f176ccf18e1",func="content::RunOtherNamedProcessTypeMain(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > const&, content::MainFunctionParams const&, content::ContentMainDelegate*)",file="../../content/app/content_main_runner_impl.cc",fullname="./../../content/app/content_main_runner_impl.cc",line="576"},frame={level="5",addr="0x00007f176ccf2730",func="content::ContentMainRunnerImpl::Run(bool)",file="../../content/app/content_main_runner_impl.cc",fullname="./../../content/app/content_main_runner_impl.cc",line="873"},frame={level="6",addr="0x00007f176ccef408",func="content::ContentServiceManagerMainDelegate::RunEmbedderProcess()",file="../../content/app/content_service_manager_main_delegate.cc",fullname="./../../content/app/content_service_manager_main_delegate.cc",line="52"},frame={level="7",addr="0x00007f1741b5374e",func="service_manager::Main(service_manager::MainParams const&)",file="../../services/service_manager/embedder/main.cc",fullname="./../../services/service_manager/embedder/main.cc",line="422"},frame={level="8",addr="0x00007f176ccf1333",func="content::ContentMain(content::ContentMainParams const&)",file="../../content/app/content_main.cc",fullname="./../../content/app/content_main.cc",line="19"},frame={level="9",addr="0x0000560cf4bd51e6",func="main",file="../../electron/shell/app/atom_main.cc",fullname="./../../electron/shell/app/atom_main.cc",line="206"}]
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76769) ->(gdb)\n"},"seq":999,"type":"event"}
1: (76769) ->(gdb)
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76769) 1012: elapsed time 7\n"},"seq":1001,"type":"event"}
1: (76769) 1012: elapsed time 7
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76770) Send Event AD7AsyncBreakCompleteEvent\n"},"seq":1003,"type":"event"}
1: (76770) Send Event AD7AsyncBreakCompleteEvent
--> E (output): {"event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/Pause","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.60611.1","VS.Diagnostics.Debugger.HostVersion":"14.0.60611.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg"}},"seq":1005,"type":"event"}
--> E (output): {"event":"output","body":{"category":"console","output":"Execute debugger commands using \"-exec <command>\", for example \"-exec info registers\" will list registers in use (when GDB is the debugger)\n"},"seq":1007,"type":"event"}
Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76773) Send Event AD7StopCompleteEvent\n"},"seq":1009,"type":"event"}
1: (76773) Send Event AD7StopCompleteEvent
--> E (stopped): {"event":"stopped","body":{"reason":"pause","threadId":10539,"allThreadsStopped":true,"source":{"name":"pause.c","path":"/build/glibc-OTsEL5/glibc-2.27/sysdeps/unix/sysv/linux/pause.c","sources":[],"checksums":[]},"line":30,"column":1},"seq":1011,"type":"event"}
<--   C (threads-10): {"command":"threads","type":"request","seq":10}
--> R (threads-10): {"request_seq":10,"success":true,"command":"threads","body":{"threads":[{"id":10539,"name":"electron"}]},"seq":1014,"type":"response"}
<--   C (stackTrace-11): {"command":"stackTrace","arguments":{"threadId":10539,"startFrame":0,"levels":20},"type":"request","seq":11}
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76798) <-1013-stack-list-arguments 0 0 9\n"},"seq":1017,"type":"event"}
1: (76798) <-1013-stack-list-arguments 0 0 9
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76799) ->&\"warning: (Internal error: pc 0x7f1769c5246a in read in CU, but not in symtab.)\\n\"\n"},"seq":1019,"type":"event"}
1: (76799) ->&"warning: (Internal error: pc 0x7f1769c5246a in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76799) ->&\"warning: (Internal error: pc 0x7f176ccf18e0 in read in CU, but not in symtab.)\\n\"\n"},"seq":1021,"type":"event"}
1: (76799) ->&"warning: (Internal error: pc 0x7f176ccf18e0 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76799) ->&\"warning: (Internal error: pc 0x7f176ccf272f in read in CU, but not in symtab.)\\n\"\n"},"seq":1023,"type":"event"}
1: (76799) ->&"warning: (Internal error: pc 0x7f176ccf272f in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76799) ->&\"warning: (Internal error: pc 0x7f176ccef407 in read in CU, but not in symtab.)\\n\"\n"},"seq":1025,"type":"event"}
1: (76799) ->&"warning: (Internal error: pc 0x7f176ccef407 in read in CU, but not in symtab.)\n"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76800) ->1013^done,stack-args=[frame={level=\"0\",args=[]},frame={level=\"1\",args=[]},frame={level=\"2\",args=[]},frame={level=\"3\",args=[]},frame={level=\"4\",args=[]},frame={level=\"5\",args=[]},frame={level=\"6\",args=[]},frame={level=\"7\",args=[]},frame={level=\"8\",args=[]},frame={level=\"9\",args=[]}]\n"},"seq":1027,"type":"event"}
1: (76800) ->1013^done,stack-args=[frame={level="0",args=[]},frame={level="1",args=[]},frame={level="2",args=[]},frame={level="3",args=[]},frame={level="4",args=[]},frame={level="5",args=[]},frame={level="6",args=[]},frame={level="7",args=[]},frame={level="8",args=[]},frame={level="9",args=[]}]
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76800) ->(gdb)\n"},"seq":1029,"type":"event"}
1: (76800) ->(gdb)
--> E (output): {"event":"output","body":{"category":"console","output":"1: (76800) 1013: elapsed time 1\n"},"seq":1031,"type":"event"}
1: (76800) 1013: elapsed time 1
--> R (stackTrace-11): {"request_seq":11,"success":true,"command":"stackTrace","body":{"stackFrames":[{"id":1000,"name":"__libc_pause()","source":{"name":"pause.c","path":"/build/glibc-OTsEL5/glibc-2.27/sysdeps/unix/sysv/linux/pause.c","sources":[],"checksums":[]},"line":30,"column":1},{"id":1001,"name":"content::WaitForDebugger(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > const&)()","source":{"name":"content_switches_internal.cc","path":"./../../content/common/content_switches_internal.cc","sources":[],"checksums":[]},"line":119,"column":1},{"id":1002,"name":"content::(anonymous namespace)::HandleRendererErrorTestParameters(base::CommandLine const&)()","source":{"name":"renderer_main.cc","path":"././../../content/renderer/renderer_main.cc","sources":[],"checksums":[]},"line":76,"column":1},{"id":1003,"name":"content::RendererMain(content::MainFunctionParams const&)()","source":{"name":"renderer_main.cc","path":"././../../content/renderer/renderer_main.cc","sources":[],"checksums":[]},"line":126,"column":1},{"id":1004,"name":"content::RunOtherNamedProcessTypeMain(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > const&, content::MainFunctionParams const&, content::ContentMainDelegate*)()","source":{"name":"content_main_runner_impl.cc","path":"./../../content/app/content_main_runner_impl.cc","sources":[],"checksums":[]},"line":576,"column":1},{"id":1005,"name":"content::ContentMainRunnerImpl::Run(bool)()","source":{"name":"content_main_runner_impl.cc","path":"./../../content/app/content_main_runner_impl.cc","sources":[],"checksums":[]},"line":873,"column":1},{"id":1006,"name":"content::ContentServiceManagerMainDelegate::RunEmbedderProcess()()","source":{"name":"content_service_manager_main_delegate.cc","path":"./../../content/app/content_service_manager_main_delegate.cc","sources":[],"checksums":[]},"line":52,"column":1},{"id":1007,"name":"service_manager::Main(service_manager::MainParams const&)()","source":{"name":"main.cc","path":"./../../services/service_manager/embedder/main.cc","sources":[],"checksums":[]},"line":422,"column":1},{"id":1008,"name":"content::ContentMain(content::ContentMainParams const&)()","source":{"name":"content_main.cc","path":"./../../content/app/content_main.cc","sources":[],"checksums":[]},"line":19,"column":1},{"id":1009,"name":"main()","source":{"name":"atom_main.cc","path":"./../../electron/shell/app/atom_main.cc","sources":[],"checksums":[]},"line":206,"column":1}],"totalFrames":10},"seq":1033,"type":"response"}
<--   C (scopes-12): {"command":"scopes","arguments":{"frameId":1000},"type":"request","seq":12}
--> E (output): {"event":"output","body":{"category":"console","output":"1: (77223) <-1014-stack-list-variables 0\n"},"seq":1036,"type":"event"}
1: (77223) <-1014-stack-list-variables 0
--> E (output): {"event":"output","body":{"category":"console","output":"1: (77224) ->1014^done,variables=[{name=\"resultvar\"}]\n"},"seq":1038,"type":"event"}
1: (77224) ->1014^done,variables=[{name="resultvar"}]
--> E (output): {"event":"output","body":{"category":"console","output":"1: (77224) ->(gdb)\n"},"seq":1040,"type":"event"}
1: (77224) ->(gdb)
--> E (output): {"event":"output","body":{"category":"console","output":"1: (77224) 1014: elapsed time 1\n"},"seq":1042,"type":"event"}
1: (77224) 1014: elapsed time 1
--> E (output): {"event":"output","body":{"category":"console","output":"1: (77230) <-1015-var-create - * \"resultvar\"\n"},"seq":1044,"type":"event"}
1: (77230) <-1015-var-create - * "resultvar"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (77231) ->1015^done,name=\"var1\",numchild=\"0\",value=\"18446744073709551102\",type=\"unsigned long\",thread-id=\"1\",has_more=\"0\"\n"},"seq":1046,"type":"event"}
1: (77231) ->1015^done,name="var1",numchild="0",value="18446744073709551102",type="unsigned long",thread-id="1",has_more="0"
--> E (output): {"event":"output","body":{"category":"console","output":"1: (77231) ->(gdb)\n"},"seq":1048,"type":"event"}
1: (77231) ->(gdb)
--> E (output): {"event":"output","body":{"category":"console","output":"1: (77232) 1015: elapsed time 1\n"},"seq":1050,"type":"event"}
1: (77232) 1015: elapsed time 1
--> R (scopes-12): {"request_seq":12,"success":true,"command":"scopes","body":{"scopes":[{"name":"Locals","variablesReference":1000,"expensive":false}]},"seq":1052,"type":"response"}
<--   C (variables-13): {"command":"variables","arguments":{"variablesReference":1000},"type":"request","seq":13}
--> R (variables-13): {"request_seq":13,"success":true,"command":"variables","body":{"variables":[{"name":"resultvar","value":"18446744073709551102","type":"unsigned long","evaluateName":"resultvar","variablesReference":0}]},"seq":1055,"type":"response"}
<--   C (source-14): {"command":"source","arguments":{"sourceReference":0,"source":{"name":"content_main.cc","path":"./../../content/app/content_main.cc","sources":[],"checksums":[]}},"type":"request","seq":14}
--> R (source-14): {"request_seq":14,"success":false,"command":"source","message":"'SourceRequest' not supported.","body":{},"seq":1058,"type":"response"}
<--   C (scopes-15): {"command":"scopes","arguments":{"frameId":1008},"type":"request","seq":15}
--> E (output): {"event":"output","body":{"category":"console","output":"1: (80926) <-1016-stack-select-frame 8\n"},"seq":1061,"type":"event"}
1: (80926) <-1016-stack-select-frame 8
--> E (output): {"event":"output","body":{"category":"console","output":"1: (80927) ->1016^done\n"},"seq":1063,"type":"event"}
1: (80927) ->1016^done
--> E (output): {"event":"output","body":{"category":"console","output":"1: (80927) ->(gdb)\n"},"seq":1065,"type":"event"}
1: (80927) ->(gdb)
--> E (output): {"event":"output","body":{"category":"console","output":"1: (80928) 1016: elapsed time 1\n"},"seq":1067,"type":"event"}
1: (80928) 1016: elapsed time 1
--> E (output): {"event":"output","body":{"category":"console","output":"1: (80928) <-1017-stack-list-variables 0\n"},"seq":1069,"type":"event"}
1: (80928) <-1017-stack-list-variables 0
--> E (output): {"event":"output","body":{"category":"console","output":"1: (80929) ->1017^done,variables=[]\n"},"seq":1071,"type":"event"}
1: (80929) ->1017^done,variables=[]
--> E (output): {"event":"output","body":{"category":"console","output":"1: (80929) ->(gdb)\n"},"seq":1073,"type":"event"}
1: (80929) ->(gdb)
--> E (output): {"event":"output","body":{"category":"console","output":"1: (80929) 1017: elapsed time 0\n"},"seq":1075,"type":"event"}
1: (80929) 1017: elapsed time 0
--> R (scopes-15): {"request_seq":15,"success":true,"command":"scopes","body":{"scopes":[]},"seq":1077,"type":"response"}
````

**Comment by pieandcakes** [comment]
Duplicate of #3662

**Comment by Spongman** [comment]
i don't think this is a dupe. if it is, it's not fixed. i'm running  0.24.0-insiders3 on 1.35.1, and i get the same error.

**Comment by Spongman** [comment]
ok, it seems like the source paths are resolved relative to the process' current working directory, which doesn't seem right. shouldn't they be resolved relative to either the debuggee's path itself, or some other directory?

**Comment by Spongman** [comment]
and what's worse, is that you can't set `cwd` for `attach` configurations, and if the child process changes its working directory to something else, it breaks source lookup in the debugger. and setting `.` in the sourceFileMap doesn't help.

**Comment by pieandcakes** [comment]
@Spongman Since I don't have a good repro, can you confirm that you are still seeing a NotImplementedException with `0.24.0-insiders3` or some other error?

For the source paths, we resolve them as your symbol file has them. if you want, you can specify `sourceFileMap` to redirect where the source files should be. You need a path as we don't support just the `.` character.

**Comment by Spongman** [comment]
so, what should i set my `sourceFileMap` to, in order to handle paths like this: `./../../content/app/content_main.cc` ?

nothing i have tried works.

again. this is an `attach` configuration, and the debuggee changes the cwd.

i don't understand why i can't just map './../..' to some directory in my project, and have all paths with that prefix mapped to that location. the '.' in those paths is some build directory in the project, it's not the cwd of the debuggee, and it's not the location of debuggee's executable. and i can't change the build process.

**Comment by pieandcakes** [comment]
Looking at the implementation it might work on `.` if you include a slash (`/` or `\`).

Here is the implementation we use: https://github.com/microsoft/MIEngine/blob/29c6569861b2042c43f04d8d78b2566db2e2ef1f/src/OpenDebugAD7/PathMapper.cs#L19

**Comment by ajihyf** [comment]
Same issue when debug in remote mode(using Remote SSH plugin)

**Comment by pieandcakes** [comment]
@ajihyf Can you let me know which version of the extension you are using?

**Comment by pieandcakes** [comment]
I misunderstood. The original issue of it crashing was fixed by us returning a failure but it looks like VS Code doesn't like that either.

**Comment by BertaBescos** [comment]
I am getting the same issue here. Did you get to solve this?

**Comment by pieandcakes** [comment]
@BertaBescos Is the failure blocking debugging? Do you have a repro that you can share?

**Comment by josepharhar** [comment]
I'm using this feature to debug chromium on linux and It looks like I'm running into the same issue:
```
Could not load source './../../third_party/blink/renderer/core/dom/element.cc': 'SourceRequest' not supported..
```
Here is my launch.json:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "crdbg",
      "type": "cppdbg",
      "request": "attach",
      "program": "${workspaceRoot}/out/Debug/chrome",
      "processId": "${command:pickProcess}",
      "MIMode": "gdb",
      "miDebuggerPath": "/usr/bin/gdb"
    }
  ]
}
```

**Comment by pieandcakes** [comment]
@josepharhar we don't support sourceRequest currently so we return a failure to VS Code which I had assumed would allow debugging to continue. Can you let me know if this ends up terminating the debug session? I can try and change the code there but i haven't been able to get a repro where i can set it up and debug the scenario.

**Comment by josepharhar** [comment]
It does not terminate debugging, I can unpause execution and hit the same breakpoint i set over and over again. Setting up chromium to repro would take a long time if you haven't done it before unfortunately, and I'm not sure what's wrong to provide a good repro. All I know is that with regular gdb it works fine.

Not sure if this helps, but I also get this message in the debug console when I first attach:
```
Superuser access is required to attach to a process. Attaching as superuser can potentially harm your computer. Do you want to continue? [y/N]
```

Just wondering, what is sourceRequest?

**Comment by pieandcakes** [comment]
@josepharhar It is something that VS Code is requesting from us through the [`debugAdapterProtocol`](https://github.com/microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L973). The error, if it isn't stopping debugging, should be ignorable.

**Comment by pemgithub** [comment]
I get the error when trying to step into Google ANGLE source code (on Ubuntu in Visual Studio Code).  It prevents debugging.  I am not able to step into code.  When I step lines of code, it just prints the error:
> Could not load source './../../samples/sample_util/SampleApplication.cpp': 'SourceRequest' not supported..

Here is my launch.json:
```
"version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/out/Debug/hello_triangle",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "justMyCode": true,
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true,
                }
            ]
        }
    ]
```
![image](https://user-images.githubusercontent.com/13956322/67886525-d006e880-fb06-11e9-8af2-8ead3c58132d.png)

**Comment by pieandcakes** [comment]
@pemgithub Does that source code exist on your machine in the location specified based on your `cwd`? If not, you can set up a `sourceFileMap` to point to the correct location.

**Comment by pemgithub** [comment]
@pieandcakes thank you for the help; I was able to get it working by changing this:
`"cwd": "${workspaceFolder}/out/Debug",`

**Comment by pemgithub** [comment]
@pieandcakes using cwd fixed it for code that's relative to my cwd.  However, for a different project, I also wanted to step into external code (from libGLESv2.so which I built from source)...  For external code, I got a similar error - "./../../src/libGLESv2/libGLESv2_autogen.cpp".  So I added the following to my launch.json (which seems to have worked):
`"sourceFileMap": {
"./../../src/": "~/pemCode/angle/src/"
}`

**Comment by jksystemarchitect** [comment]
I faced the same issue with VS code in Ubuntu was resolved by 
compile as g++ -g file.cpp -o file.o 
where -g will add debug info to the output file 
and add the file.o to the launch.json

**Comment by HiddenStar1** [comment]
> I faced the same issue with VS code in Ubuntu was resolved by compile as g++ -g file.cpp -o file.o where -g will add debug info to the output file and add the file.o to the launch.json

![image](https://github.com/microsoft/vscode-cpptools/assets/98447791/c2362f51-a8d3-4a30-9af9-c2fcd2a6b54d)
Is it set up like this?Still not resolved.

**Comment by RushilJalal** [comment]
I still have the issue...
