### ISSUE TITLE
The "OUTLINE" will not given symbols when open a file.

### ISSUE THREAD

**Issue by JasonLeeCn** [microsoft/vscode-cpptools#3877]
Issue Type: <b>Bug</b>

The "OUTLINE" will given a tip "No symbols found in document xxx" when open file. It will stay this state untill the file context was be modify. When modify file, it can se the symbols in "OUTLINE". If close file and then re-open the file, it will also given no symbols with a tip "No symbols found...".

Extension version: 0.24.0
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.66GB (3.12GB free)|
|Process Argv|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
@Colengms I think one of your changes submitted on Friday fixed this -- do you know which? What's the best way to get this into a 0.24.1?

UPDATE: Upvote this if you want us to release a 0.24.1 with a fix.

**Comment by LongChampion** [comment]
Hello everybody, I am having an "opposite" broblem. When i create new .cpp or .h file, the outline panel display many line with content "{}__7". Is this another bug?
![image](https://user-images.githubusercontent.com/47727306/60762195-d3242780-a084-11e9-96a0-794536fc4758.png)
My system infomation:

- OS: Ubuntu 18.04.2 LTS (Linux kernel 4.18.0-25-generic)
- VS Code version 1.36
- Extension: ms-vscode.cpptools 1.24

**Comment by Lennon925** [comment]
> @Colengms I think one of your changes submitted on Friday fixed this -- do you know which? What's the best way to get this into a 0.24.1?
> 
> UPDATE: Upvote this if you want us to release a 0.24.1 with a fix.

Hi Sean, when will you release 0.24.1 to fix this bug?

**Comment by sean-mcmanus** [comment]
Originally, we were going to release a 0.24.1 bug fix release this week, but it seems like not enough users are complaining, so the current plan is to wait till 0.25.0-insiders in a couple weeks.

**Comment by kdpainter** [comment]
> Originally, we were going to release a 0.24.1 bug fix release this week, but it seems like not enough users are complaining, so the current plan is to wait till 0.25.0-insiders in a couple weeks.

I think that users haven't found this thread.  I was googling for weeks to find a solution to this problem when I finally stumbled onto this thread.  I am going to use a different editor until this gets fixed.

**Comment by sean-mcmanus** [comment]
@kdpainter You could also use the "Install Another Version..." feature to revert to 0.23.1. We pinned the issue to the top of the GitHub Issues page to try to make it more visible.

**Comment by kdpainter** [comment]
> @kdpainter You could also use the "Install Another Version..." feature to revert to 0.23.1. We pinned the issue to the top of the GitHub Issues page to try to make it more visible.

Thanks!  I wasn't aware of this feature.  That works for me!   The one thing I found is that you have to set "extensions.autoUpdate": false, 
or it will just update to 0.24.0 again.

**Comment by Lennon925** [comment]
> Originally, we were going to release a 0.24.1 bug fix release this week, but it seems like not enough users are complaining, so the current plan is to wait till 0.25.0-insiders in a couple weeks.

I don't think it's wise to release this fix in 0.25.insider because maybe new feature will bring new bugs. Users can't get a stable version to use for long time until new bugs are fixed. 
In addition, I think most of users haven't found this bug, maybe they haven't updated to version 0.24. And even though they found this, some of them won't create a issue here. 
We hope we can get a stable version to use and a stable 0.24.1 version is necessary because we can't get a stable version for long time if there are new bugs in version 0.25.insider.

**Comment by Lennon925** [comment]
> @kdpainter You could also use the "Install Another Version..." feature to revert to 0.23.1. We pinned the issue to the top of the GitHub Issues page to try to make it more visible.

I think it's so cool to add function "Semantic Colorization" in version 0.24. It's a big step forward. Why to revert to use version 0.23.1 because of this small bug which is not hard to realease.

**Comment by suifeng115** [comment]
I hope this bug can be fixed as soon as possible.  It's really a big trouble for our team, both all of us have updated.

**Comment by kdpainter** [comment]
> @kdpainter You could also use the "Install Another Version..." feature to revert to 0.23.1. We pinned the issue to the top of the GitHub Issues page to try to make it more visible.

Unfortunately, this "Install Another Version" feature doesn't work.  I have autoupdate extensions disabled but it updates to 0.24.0 anyway so I am going to have to use another editor after all.

**Comment by sean-mcmanus** [comment]
@kdpainter The C_Cpp.updateChannel needs to be changed to "Default" instead of "Insiders" -- we have another issue tracking fixing that.

**Comment by kdpainter** [comment]
@sean-mcmanus Thank you!  That was driving me nuts.  It kept updating and I couldn't figure out why.

**Comment by sean-mcmanus** [comment]
Okay, we plan to release a 0.24.1 with this fix on Monday/Tuesday. See https://github.com/microsoft/vscode-cpptools/pull/3943 .

**Comment by Lennon925** [comment]
> Okay, we plan to release a 0.24.1 with this fix on Monday/Tuesday. See #3943 .

It's great! Thank you very much.

**Comment by Colengms** [comment]
This appears to be fixed by: https://github.com/microsoft/vscode-cpptools/pull/3844

**Comment by johnwbyrd** [comment]
+1.  Hitting this outline issue on 0.24, reverting to 0.23 makes the problem go away.

**Comment by sean-mcmanus** [comment]
This should be fixed now with 0.24.1.

**Comment by VamosCC** [comment]
this bug is still appeared in 0.29.0, vscode version 1.45.1, ubuntu 18.04.

**Comment by sean-mcmanus** [comment]
@VamosCC Your scenario is probably different with the same symptom. Can you open a new issue with more repro details? You may want to close all VS Code instances and then make sure all the cpptools process are killed -- otherwise, those processes can lock the database and prevent the Outline from populating.
