### ISSUE TITLE
Error: Failed to parse ".vscode\c_cpp_properties.json

### ISSUE THREAD

**Issue by sye989** [microsoft/vscode-cpptools#4060]
Failed to parse "\.vscode\c_cpp_properties.json": ENOENT: no such file or directory, open '\.vscode\c_cpp_properties.json'
 code in vs code:
#include <stdio.h>

int main()
{
    printf("Hi, my name is ny");
    return 0;
}

**Comment by sean-mcmanus** [comment]
It should be fixed with the latest Insiders (0.25.0-insiders, https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders ). See https://github.com/microsoft/vscode-cpptools/issues/3888 .

**Comment by shameerariff** [comment]
Hi Sean-mcmanus,
Te issue still persists. I have the visual code version 1.48 with C/C++ (ms-vscode.cpptools) version 0.30.0 insiders2. I do got the same error as follows 
Failed to parse "/.vscode/c_cpp_properties.json": ENOENT: no such file or directory, open '/.vscode/c_cpp_properties.json'
The working environment was Ubuntu 20.04 LTS.

**Comment by Colengms** [comment]
Hi @shameerariff .  We are not currently tracking any known issues that result in this error, so there would seem to be something specified about your environment or scenario.  Could you open a new issue with repro details?

**Comment by shameerariff** [comment]
Hi @Colengms ,
I have created a new issue, The [URL](https://github.com/microsoft/vscode-cpptools/issues/5966)
