### ISSUE TITLE
Version 0.26.0-insiders breaks language server

### ISSUE THREAD

**Issue by Finkman** [microsoft/vscode-cpptools#4375]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.38.1
- C/C++ Extension Version: 0.26.0
- Other extensions you installed (and if the issue persists after disabling them): C/C++ Clang Command Adapter, C++ Intellisense, CMake, Cmake Tools.
Issue persists even after disabling the extensions.
- A clear and concise description of what the bug is.

After updating to 0.26.0 a message pops-up that the language-server crashed more than 5 times the last 3 minutes and will not restarted anymore.

**To Reproduce**
It should be reproducible by simply installing 0.26.0

**Expected behavior**
I would simply expect it to not crash the language server

**Screenshots**

**Additional context**
[Error - 09:35:47] Connection to server got closed. Server will not be restarted.

**Comment by yuranu** [comment]
Confirm same issue here, on Fedora 30 after updating to 0.26.0.
For now switched back to 0.25.1 as a workaround.

**Comment by karan-k-deepr** [comment]
I am also getting the same error today now switched back to the previous version `0.25.1` and disable auto-update extensions because of this.

**Comment by MatejMarecek** [comment]
I have the same problem (Windows 10)

**Comment by ArekSredzki** [comment]
Same for Ubuntu 16.04

**Comment by bobbrow** [comment]
We are seeing crashes with the document outline in our telemetry that we didn't see in our testing.  We have removed the release for now while we investigate the issue.  We're sorry about the disruption this has caused!

You can revert back to 0.25.1 by changing the `"C_Cpp.updateChannel"` setting to `"Default"`.  You shouldn't need to disable auto-update of all extensions for this.

**Comment by bobbrow** [comment]
We found a repro and are preparing a fix.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.0-insiders2 .

**Comment by Novakov** [comment]
I think I'm seeing this issue in 0.26.0-insiders2 release. `Microsoft.VSCode.CPP.IntelliSense.Msvc.exe` process is crashing frequently (in Process Explorer I can see that there are few instances started and dying one by one, sometimes one or two survives a bit longer).

`Procdump` reports following exception: `Exception: E06D7363.?AUa_cfe_exception@@`.

Should I report this as new issue?

**Comment by ArekSredzki** [comment]
@sean-mcmanus I too am still seeing this issue in `0.26.0-insiders2` on Ubuntu 16.04. Additionally, my computer seems to freeze momentarily when VS Code is open with this configuration.

**Comment by ArekSredzki** [comment]
It turns out to be memory related (https://github.com/microsoft/vscode-cpptools/issues/4386)

**Comment by ArekSredzki** [comment]
![image](https://user-images.githubusercontent.com/879918/66226346-67efee80-e68f-11e9-9521-b9262ce399f6.png)
It just keeps consuming all ram, crashing and then restarting to do the same

**Comment by sean-mcmanus** [comment]
@Novakov Your issue with the IntelliSense process crashing is different from the other issues. We need more info as to what is causing the crash and/or a call stack. We are not aware of any new regression involving the IntelliSense process, but we do have a fix pending for our next release for a high hitting IntelliSense crash, see https://github.com/microsoft/vscode-cpptools/issues/4302 .

**Comment by Novakov** [comment]
@sean-mcmanus OK, thanks for the link. I will try to reproduce my issue in more controlled manner and create new issue if it will be unrelated to the one you metioned.
