### ISSUE TITLE
AArch inline asm: "unknown register name" clobber list

### ISSUE THREAD

**Issue by TishSerg** [microsoft/vscode-cpptools#4382]
**Type: LanguageService**

**The bug**
- OS and Version:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

$ uname -a
Linux serg-VM 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- VS Code Version:
```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-64-generic
```
- C/C++ Extension Version: 0.25.1 (problem exist in v0.23.1 too)
- No other extensions are installed
- AArch-specific (ARM) register names aren't recognized in the `clobber list` of `inline asm` statement. Nevertheless the code successfully compiles and works.

**To Reproduce**

1. Go to any C function body.
2. Paste `asm("mov w0, #0":::"r0");`
3. See error

**Expected behavior**
AArch-specific register names must be recognized just like x86's `eax`, `rax` and so.

**Screenshots**
![image](https://user-images.githubusercontent.com/11420785/66139190-a2fb0f00-e608-11e9-8de6-233963779e89.png)

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I reported it to the VS team at https://developercommunity.visualstudio.com/content/problem/778258/cc-intellisense-shows-unknown-register-name-with-a.html .

It's possible we may also need to add support for ARM IntelliSense mode and -std=gnu11 for all the errors to disappear (we have other issues tracking those).

**Comment by cardiffman** [comment]
During WFH about half the developers I work with have been using VSCode and the other half don't use GUI IDEs. A few of us do Linux kernel module development for ARM and MIPS. There is a macro called get_user that obtains one scalar value from user space, and on ARM it expands to inline assembly referencing r0. Every file that has a get_user macro in gets tagged as a problem.

**Comment by sean-mcmanus** [comment]
@cardiffman If you can edit the macro, you may be able to avoid the errors via surrounding the code in a 
```
#ifndef __INTELLISENSE__
// code we don't handle correctly
#endif
```

**Comment by cardiffman** [comment]
> @cardiffman If you can edit the macro, you may be able to avoid the errors via surrounding the code in a
> 
> ```
> #ifndef __INTELLISENSE__
> // code we don't handle correctly
> #endif
> ```
Interesting idea. It makes sense that you would have a macro defined to help with that.

**Comment by guillep2k** [comment]
Happens the same with ARM7:

cpptools version: **0.28.1**

VSCode version:
```
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

```
gcc --version
gcc (GCC) 4.0.1 (WinARM)
```

```
"C_Cpp.default.compilerArgs": [ "-mcpu=arm7tdmi" ]
```


Snippets:

```
// Simply declaring a variable triggers the error
register int r0 asm("r0");
```

Or declaring registers in the clobber section:
```
asm volatile (
	"mov		ip, %[p1]\n\t"
	[... some mode code ...]
	: /* output */
	: /* input */	[p1]  "r" (portdata)
	: /* clobber */ "r0", "r1", "r2", "r3", "r4", "ip" );
```

**Comment by Prehistoricman** [comment]
![image](https://user-images.githubusercontent.com/5530868/98382707-73a4a600-2043-11eb-9ccf-6850163c0c44.png)

Same issue - I included "eax" just for demonstration. I would have thought that changing intelliSenseMode to "gcc-arm" would fix this. Intellisense is only recognising x86 registers.

**Comment by sean-mcmanus** [comment]
I think the VS issue at https://developercommunity.visualstudio.com/content/problem/778258/cc-intellisense-shows-unknown-register-name-with-a.html may need more upvotes.

**Comment by attzonko** [comment]
I see the same issue when trying to access ARM registers
![image](https://user-images.githubusercontent.com/4975715/108888295-1ddb1600-75c0-11eb-81a1-b2c78f3c41fb.png)

**Comment by guillep2k** [comment]
@RSDuck, as you've created #5381, would you mind upvoting this issue? (it's marked as "more votes needed").

**Comment by Prehistoricman** [comment]
The [Visual Studio issue](https://developercommunity.visualstudio.com/t/cc-intellisense-shows-unknown-register-name-with-a/778258) has been marked as fixed, but as of C/C++ v1.5.1 I am still seeing the issue. Can someone see if it is fixed in Visual Studio?

**Comment by guillep2k** [comment]
> 
> 
> The [Visual Studio issue](https://developercommunity.visualstudio.com/t/cc-intellisense-shows-unknown-register-name-with-a/778258) has been marked as fixed, but as of C/C++ v1.5.1 I am still seeing the issue. Can someone see if it is fixed in Visual Studio?

Perhaps in VS 2022 beta?

**Comment by sean-mcmanus** [comment]
@Prehistoricman It was never fixed. Someone just assigned it the wrong state temporarily. The issue got closed as low priority, but we're still tracking the issue internally and you can upvote this GitHub issue.

**Comment by Victor333Huesca** [comment]
Any updates on this issue? Is it still tracked and planned in a future release?

**Comment by tigert1998** [comment]
avx2 registers like "ymm0" also fails to be recognized.

**Comment by sean-mcmanus** [comment]
@Victor333Huesca It was closed as "low priority" by the VS team. I'm looking into if we can get it re-activated due to our larger number of embedded users and higher upvote count.

**Comment by beaver700nh** [comment]
I'm on Arduino and I'm also getting this, but for `pgm_read_word_near()` which causes the error "unknown register name `'r0'`"

**Comment by sean-mcmanus** [comment]
FYI, I've opened an internal VS issue to track this and mentioned the 12 upvotes.

**Comment by tehKaiN** [comment]
Hi,

I have similar problem, but not in ARM compiler, but in Motorola 68000 one. I see this issue is marked as "Done" in 1.11 - is the fix applicable for ARM only, or does it fix the root of the problem for other architectures too?

**Comment by sean-mcmanus** [comment]
@tehKaiN The fix will work for all architectures.

**Comment by sean-mcmanus** [comment]
This fix is available with 1.11.2 (pre-release): https://github.com/microsoft/vscode-cpptools/releases

**Comment by tehKaiN** [comment]
unfortunately this doesn't work for me under 1.11.4, screenshot taken just now:

![obraz](https://user-images.githubusercontent.com/16180344/180463600-6633b1af-c4d9-490f-a930-122ee4413da9.png)

same thing with `__asm__` directive instead of `__asm`, albeit it formats the register string way nicer.

I'm using ms-vscode.cpptools, ms-vscode.cmake-tools and 68000 GCC compiler bundled with bartmanabyss.amiga-debug extension. I understand that you may not want to set up such exotic configuration - can you give me any pointers on how can I find the point of failure for you?

**Comment by sean-mcmanus** [comment]
@tehKaiN Sorry about that -- looks like the "asm("mov w0, #0":::"r0");" case got fixed but not the other case.

**Comment by sean-mcmanus** [comment]
@tehKaiN I've opened a new issue to track that case: https://github.com/microsoft/vscode-cpptools/issues/9627

**Comment by Victor333Huesca** [comment]
Yes, I do confirm that the inline asm is fixed with arm, thanks!
But, the asm register is still reporting an error on my side too.

_PS: I upvoted the new issue._

**Comment by sean-mcmanus** [comment]
@Victor333Huesca Yes, the error wasn't fixed for register declarations -- we have a potential fix for our next pre-release, pending code review.

**Comment by sean-mcmanus** [comment]
@tehKaiN @Victor333Huesca The register declaration issue is fixed with 1.12.0 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.12.0
