### ISSUE TITLE
Setting intelliSenseEngine to "Disabled" has no effect for folders in a workspace

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4463]
...it only works if the setting is set on the workspace itself (or in the non-multiroot scenario).

Ideally, certain folders could have the language server stuff disabled, but maybe that's too unusual of a scenario to worry about?

**Comment by sean-mcmanus** [comment]
I don't think this will get fixed by the multiroot (and settings) changes, but I'll double check...

**Comment by Colengms** [comment]
@sean-mcmanus  Since we're moving this setting (renamed to "languageServer.enabled") to 'window' scope, it should apply to all folders in a workspace.  Based on the title, is there still an issue in which disabling has 'no effect' (in your multiroot work)?

**Comment by sean-mcmanus** [comment]
Yeah, this is no longer applicable after the settings re-design.

UPDATE: The changed design was reverted.

**Comment by Colengms** [comment]
@sean-mcmanus Is this still an issue?  IntelliSenseEngine is currently set to resource scope.

**Comment by sean-mcmanus** [comment]
Yeah, it's still an issue. Seems low priority though.

**Comment by bobbrow** [comment]
Closing stale issues with low impact and no upvotes.
