### ISSUE TITLE
"Connection to server got closed. Server will not be restarted." after update to 0.26.3insiderX

### ISSUE THREAD

**Issue by jwierzbi** [microsoft/vscode-cpptools#4770]
Issue Type: <b>Bug</b>

Hard for me to say what are the reproduction steps for this issue. It just happens when I have a C project opened. The message pops up periodically every few minutes.

This specifically appears after updating to 0.26.3. I had an 0.26.3-insiders version before and I reverted it to 0.26.2 and the error was gone. Now I updated again because the insiders2 version rolled out and the error is back.

I know there's already #4714 but it was raised against an earlier version which I had no problems with so this might be a different issue.

Extension version: 0.26.3-insiders2
VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:32:17.711Z)
OS version: Linux x64 4.15.0-73-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 2948)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.54GB (1.08GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

Note: The memory above shows that I have 1.08GB free but it's actually more. I'm on Linux and most of the memory is taken by caches. The actual value for free is around 10GB.

**Comment by sean-mcmanus** [comment]
The crash we fixed with 0.26.3-insiders2 was with the IntelliSense process, but you're hitting a main process crash. We aren't aware of any high hitting main process crash, except for an out of memory crash on Windows -- does it appear like the process keeps growing memory usage till it runs out?

Doing a Reset IntelliSense Database might fix things if the database is corrupt in some way.

Can you attach a debugger before the process crashes to get a call stack?

**Comment by jwierzbi** [comment]
> does it appear like the process keeps growing memory usage till it runs out?

I haven't noticed anything out of the ordinary regarding memory usage in my system when this issue happens.

> Doing a Reset IntelliSense Database might fix things if the database is corrupt in some way.

Tried twice and sadly I can still see the error message.

> Can you attach a debugger before the process crashes to get a call stack?

I'm not overly familiar with debugging Electron apps but I dumped the developer tools' console (attached). Hope that helps but if it's not enough I'll try and figure out how to fire up the debugger later.

[vscode_console.log](https://github.com/microsoft/vscode-cpptools/files/3986375/vscode_console.log)

**Comment by jwierzbi** [comment]
I attached GDB to the _Microsoft.VSCode.CPP.Extension.linux_ process and this is the stack trace from the crash: [vscode_bt.log](https://github.com/microsoft/vscode-cpptools/files/3986925/vscode_bt.log).

**Comment by saidganim** [comment]
Having the same issue here. Last night I updated the VSCode C/C++ IntelliSense cpptools  and then started getting the "Connection to server got closed. Server will not be restarted." message periodically with my C project.

**Comment by sean-mcmanus** [comment]
@jwierzbi Thanks a lot for providing that call stack -- that looks like our top hitting main process crash, and it's a regression with 0.26.3-insiders2, but it was below our "crash bar threshold", so we had not investigated it further yet.

But now that it's been user reported we'll try to dig into it next week :)

@saidganim Are you on 0.26.3-insiders2?

**Comment by saidganim** [comment]
@sean-mcmanus  yes, my version is  0.26.3-insiders2

**Comment by sean-mcmanus** [comment]
Setting C_Cpp.updateChannel to "Default" is a workaround until we're able to get a fix.

@jwierzbi Can you set your C_Cpp.loggingLevel to "Debug" and see what file is being parsed when the crash occurs in the output "tag parsing file: ..." in the C/C++ pane? Does the crash happen repeatedly on the same file? We have code that is supposed to skip parsing files that cause parsing crashes the 2nd time, but it's possible that might not be working if the database ends up getting reset from the crash.

@saidganim Without a crash call stack or more repro details, I can't be sure if you're hitting the same crash or a different one.

**Comment by jwierzbi** [comment]
> Does the crash happen repeatedly on the same file?

Yes it does and I have a very simple way to reproduce it now:

```
$ wget http://llvm.org/releases/9.0.0/cfe-9.0.0.src.tar.xz
$ tar xf cfe-9.0.0.src.tar.xz
```

Then Open Folder... _cfe-9.0.0.src_ in VS Code and open _has_include.c_ file. It should crash instantly.

**Comment by sean-mcmanus** [comment]
@jwierzbi Thanks a lot for the repro! It crashes VS as well -- I've filed a bug at https://developercommunity.visualstudio.com/content/problem/866100/vs-crashes-due-to-a-cc-tag-parser-crash-when-openi.html .

I've emailed the developer responsible, but they're OOF for a couple weeks, so I'm not sure if anyone else would be able to fix it before then.

As mentioned previously, our workspace parsing code that runs on startup should avoid auto-parsing that file after the initial crash, but explicitly opening that file will re-trigger the parsing/crash.

**Comment by jwierzbi** [comment]
> I've emailed the developer responsible, but they're OOF for a couple weeks, so I'm not sure if anyone else would be able to fix it before then.

Thanks! It's Christmas after all so that totally expected :).

> As mentioned previously, our workspace parsing code that runs on startup should avoid auto-parsing that file after the initial crash, but explicitly opening that file will re-trigger the parsing/crash.

Sadly but it doesn't seem to work like that in my case. When I open VS Code and load any other C file then I can see the initial error message printed periodically. It seems that the extension restarts the parsing process from the very beginning each time and goes through the whole project again and again.

I think that you should be able to reproduce this behaviour as well. Just open any other file than _has_include.c_. It repeats in less than 60s in my case.

**Comment by sean-mcmanus** [comment]
Yeah, I checked the logs -- the crash occurs too soon after modifying our database, causing our "database safety check" to fail, so on restart we reset the database instead. We'd need to delay the crash long enough for the other thread to pass it's safety check or move the parsing to a different process.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.3-insiders3

**Comment by jwierzbi** [comment]
I can confirm that the issue is gone in my case.

Thank  you very much for fixing it. Feel free to close the issue when you see fit.

**Comment by MarkAllenPhillips** [comment]
Having same issue with VSCode Puppet.  
C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': Invalid argument @ dir_s_mkdir - H:/.puppetlabs/var (Errno::EINVAL)
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:193:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:404:in `create_ancestors'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:389:in `block in initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:388:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:388:in `initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet.rb:163:in `do_initialize_settings_for_run_mode'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet.rb:155:in `initialize_settings'
	from c:/Users/A375484/.vscode/extensions/puppet.puppet-vscode-0.26.1/vendor/languageserver/lib/puppet_languageserver.rb:222:in `init_puppet'
	from c:/Users/A375484/.vscode/extensions/puppet.puppet-vscode-0.26.1/vendor/languageserver/puppet-languageserver:13:in `<main>'
[Info  - 10:08:42 AM] Connection to server got closed. Server will restart.
C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': Invalid argument @ dir_s_mkdir - H:/.puppetlabs/var (Errno::EINVAL)
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:193:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:404:in `create_ancestors'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:389:in `block in initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:388:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:388:in `initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet.rb:163:in `do_initialize_settings_for_run_mode'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet.rb:155:in `initialize_settings'
	from c:/Users/A375484/.vscode/extensions/puppet.puppet-vscode-0.26.1/vendor/languageserver/lib/puppet_languageserver.rb:222:in `init_puppet'
	from c:/Users/A375484/.vscode/extensions/puppet.puppet-vscode-0.26.1/vendor/languageserver/puppet-languageserver:13:in `<main>'
[Info  - 10:08:47 AM] Connection to server got closed. Server will restart.
C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': Invalid argument @ dir_s_mkdir - H:/.puppetlabs/var (Errno::EINVAL)
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:193:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:404:in `create_ancestors'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:389:in `block in initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:388:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:388:in `initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet.rb:163:in `do_initialize_settings_for_run_mode'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet.rb:155:in `initialize_settings'
	from c:/Users/A375484/.vscode/extensions/puppet.puppet-vscode-0.26.1/vendor/languageserver/lib/puppet_languageserver.rb:222:in `init_puppet'
	from c:/Users/A375484/.vscode/extensions/puppet.puppet-vscode-0.26.1/vendor/languageserver/puppet-languageserver:13:in `<main>'
[Info  - 10:08:52 AM] Connection to server got closed. Server will restart.
ERROR: 2020-05-17T14:08:56.953Z Error: connect ETIMEDOUT 10.71.6.18:9119
C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': Invalid argument @ dir_s_mkdir - H:/.puppetlabs/var (Errno::EINVAL)
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:193:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:404:in `create_ancestors'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:389:in `block in initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:388:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:388:in `initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet.rb:163:in `do_initialize_settings_for_run_mode'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet.rb:155:in `initialize_settings'
	from c:/Users/A375484/.vscode/extensions/puppet.puppet-vscode-0.26.1/vendor/languageserver/lib/puppet_languageserver.rb:222:in `init_puppet'
	from c:/Users/A375484/.vscode/extensions/puppet.puppet-vscode-0.26.1/vendor/languageserver/puppet-languageserver:13:in `<main>'
[Info  - 10:08:58 AM] Connection to server got closed. Server will restart.
C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': Invalid argument @ dir_s_mkdir - H:/.puppetlabs/var (Errno::EINVAL)
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:193:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.8/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:404:in `create_ancestors'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:389:in `block in initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:388:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet/settings.rb:388:in `initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet.rb:163:in `do_initialize_settings_for_run_mode'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.15.0-x64-mingw32/lib/puppet.rb:155:in `initialize_settings'
	from c:/Users/A375484/.vscode/extensions/puppet.puppet-vscode-0.26.1/vendor/languageserver/lib/puppet_languageserver.rb:222:in `init_puppet'
	from c:/Users/A375484/.vscode/extensions/puppet.puppet-vscode-0.26.1/vendor/languageserver/puppet-languageserver:13:in `<main>'
[Error - 10:09:03 AM] Connection to server got closed. Server will not be restarted.

**Comment by LIUHUANUCAS** [comment]
# I have the same problem
- version:`April 2020 (version 1.45)`
- `macos ,clang-format version 10.0.0`
- I don't confirm the exactly steps to reproduce it, but the happened time  is that I use the clang-format extension to format my cpp files on save.what's more ,I can not use the format on save when the error has happened.
- the error information as follows:
![image](https://user-images.githubusercontent.com/10096544/82153220-c07ba100-9898-11ea-927e-9e567df07a7d.png)

**Comment by michelleangela** [comment]
@MarkAllenPhillips this repository is for the C/C++ extension. From your logs it looks like the issue is with extension Puppet https://github.com/puppetlabs/puppet-vscode

**Comment by michelleangela** [comment]
@LIUHUANUCAS can you try uninstalling and re-installing the extension with the latest version 0.28.0? If that does not fix the issue, please create a new issue for the latest version of the extension.

**Comment by LIUHUANUCAS** [comment]
> @LIUHUANUCAS can you try uninstalling and re-installing the extension with the latest version 0.28.0? If that does not fix the issue, please create a new issue for the latest version of the extension.

- yeah: sometimes ,I uninstall  and re-install the Clang-Format and cpptools extension, the issue can be solved for a while after un-re install the extension, but the issue happens after a while.
- the Clang-Format extension version is 1.9.0
- the cpptools extension version is 0.28.0

![image](https://user-images.githubusercontent.com/10096544/82337187-1168d200-9a1e-11ea-88d3-9abd9efa8072.png)
![image](https://user-images.githubusercontent.com/10096544/82337820-c1d6d600-9a1e-11ea-886e-1fcff3b350b0.png)

**Comment by MarkAllenPhillips** [comment]
After installing and reinstalling and then restarting the pc, everythings seens to be working fine.
Thanks

**Comment by michelleangela** [comment]
@LIUHUANUCAS I created a new issue at https://github.com/microsoft/vscode-cpptools/issues/5528 for your issue. Please continue to provide info at the thread.
