### ISSUE TITLE
Some files in the database get unnecessarily removed on startup with a configuration provider

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4802]
Using CMake Tools, I'm seeing around 2k files being removed (unnecessarily) from the database on startup and then reparsed. Reproed with 0.26.2 and 0.26.3-insiders2. Might be a regression.

**Comment by Colengms** [comment]
This is because we haven't heard from the custom configuration provider yet.  Other issues related to this scenario that resulted in incorrectly configured TU's have been addressed be ensuring the TU is corrected when the new configuration arrives.  The next step is to give the provider some time to start up before falling back to the cpptools configuration.

**Comment by sean-mcmanus** [comment]
@Colengms I still see this reproing with 0.26.3-insiders3 and our latest code -- from the logging it looks like the correct browse.path is getting used, but the parse_root is operating on a copy of old data.
