### ISSUE TITLE
Variables defined on the same line as a struct causes a discrepancy between the variable and variables with the same type.

### ISSUE THREAD

**Issue by pepsipu** [microsoft/vscode-cpptools#5519]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 19, Linux 5.3.0-51-generic
- VS Code Version: 1.45.1
- C/C++ Extension Version: 0.28.0
- Other extensions you installed (and if the issue persists after disabling them): n/a
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

To produce a bug, create a struct that has a variable defined on the same line, similar to how anonymous structures are defined.
```
struct cool_struct
{
  int a;
  char b;
} a_global_variable;
```

Trying to assign `a_global_variable` to a compound literal casted to `cool_struct` or any instances of `cool_struct` will cause an error. For example,

```
a_global_variable = (struct cool_struct){
  .a = 1,
  .b = 'e',
};
```
causes an error, even though gcc sees this as completely valid.

**Expected behavior**

a_global_variable should be able to be assigned to instances and compound literals that have been casted to cool_struct, but it states the two types are different. This should not be the case.

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 5/17/2020, 9:58:34 PM
Version: 0.28.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "c11",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "clang-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/pepsipu/CLionProjects/rxinOS/sys/idt.c ]:
    /home/pepsipu/CLionProjects/rxinOS/sys/idt.c
Translation Unit Configurations:
[ /home/pepsipu/CLionProjects/rxinOS/sys/idt.c ]:
    Process ID: 17372
    Memory Usage: 14 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/lib/gcc/x86_64-linux-gnu/9/include
        /usr/local/include
        /usr/lib/gcc/x86_64-linux-gnu/9/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
        /home/pepsipu/CLionProjects/rxinOS
    Standard Version: c11
    IntelliSense Mode: gcc-x64
    Other Flags:
        --gcc
        --gnu_version=90201
Total Memory Usage: 14 MB
```
</details>

**Screenshots**

this is where I encountered the bug.
![image](https://user-images.githubusercontent.com/40325571/82175701-79d27a80-9889-11ea-9511-3db1a668a284.png)

**Comment by sean-mcmanus** [comment]
It works for me. Can you provide more repro details? I get that error when I use msvc mode, but not gcc mode.

![image](https://user-images.githubusercontent.com/19859882/82271699-5f51dd00-992d-11ea-9d22-e913c786c6ac.png)

**Comment by pepsipu** [comment]
![image](https://user-images.githubusercontent.com/40325571/82413643-9528bb80-9a2a-11ea-8c19-eb928f26358b.png)
I put the bug causer in the context of my program and it seems to still be present. What information do you need exactly?

**Comment by sean-mcmanus** [comment]
Okay, it's reproing now with Ubuntu 20 and gcc-10 (not sure why it wasn't reproing before on Ubuntu 18 with gcc-9).

**Comment by sean-mcmanus** [comment]
The cause is from code shared with VS so I filed a bug at https://developercommunity.visualstudio.com/content/problem/1042219/cc-intellisense-gives-error-a-value-of-type-struct.html .

**Comment by Colengms** [comment]
This appears to have been addressed.  I no longer get any squiggles for the example code in a .c file, with 1.3.0.  Closing as fixed.

**Comment by arpit-saxena** [comment]
I still see the squiggles for the example code with 1.3.0. (version on extensions page is given as `Version 1.3.0: April 13, 2021`)

![image](https://user-images.githubusercontent.com/14573995/115078331-1b8c9c80-9f1d-11eb-97f7-5cc4f0e04440.png)

**Comment by Colengms** [comment]
Interesting.  The repro is not consistent.  I'm able to cause the error to be cleared by making seemingly unrelated edits to the file, such as adding a line before main(), and moving the cursor to within the initializer list.  (sometimes).

**Comment by sean-mcmanus** [comment]
Yeah, that's that issue with the IntelliSense process randomly clearing errors -- when verifying that an old bug is fixed, you may want to try adding some new lines to make sure the errors don't re-appear. At the time the bug was originally filed the behavior may have been more consistent.

**Comment by Colengms** [comment]
@sean-mcmanus @arpit-saxena  I'm no longer able to repro this issue with 1.6.0, either immediately after launching directly to the source file, opening the source file later, or after making unrelated edits to the source file.  Could one of you re-check this to confirm?

**Comment by arpit-saxena** [comment]
@Colengms Yes I don't see this issue with 1.6.0

**Comment by Colengms** [comment]
Hi @arpit-saxena .  Thanks for confirming.  I'm going to close this as fixed.  If you find a repro, let us know.  :)
