### ISSUE TITLE
Rename Symbol (F2) facility does not work

### ISSUE THREAD

**Issue by EmbeddedBacon** [microsoft/vscode-cpptools#5542]
Type: General

- OS and Version: Windows 10
- VS Code Version: 1.45.1 (user setup)
- C/C++ Extension Version: 0.28.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

In a C project when I try to use the Rename facility by pressing F2 which brings up "Enter to Rename. Shift+Enter to Preview". I didn't know this existed until a friend pointed it out. When I tried the Preview selection it brought up a window on the left side which looked like a search of the selected text.

Now, when I try either the Rename or Preview nothing happens. When through each of the OUTPUT windows to see if there was any tracing, but I didn't see anything. I read on a Stack Overflow post that VSCode support the rename facility for TypeScript and JavaScript, though this was from over two years ago. The keybinding is

{
"key": "f2",
"command": "editor.action.rename",
"when": "editorHasRenameProvider && editorTextFocus && !editorReadonly"
}

I couldn't find the "editorHasRenameProvider" in [Key Bindings for Visual Studio Code](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts) documentation, so as a test I removed the "editorHasRenameProvider". Of course that didn't work.

A number of other co-workers have the same issue. I am not sure if this is VS Code or C/C++ extension issue. How do I fix the rename facility?

Regards,
Mark

Edit: I tried using Rename Symbol using the nodemcu-firmware project from github, but I am seeing the same behavior on my home machine using the same OS, VS Code, and extension version.

**Comment by sean-mcmanus** [comment]
It's normally supposed to work and this is the 1st report we've heard of it not working. Do you have IntelliSense working, i.e. do you get error squiggles with invalid code? 
What does it show when you run C/C++: Log Diagnostics from the Command Palette? Do you see any errors when you open the Help->Toggle Developer Tools->Console?

Does Find All References work?

**Comment by EmbeddedBacon** [comment]
Hello Mr. @sean-mcmanus, I think the IntelliSense is working for the most part.  I did one test and I see the following:

![image](https://user-images.githubusercontent.com/42427056/82518012-38cda680-9ad3-11ea-85a8-b95b4fa46665.png)

I don't normally use the Find All References since it is much slower than just doing a normal Find In All Files, but I did one test and after many seconds I see the following:

![image](https://user-images.githubusercontent.com/42427056/82518148-86e2aa00-9ad3-11ea-83c8-5e5d6455f3e2.png)

I searched the OUTPUT - C/C++ window and searched for "error" (not sure what else to search for).  Mostly saw

Error squiggle count:
Error squiggles will be disabled
Error squiggles are enabled if all header dependencies are resolved

Those were the only one I saw

**Comment by EmbeddedBacon** [comment]
Okay, I was checking the Developer Tools - Console window.  I cleared the contents, though I did save it first, and tried a F2 - Shift Enter.  This was the only items in the console

console.ts:137 [Extension Host] Info Python Extension: 2020-05-20 21:04:18: Cached data exists getEnvironmentVariables, /users/mrhicks/projects/raptor/repo
2console.ts:137 [Extension Host] Info Python Extension: 2020-05-20 21:04:18: > C:\Program Files\Python37\python.exe ~/.vscode-server/extensions/ms-python.python-2020.5.80290/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"

**Comment by EmbeddedBacon** [comment]
Results from running C/C++: Log Diagnostics from the Command Palette, changed the project name though to xxxPrj

```
-------- Diagnostics - 5/20/2020, 9:06:33 PM
Version: 0.28.0
Current Configuration:
{
    "name": "Linux",
    "defines": [],
    "compilerPath": "/opt/BullseyeCoverage/bin/gcc",
    "cppStandard": "c++14",
    "includePath": [
        "${workspaceFolder}/firmware/src/**"
    ],
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/firmware/src/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /users/mrhicks/projects/xxxPrj/repo/firmware/src/mtfw/event/cli/event_cli.c ]:
    /users/mrhicks/projects/xxxPrj/repo/firmware/src/mtfw/event/cli/event_cli.c
    /users/mrhicks/projects/xxxPrj/repo/firmware/src/mtfw/inc/ds_uart_input_context.h
[ /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/uart/cs_uart_mqx_stub.c ]:
    /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/uart/cs_uart_mqx_stub.c
[ /users/mrhicks/projects/xxxPrj/repo/firmware/src/mtfw/ds/uart_input_context/ds_uart_input_context.c ]:
    /users/mrhicks/projects/xxxPrj/repo/firmware/src/mtfw/ds/uart_input_context/ds_uart_input_context.c
    /users/mrhicks/projects/xxxPrj/repo/firmware/src/mtfw/inc/ds_uart_input_context.h
Translation Unit Configurations:
[ /users/mrhicks/projects/xxxPrj/repo/firmware/src/mtfw/event/cli/event_cli.c ]:
    Process ID: 4646
    Memory Usage: 555 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include
        /usr/local/include
        /usr/include
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/sec/aegis5/src/product/xxxPrj/include
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/mtfw/inc
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/include/HAL
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/HALWrapper/cs/inline
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/include/ftl
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/include/cs
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/HAL/inline
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/fe/include
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/ftl/cftl_test/sim/cftl_platform/include
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/include/fe
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/inc
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/include/HAL/rtl/agnisys
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/include
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/psp/arc
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/bsp/common
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/be/include
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/io_mem
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/io_null
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/serial
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/enet/mwsim
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/enet/xemac
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/enet/vmac
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/flashx
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/flashx/istrata
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/i2c
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/spi
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/timers
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/wdt
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/pipe
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/be/hs/scans/inc
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/bsp/xxxPrj
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/common_log
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/ftl/cftl_test/sim/include
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/ftl/cftl_test/sim/cftl_platform/include/alignment_policy/no_align
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/ftl/include
    Standard Version: c11
    IntelliSense Mode: gcc-x64
    Other Flags:
        --gcc
        --gnu_version=40805
[ /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/uart/cs_uart_mqx_stub.c ]:
    Process ID: 5808
    Memory Usage: 12 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include
        /usr/local/include
        /usr/include
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/sec/aegis5/src/product/xxxPrj/include
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/include/cs
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/include
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/psp/arc
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/bsp/common
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/io_mem
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/io_null
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/serial
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/enet/mwsim
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/enet/xemac
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/enet/vmac
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/flashx
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/flashx/istrata
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/i2c
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/spi
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/timers
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/wdt
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/io/pipe
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/bsp/xxxPrj
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/include/HAL
    Standard Version: c11
    IntelliSense Mode: gcc-x64
    Other Flags:
        --gcc
        --gnu_version=40805
[ /users/mrhicks/projects/xxxPrj/repo/firmware/src/mtfw/ds/uart_input_context/ds_uart_input_context.c ]:
    Process ID: 6063
    Memory Usage: 320 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include
        /usr/local/include
        /usr/include
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/mtfw/inc
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/include/HAL
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/include/ftl
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/sec/aegis5/src/product/xxxPrj/include
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/ftl/cftl_test/sim/include
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/ftl/cftl_test/sim/cftl_platform/include
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/include/fe
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/inc
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/include/HAL/rtl/agnisys
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/be/include
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/be/hs/scans/inc
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/common_log
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/HAL/inline
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/ftl/cftl_test/sim/cftl_platform/include/alignment_policy/no_align
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/ftl/include
        /users/mrhicks/projects/xxxPrj/repo/firmware/src/cs/mqx/library/include
    Standard Version: c11
    IntelliSense Mode: gcc-x64
    Other Flags:
        --gcc
        --gnu_version=40805
Total Memory Usage: 887 MB
```

**Comment by sean-mcmanus** [comment]
Yeah, everything looks good from what I see, i.e. Rename should be working.

If you try a simple case with a local var iii in `int main() { int iii; return iii; }` does rename work for that? (make sure "iii" doesn't match any other text in your workspace).

Did rename work with 0.27.1? We changed our Rename UI starting with 0.28.0 to use VS Code's UI instead of the UI similar to the Find All References UI on the left.

@Colengms @michelleangela Any other ideas what why Rename would fail when everything else seems to be working? Or what else to check?

**Comment by EmbeddedBacon** [comment]
@sean-mcmanus, I believe it worked in the previous edition.  At the time it worked for me I was sharing my screen and someone was walking me through the Rename Symbol, given I didn't know it existed, they were surprised it worked on my side since it never worked for them.  Though, given some of your comments there were having some issues with the default parser.  Even though we work on the same code base/project/source files.  So, them having issues with the default parser may be connected, though at the time I didn't know that.

Is there some other logging I can enable or check to gather some information for you?

This is what I have for C/C++ settings:
```
"C_Cpp.loggingLevel":              "Debug",
"C_Cpp.updateChannel":             "Insiders",
"C_Cpp.default.intelliSenseMode":  "gcc-x86",
"C_Cpp.intelliSenseEngine":        "Default",
"C_Cpp.default.includePath": ["${workspaceFolder}/firmware/src/**"],
```
I am trying to some items and try to collect more data for you

**Comment by EmbeddedBacon** [comment]
I saw there was an update to the extension, v0.28.1, so I installed that locally and remotely.  Unfortunately, I still see the same issue.

**Comment by EmbeddedBacon** [comment]
I reverted back to v0.27.1 and was seeing the same thing

![RenameSymbol](https://user-images.githubusercontent.com/42427056/82543717-da231f80-9b08-11ea-90d1-dfff07ba128b.gif)

**Comment by michelleangela** [comment]
@EmbeddedBacon 
Can you confirm that this reproduces with default configurations for VS Code and the extension while using a simple source file such as:
```
void orange()
{}

void blue()
{}

void yellow()
{
    blue();
}

int main()
{
    orange();
    blue();
    return 0;
}
```

**Comment by Colengms** [comment]
Hi @EmbeddedBacon .  It looks like you are using a remoting extension.  I see from an image you posted that there are multiple remoting extensions installed.  Which one are you connecting with?  Does the issue repro with a non-remote project?

I see that you also have a number of other extensions installed.  Does the issue repro with all other extensions disabled?  There may be another extension registering to provide Rename services, and causing the behavior you are seeing.  Our Rename implementation should not result in a 'window on the left side'.

**Comment by EmbeddedBacon** [comment]
@Colengms, I went through and uninstalled each remote extension and test each iteration until I was left with only the C/C++ extension.  Each iteration produced the same results as seen here.

![RenameSymbol_2](https://user-images.githubusercontent.com/42427056/82614223-29566800-9b7c-11ea-8815-3907b5a7b8bc.gif)

**Comment by EmbeddedBacon** [comment]
@Colengc, I had tried a local repo which i mentioned in the original description by using nodemcu-firmware on my home computer using Windows 10 and same version of VS Code and extensions.  Same results.  Granted, I just cloned the nodemcu-firmware repo and tried the Rename Symbol.

**Comment by sean-mcmanus** [comment]
What happens if you create a test.ts file with code
```
let main: boolean;
let sub: boolean = main;
```
and try to rename and rename preview on "main"? If that doesn't work, then it would indicate a problem with VS Code itself.

**Comment by EmbeddedBacon** [comment]
@michelleangela, I tried your test scenario.  I created a new directory, created a main.c file, inserted the code, then went through the process.  Here is the visual test case

![RenameSymbol_3](https://user-images.githubusercontent.com/42427056/82614941-e6958f80-9b7d-11ea-9215-91e0791a0b27.gif)

**Comment by EmbeddedBacon** [comment]
@sean-mcmanus   Here is that test case you described, same behavior, but I am not sure what I should see now. If I recall correctly, Where the list of extension is now, there was a window in the same place that showed what would change if the Rename Preview was selected

![RenameSymbol_4](https://user-images.githubusercontent.com/42427056/82615599-adf6b580-9b7f-11ea-9693-0db647455e90.gif)

**Comment by sean-mcmanus** [comment]
You need to change the name to something different, right? I don't see the original name being changed. Can you try changing the name by adding a 2 or something to the end in the rename popup?

**Comment by EmbeddedBacon** [comment]
Mr. @sean-mcmanus , you are right, I didn't even notice the little box to type in a new string.  That worked with your test case and @michelleangela test case.  Let me go back to my project, perhaps I have been wrong all this time????

**Comment by EmbeddedBacon** [comment]
So sorry, it appears to be user error.  In my original project, after pressing F2 then typing in a new string I see the preview

![image](https://user-images.githubusercontent.com/42427056/82617733-e00b1600-9b85-11ea-9ee5-f18afe0d85c8.png)
