### ISSUE TITLE
Intellisense #include completion does not display package-like foo.bar header files

### ISSUE THREAD

**Issue by vlmillet** [microsoft/vscode-cpptools#5698]
**Type: LanguageService**

**Describe the bug**
- Windows 10
- VS Code Version : 1.46.1
- C/C++ Extension Version: last 0.28.3

package-like files (ex:  `MyEngine.Math.Vector3`) are not displayed in #include because they are interpreted as unrecognized extension while they don't really have extension 

**Steps to reproduce**

type `#include <MyEngine.Math.` in a C++ file with some `MyEngine.Math.Vector3` file existing in include path

**Expected behavior**
I want to be able to customize what files can be displayed in the #include completion. In my case I have extension-less package-like files that contains c++ code but have not a recognized extension (ex : `MyEngine.Math.Vector3`) 
I'm expecting an option that allows me to filter files being displayed in `#include` completion because C++ preprocessor has no constraints relative to file extensions in `#include` directives

**Comment by sean-mcmanus** [comment]
Would showing types associated with "c" or "cpp" in the files.associations be sufficient? Or did you want a setting to show all types? Or did you have some other idea?

**Comment by vlmillet** [comment]
Showing only types associated with c and cpp wouldn’t be enough as there is no efficient way to associate these files except by using a pattern` *.* `and that would pollute every other feature using the file associations.
I think an option just to « display every file on #include completion » would do the job, and maybe being able to enable it only in a list of given include path, that way we could display all files only in some desired folders where we know we only have package-like files or other non standard header files.
Would it be feasible ?

**Comment by sean-mcmanus** [comment]
It's feasible (might have some performance impact).

**Comment by vlmillet** [comment]
When do you think this could be integrated ? What is the policy about 'enhancement' integrations ?
I ask because we are stuck without a workaround right now and cannot really migrate fully to vscode for this reason, even if I'd really want programmers to use it here. 
If someone in your team can guide me on how to make a workaround, that would be great ! at least until the feature ends up in a release, if it does.

**Comment by sean-mcmanus** [comment]
I don't know. It's not a matter of being "integrated" it's a matter of being "changed"/"fixed". The change would have to be done in our closed source cpptools process. I thought this might be a one line change to stop the filtering, but there's something more complicated going on, so I don't know how long it would take to investigate/fix this and we are currently working on higher priority issues (this is the only report we've seen from users using foo.bar style headers).

**Comment by vlmillet** [comment]
Okay I see, thanks for the explanations. 
Can you keep me in touch once it is on going ? 
I still struggle to find a workaround right now except changing all our file organisation which you can guess is not really a good plan !
If you have an idea of a possible workaround/hack to this, please let me know.

**Comment by sean-mcmanus** [comment]
Sure.

**Comment by vlmillet** [comment]
What is the status about the issue right now ?

**Comment by sean-mcmanus** [comment]
I re-tried the one-line fix I tried previously, which didn't work before, and it works now, so it should be available in 1.2.0-insiders unless I we find some other problem with the change.

**Comment by vlmillet** [comment]
Great thanks !

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2

We still exclude hardcoded file types that we associate with source files and don't expect or recommend being `#included`, even though the language doesn't enforce that. It's sort of design trade off -- users could file a feature request to add a setting to make .cpp/.c etc. files appear in the `#include` completion list, but it would need more upvotes.

**Comment by vlmillet** [comment]
I tried and the issue is still there. 
I've created a `foo.bar` file in the root of my includePath, and it doesn't show in the completion list after typing `#include <`
Is there an option or a setting to set up to that it works ?

**Comment by sean-mcmanus** [comment]
You need to reload window after creating the foo.bar because our code for handling the file creation doesn't update the include completion cache unless the created file is extensionless or a known header, i.e. it's a bug -- that looks to be easy to fix for 1.3.0-insiders.

![image](https://user-images.githubusercontent.com/19859882/109357324-e4f8a680-7836-11eb-83f4-982a32fa2afb.png)

**Comment by sean-mcmanus** [comment]
The issue mentioned in my previous comment is fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders . Let us know if you notice any other bugs regarding headers with non-standard extensions.
