### ISSUE TITLE
Don't create browse database when the folder does not have C / C++ source files

### ISSUE THREAD

**Issue by sridmad** [microsoft/vscode-cpptools#6]
from Xaver Hellauer - Review comments on extension's market place page

> > > One thing still needs to be fixed: In my opinion, the extension should not load and produce its helper files when non-C/C++ projects are open.

**Comment by sridmad** [comment]
Fixed in 0.6 if extension

**Comment by niedzielski** [comment]
This issue seems to still exist in VS Code v1.2 for Ubuntu with v0.6.1 of the extension. Here are the repro steps:

``` bash
git clone https://github.com/rndmem/sound-of-water
cd sound-of-water
code .
```

After exiting VS Code, `git status` shows:

```
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

    .vscode/.browse.VC.db

nothing added to commit but untracked files present (use "git add" to track)
```

The project has no C or C++ files and NPM dependencies aren't installed in this example.

``` bash
find -iname \*.c -o -iname \*.cpp -o -iname \*.cxx
```

**Comment by niedzielski** [comment]
Is it possible to reopen this issue be or should should I file a new bug?

**Comment by jgoshi** [comment]
The fix will appear in the next release, version 0.8.0

**Comment by niedzielski** [comment]
Fixed! \o/ Thank you!

**Comment by rkeithhill** [comment]
I'm on 0.8.1 and these two files are still being created on a project (vscode extension project) that is not a C++ project.

**Comment by MeirionHughes** [comment]
I was just about to complain about this; but I think its actually the C# add-on that is doing it for me. 

```
.BROWSE-VC.DB
.BROWSE-VC.DB-shm
.BROWSE-VC.DB-wal
```

**Comment by rkeithhill** [comment]
I dunno.  I uninstalled 0.8.1 of this extension and the problem went away.

**Comment by jgoshi** [comment]
I just looked at the source code. It was fixed, then looks like there was a regression recently. So what you said makes sense. I’ll fix it again for the next release.

**Comment by jgoshi** [comment]
Ok this is fixed and will appear in the next release (0.9.0)
