### ISSUE TITLE
Compiler probe failure with clang and -Xclang arg

### ISSUE THREAD

**Issue by grigorig** [microsoft/vscode-cpptools#6356]
### Brief Issue Summary

Either cmake-tools or cpptools (I'm not quite sure) apparently aren't correctly probing clang on my system, resulting in broken IntelliSense. This only applies if I use precompiled headers in my project. gcc works as expected with precompiled headers.

### Expected:

cmake-tools use my compiler (Kit) configuration and build system information to provide IntelliSense.

### Apparent Behavior:

The C++ log in VSCode shows:

```
Compiler probe command line: "/usr/bin/clang++-10" -fsanitize=undefined -fsanitize=address -g -fPIC -fvisibility=hidden -Wall -Wextra -Wunused -Wignored-qualifiers -Wmissing-braces -Wreturn-type -Wswitch -Wswitch-default -Wuninitialized -Wmissing-field-initializers -Wcast-align -Wmissing-declarations -Wpedantic -Wreorder -Wreturn-stack-address -std=c++17 -Xclang -Xclang /path/to/build/Debug/source/main/CMakeFiles/main.dir/cmake_pch.hxx.pch -Xclang /path/to/build/Debug/source/main/CMakeFiles/main.dir/cmake_pch.hxx  -Wp,-v -E -dD -x c++ -m64 -fno-blocks /dev/null
Done discovering files.
Populate include completion cache.
Discovering files...
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /usr/lib64/clang/10.0.1/include/
Failed to query compiler. Falling back to 32-bit intelliSenseMode.
Compiler probe command line: "/usr/bin/clang++-10" -fsanitize=undefined -fsanitize=address -g -fPIC -fvisibility=hidden -Wall -Wextra -Wunused -Wignored-qualifiers -Wmissing-braces -Wreturn-type -Wswitch -Wswitch-default -Wuninitialized -Wmissing-field-initializers -Wcast-align -Wmissing-declarations -Wpedantic -Wreorder -Wreturn-stack-address -std=c++17 -Xclang -Xclang /path/to/build/Debug/source/main/CMakeFiles/main.dir/cmake_pch.hxx.pch -Xclang /path/to/build/Debug/source/main/CMakeFiles/main.dir/cmake_pch.hxx  -Wp,-v -E -dD -x c++ -m32 -fno-blocks /dev/null
  Processing folder (recursive): /usr/include/
Failed to query compiler. Falling back to no bitness.
Compiler probe command line: "/usr/bin/clang++-10" -fsanitize=undefined -fsanitize=address -g -fPIC -fvisibility=hidden -Wall -Wextra -Wunused -Wignored-qualifiers -Wmissing-braces -Wreturn-type -Wswitch -Wswitch-default -Wuninitialized -Wmissing-field-initializers -Wcast-align -Wmissing-declarations -Wpedantic -Wreorder -Wreturn-stack-address -std=c++17 -Xclang -Xclang /path/to/build/Debug/source/main/CMakeFiles/main.dir/cmake_pch.hxx.pch -Xclang /path/to/build/Debug/source/main/CMakeFiles/main.dir/cmake_pch.hxx  -Wp,-v -E -dD -x c++  -fno-blocks /dev/null
clang-10: warning: /path/to/build/Debug/source/main/CMakeFiles/main.dir/cmake_pch.hxx.pch: previously preprocessed input [-Wunused-command-line-argument]
error: unknown argument: '-Xclang'
```
The main issue here seems to be "-Xclang" twice in sequence, which is incorrect. I'm not sure where it comes from. The compile commands typically have `-Xclang -include -Xclang /path/to/something.pch` to include precompiled headers, so maybe VSCode is doing some strange postprocessing on the compiler flags.

### Platform and Versions

- **Operating System**: Fedora 32
- **CMake Version**: 3.17.4
- **VSCode Version**: 1.50.1
- **CMake Tools Extension Version**: 1.4.2 (cpptools: 1.1.0-insiders2, but same behavior with stable version)
- **Compiler/Toolchain**: clang 10.0.1

**Comment by Colengms** [comment]
The problem appears to be that we aren't handling `-Xclang`, so were not aware that it's a argument pair, and are processing the second part of that arg ("-include"), and removing only that from the probe.

The documentation of clang command line options [here](https://clang.llvm.org/docs/ClangCommandLineReference.html) indicate:

```
-Xclang <arg>
Pass <arg> to the clang compiler
```

It's unclear to me why this is needed.  It seems like all occurrences of -Xclang could simply be stripped.  In what scenarios is it necessary to use -Xclang?

**Comment by grigorig** [comment]
cmake added this a while ago, here's the MR: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/4360
I don't fully understand why, but I haven't looked at this in detail.

I think my immediate problem can simply be solved by always passing through the argument that follows `-Xclang` verbatim?

**Comment by Colengms** [comment]
I can address the issue with the probe failing, but have opened another issue to track parsing include paths out of args passed after -Xclang : https://github.com/microsoft/vscode-cpptools/issues/6359

**Comment by Colengms** [comment]
This appears to be an issue in CMake Tools as well.  The cpptools fix should address the scenario in which the source file is in CMakeLists.txt (can get a custom config).  Source files not in CMakeLists.txt would fall back to a 'custom browse config', where CMake Tools is not handling the args properly.  PR for a potential fix: https://github.com/microsoft/vscode-cmake-tools/pull/1497

**Comment by sean-mcmanus** [comment]
The fix is available in https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.0-insiders3 (not the CMake Tools issue).

**Comment by grigorig** [comment]
Hm... I'm not seeing any changes here with 1.1.0-insiders3. I still see exactly the same issue.

Edit: To clarify, the compiler probe still fails, options are still processed the same way, even after resetting IntelliSense etc.

**Comment by sean-mcmanus** [comment]
@Colengms Can you follow up on this?

**Comment by majaeger** [comment]
I am still hitting the issue in insiders3 as well

**Comment by Colengms** [comment]
I believe we have a fix for this, pending release.  We may release a 1.1.0-insiders4, or we may skip directly to 1.1.0.

**Comment by Colengms** [comment]
@majaeger @grigorig Are you still seeing this issue with 1.1.0-insiders4 ?

**Comment by grigorig** [comment]
Yes, this fixes the problem. Thanks!
