### ISSUE TITLE
cpptools isn't exiting properly on Mac in certain scenarios (infinite loop)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#7026]
When reproing https://github.com/microsoft/vscode-cpptools/issues/7025 on Mac, cpptools doesn't exit properly. It exits correctly on Windows.

See also https://github.com/microsoft/vscode-cpptools/issues/7022

**Comment by sean-mcmanus** [comment]
Also repros on Linux

**Comment by sean-mcmanus** [comment]
Actually, seems to be Mac-only.

**Comment by michelleangela** [comment]
Fix is released in the 1.3.0 release version https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0

**Comment by michelleangela** [comment]
Was this fixed in 1.3.0? there is no "fixed pending" label.

**Comment by sean-mcmanus** [comment]
The underlying issue wasn't fixed, but the bug that triggered the issue was fixed...so I'm not sure if we have an active repro. I moved it to "backlog" in case we want to investigate the issue more later.
