### ISSUE TITLE
'wmic' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by eternalphane** [microsoft/vscode-cpptools#8328]
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 11 Insider Preview Build 22483.1011
- VS Code Version: 1.62.0-insider
- C/C++ Extension Version: 1.7.1
- A clear and concise description of what the bug is:
> Command failed: `wmic process get Name,ProcessId,CommandLine /FORMAT:list`
   'wmic' is not recognized as an internal or external command, operable program or batch file.

**To Reproduce**
`launch.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Attach",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}
```
1. Select `(Windows) Attach` configuration in Debug pane, and press `F5` to start debugging.
2. The error described above popped up.

**Additional context**
WMIC is deprecated in favor of CMI cmdlets in PowerShell as of Windows 10 21H1, and has already been removed from Windows 11 22483. See MicrosoftDocs/win32@9f7ba67.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/edit/1.8.0-insiders

**Comment by chopperg** [comment]
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Attach",
            "type": "C++",
            "request": "attach",
            "Copyright": "${command:pickProcess}"
        }
    ]
}

**Comment by johnfc-soulassembly** [comment]
Still happening for me with version 1.22.1 of the C++ Extension,VSCode 1.96.2 and Windows 11 10.0.26100 Build 26100
