### ISSUE TITLE
C_Cpp: Dim Inactive Regions no longer working in insider build 1.8.0

### ISSUE THREAD

**Issue by Sonicboom247** [microsoft/vscode-cpptools#8478]
Bug type: Language Service

**Describe the bug**
VS Code Version: Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
- C/C++ Extension Version: 1.8.0
- Other extensions you installed (and if the issue persists after disabling them): Platformio, Auto Build Marlin, Material Icon Themes, Python, STM32 for vscode, Github pull request
- If using SSH remote, specify OS of remote machine: none
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
- single project workspace, when C++ intellisense is updated to 1.8.0 inactive region dimming stops functiioning and all code is active (not dimmed), reverting back to 1.7.1 fixes issue.

![unhighlighted](https://user-images.githubusercontent.com/84334417/144252824-a3a16df7-c6fb-4af5-8945-3d843e1f6827.jpg)

**Steps to reproduce**

**Expected behavior**
inactive region dimming 
![1 7 0](https://user-images.githubusercontent.com/84334417/144253349-c8a07837-3083-4876-b97c-550c291d0cec.jpg)

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by Colengms** [comment]
Hi @Sonicboom247 .  Thanks for reporting this.  I can repro the issue.

@sean-mcmanus This appears to be related to changes you made recently, to add `normalize_drive_casing()`.  The drive letter is not capitalized in the `openFileVersions` map on the TypScript side, so the URI received in the `cpptools/inactiveRegions` message no longer matches the map.  Rather than normalize the drive casing to be upper case, perhaps normalize it to be lower case, to ensure all URIs communicated back to VS Code are using the same casing it uses?

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders2 .

**Comment by beanspower** [comment]
Hello expert@sean-mcmanus  
I have same issue here , but it seems that 1.8.0-insiders 2 still cannot solve it.
I use v1.7.1， the issue will be solved.

Version: 1.63.0-insider (user setup)
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-06T21:54:39.104Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by Colengms** [comment]
Hi @beanspower .  Using 1.8.0-insiders2, a simple example is working for me, in both C and C++.

![image](https://user-images.githubusercontent.com/49173979/145329818-e67eebde-ebe8-4bb7-a52a-13950144085f.png)

Does a simple example work properly for you?  If so, and you have a scenario that is not working, please open a new issue for it.

**Comment by Sonicboom247** [comment]
working fine for me using C++, make sure you are updating the correct extension?

**Comment by beanspower** [comment]
Hello @Colengms @Sonicboom247 

Thanks for your help.
When i return back to  v1.7.1, the issue is missing.
And then i update to 1.8.0-in2 , but for now i still cannot reproduce it .
I will try to find way to reproduce it.
When i can do it, i will create a new ticket.
