### ISSUE TITLE
While debugging using VSCode, execution goes into infinite loop.

### ISSUE THREAD

**Issue by aakash0641** [microsoft/vscode-cpptools#8776]
Bug type: Debugger

**Describe the bug**
- OS and Version: Ubuntu 20.04
- VS Code Version: 1.63
- C/C++ Extension Version: v1.8.3
- Other extensions you installed (and if the issue persists after disabling them): CMake tools, C/C++ Extension Pack, C,C++ Themes
- A clear and concise description of what the bug is. Only in debug mode (not during Run-without-debug), the execution goes into infinite loop on stepping into a particular function call using F11/F10/F5. Even though I put a breakpoint explictly inside the function ```constrainedMatching``` (see attached image, line 53) but the control does not reach at that particular line during debug. Instead the execution goes into endless loop. On pressing pause icon, the debug does not stop. Only way is stop press the Stop icon. I had raised this issue with VSCode forum, but they said that the issue is with /extCpp Please see the link https://github.com/microsoft/vscode/issues/142166

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1.The code to produce bug is https://github.com/whoenig/libMultiRobotPlanning
2. Download the code from above link and follow instructions in it to configure and build using CMake in VSCode
3. Start debug mode using CMAKE tools extension in VSCode
4. 
![Screenshot from 2022-02-04 14-31-44](https://user-images.githubusercontent.com/82028192/152539274-8c0470c2-df64-48c6-a300-c529576b8896.png)
Reach the problematic line 53 (as shown in attached snap) which has function call. Press F11 / F10 / F5 and see the endless loop
5. Note that the function call is in a ```hpp``` file. That is, a function, which is defined within hpp file, is called inside the hpp file.

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.
Below is the content of ```launch.json```:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            // "program": "enter program name, for example ${workspaceFolder}/a.out",
            "program": "${command:cmake.launchTargetPath}",
            "args": ["-i", "ifile_1.yaml", "-o", "ofile_1.yaml"],
            // "stopAtEntry": true,
            "justMyCode": false,
            "cwd": "${fileDirname}",
            // "environment": [],
            "environment": [
                {
                    // add the directory where our target was built to the PATHs
                    // it gets resolved by CMake Tools:
                    "name": "PATH",
                    "value": "$PATH:${command:cmake.launchTargetDirectory}"
                }
            ],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "Set Disassembly Flavor to Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

**Comment by WardenGnaw** [comment]
Can you add the following to your `launch.json` and share the output from the Debug Console?
```
logging": { "engineLogging": true, "trace": true, "traceResponse": true }
```

**Comment by TheTrio** [comment]
Was facing the same error. Here's what the I got 

> Stopping due to fatal error: ArgumentException: An item with the same key has already been added. Key: (Microsoft.MIDebugEngine.AD7StackFrame, __for_range)

Here's a screenshot 
![unknown](https://user-images.githubusercontent.com/10794178/152589189-3949f652-dfb5-4ab5-bfc8-baab2bfd0174.png)

VS Code version: 1.64.0

Was able to reproduce the issue on both Windows 10(_C++ extension version 1.8.2_) and Arch (_C++ extension version: 1.8.3 Pre release_)

**Comment by WardenGnaw** [comment]
This seems to be a duplicate of https://github.com/microsoft/vscode-cpptools/issues/8760

Can you downgrade to 1.8.1?

**Comment by TheTrio** [comment]
Yup that does the trick. Thanks!

**Comment by aakash0641** [comment]
@WardenGnaw  I switched C/C++ version to 1.8.1. and issue still persists. So I downgraded it further to  1.7.1 and issue still persists. Can you help please ?

**Comment by aakash0641** [comment]
> Can you add the following to your `launch.json` and share the output from the Debug Console?
> 
> ```
> logging": { "engineLogging": true, "trace": true, "traceResponse": true }
> ```

Please see the below output from the Debug Console:
![Screenshot from 2022-02-05 08-23-16](https://user-images.githubusercontent.com/82028192/152626355-66be45c4-c0a9-4a65-90ab-1f543a80322c.png)

-> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (19547) ->=breakpoint-modified,bkpt={number=\"17\",type=\"breakpoint\",disp=\"keep\",enabled=\"y\",addr=\"0x00005555555780b0\",func=\"libMultiRobotPlanning::NextBestAssignment<unsigned long, Location, libMultiRobotPlanning::Assignment<unsigned long, Location> >::constrainedMatching(std::set<std::pair<unsigned long, Location>, std::less<std::pair<unsigned long, Location> >, std::allocator<std::pair<unsigned long, Location> > > const&, std::set<std::pair<unsigned long, Location>, std::less<std::pair<unsigned long, Location> >, std::allocator<std::pair<unsigned long, Location> > > const&, std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> > const&, std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> > const&, std::map<unsigned long, Location, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, Location> > >&)\",file=\"[/home/aakash/Desktop/code/libMultiRobotPlanning/include/libMultiRobotPlanning/next_best_assignment.hpp]()\",fullname=\"[/home/aakash/Desktop/code/libMultiRobotPlanning/include/libMultiRobotPlanning/next_best_assignment.hpp]()\",line=\"129\",thread-groups=[\"i1\"],times=\"1\",original-location=\"next_best_assignment.hpp:129\"}\n"},"seq":3263}
1: (19547) ->=breakpoint-modified,bkpt={number="17",type="breakpoint",disp="keep",enabled="y",addr="0x00005555555780b0",func="libMultiRobotPlanning::NextBestAssignment<unsigned long, Location, libMultiRobotPlanning::Assignment<unsigned long, Location> >::constrainedMatching(std::set<std::pair<unsigned long, Location>, std::less<std::pair<unsigned long, Location> >, std::allocator<std::pair<unsigned long, Location> > > const&, std::set<std::pair<unsigned long, Location>, std::less<std::pair<unsigned long, Location> >, std::allocator<std::pair<unsigned long, Location> > > const&, std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> > const&, std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> > const&, std::map<unsigned long, Location, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, Location> > >&)",file="[/home/aakash/Desktop/code/libMultiRobotPlanning/include/libMultiRobotPlanning/next_best_assignment.hpp]()",fullname="[/home/aakash/Desktop/code/libMultiRobotPlanning/include/libMultiRobotPlanning/next_best_assignment.hpp]()",line="129",thread-groups=["i1"],times="1",original-location="next_best_assignment.hpp:129"}
--> R (stepIn-41): {"type":"response","request_seq":41,"success":true,"command":"stepIn","body":{},"seq":3265}

**Comment by aakash0641** [comment]
@WardenGnaw As in by Debug Console, there is no error shown, so it seems that the issue I am facing is not same as #8760 . In that case, I request you to re-open this issue and help.

**Comment by sean-mcmanus** [comment]
@aakash0641 Is this issue fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.4 ?

**Comment by aakash0641** [comment]
> @aakash0641 Is this issue fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.4 ?

@sean-mcmanus Apologies for delay in reply. I was not well. The issue is not fixed yet with 1.8.4 version of C/C++ extension. I am attaching couple of snaps below, which has snapshot of debug console, and installation evidence. 
![Screenshot from 2022-02-13 16-57-05](https://user-images.githubusercontent.com/82028192/153751108-f187d526-fe47-4723-95e7-47305e472624.png)
![Screenshot from 2022-02-13 16-57-12](https://user-images.githubusercontent.com/82028192/153751115-ad3d940e-5c6f-4ed6-9c90-411e698104e5.png)
![Screenshot from 2022-02-13 17-03-38](https://user-images.githubusercontent.com/82028192/153751121-59d0d8da-c34a-442a-a4cf-2a02d1c91bfe.png)

**Comment by aakash0641** [comment]
> @aakash0641 Can you please provide the logs in text format instead of images?
> 
> Thank you.

Sure, please find attached a text file having log of debug console. You might have already understood but still I wish to highlight that I had placed a breakpoint within the problematic function, but on pressing either of F11/F10/F5 keys, the debugger does not stop at the inside-breakpoint and it looks like an infinite loop is running (attaching a supporting snap for this too)
[8776_debug_console_output.txt](https://github.com/microsoft/vscode-cpptools/files/8066551/8776_debug_console_output.txt)
![Screenshot from 2022-02-15 12-22-47](https://user-images.githubusercontent.com/82028192/154008733-9e236651-ed0a-4cef-9ccb-1021a98189b4.png)

**Comment by aakash0641** [comment]
> From the logs, it seems like we are waiting for GDB to complete the step-in request.
> 
> Instead of stepping into `constrainedMatching` from `solve`, can you do the following?
> 
> 1. Stop at `solve` before `constrainedMatching` is called.
> 2. Set a breakpoint in `constrainedMatching` the first line, e.g. 136
> 3. Hit F5 to continue to that breakpoint
> 
> Let me know if you can hit the breakpoint in this case.

@WardenGnaw This is exactly what I have done multiple times but unsuccessful to hit the breakpoint set in 1st line of ```constrainedMatching```. I can even show you via a screen-sharing session if you want.

**Comment by WardenGnaw** [comment]
@aakash0641 I am able to reproduce the issue with step-in. However, this is a GDB issue since it occurs without involving VS Code and the C/C++ Extension.
You can report this at https://sourceware.org/bugzilla/

Repro steps:
1. Check out https://github.com/whoenig/libMultiRobotPlanning
2. Install dependencies (see [InstallPackagesUbuntu](https://github.com/whoenig/libMultiRobotPlanning/blob/main/InstallPackagesUbuntu) as an example.
3. Add `-g` to `CMAKE_CXX_FLAGS` in `CMakeLists.txt`
4. Build as described in [README](https://github.com/whoenig/libMultiRobotPlanning#building)
5. Debug with just GDB
   1. `gdb ecbs_ta`
   2.  `break next_best_assignment.hpp:53`
   3. `r -i ../benchmark/8x8_obst12/map_8by8_obst12_agents1_ex0.yaml -o ../ofile_1.yaml`
   4. `continue`
   5. `step`

It will hang after the step call. 
![image](https://user-images.githubusercontent.com/3953714/154575975-80f9eced-296f-4fce-bd86-f72f483c839e.png)

**Comment by aakash0641** [comment]
> @aakash0641 I am able to reproduce the issue with step-in. However, this is a GDB issue since it occurs without involving VS Code and the C/C++ Extension. You can report this at https://sourceware.org/bugzilla/
> 
> Repro steps:
> 
> 1. Check out https://github.com/whoenig/libMultiRobotPlanning
> 2. Install dependencies (see [InstallPackagesUbuntu](https://github.com/whoenig/libMultiRobotPlanning/blob/main/InstallPackagesUbuntu) as an example.
> 3. Add `-g` to `CMAKE_CXX_FLAGS` in `CMakeLists.txt`
> 4. Build as described in [README](https://github.com/whoenig/libMultiRobotPlanning#building)
> 5. Debug with just GDB
>    
>    1. `gdb ecbs_ta`
>    2. `break next_best_assignment.hpp:53`
>    3. `r -i ../benchmark/8x8_obst12/map_8by8_obst12_agents1_ex0.yaml -o ../ofile_1.yaml`
>    4. `continue`
>    5. `step`
> 
> It will hang after the step call. ![image](https://user-images.githubusercontent.com/3953714/154575975-80f9eced-296f-4fce-bd86-f72f483c839e.png)

@WardenGnaw  Thanks for this information. I wish to ask whether there is an alternative to GDB that can be used as a debugger with VSCode and C/C++ Extension ? Also, how to use it ? Meanwhile, I will file the bug in the suggested portal.

**Comment by WardenGnaw** [comment]
You can try building with clang and building lldb-mi on linux, but that is a bit more complicated.

I did notice that you were using GDB version 9.2.

You could try upgrading the version of GDB and see if newer version is experiencing this problem.

**Comment by aakash0641** [comment]
> 

Yes, I upgraded to GDB version 11.2 and this resolved the problem. Thank you so much @WardenGnaw
