### ISSUE TITLE
Variadic template causes "no instance of function template matches the argument list"

### ISSUE THREAD

**Issue by ChrisBlueStone** [microsoft/vscode-cpptools#8985]
Bug type: Language Service

When using a variadic template on a function, the intellisense gets angry whenever the function is called and can't seem to resolve it, displaying the message `no instance of function template matches the argument list`. The "Go to definition" function works fine though, and the program compiles just fine.

I've noticed similar issues reported that trigger the intellisense message I'm getting, but I'm not sure any of them are the result of the same underlying issue.

- OS and Version: Windows 10.0.19043 Build 19043
- VS Code Version: 1.64.2
- C/C++ Extension Version: 1.8.4
- All extensions except for cpptools are disabled, and the issue only manifests when this extension is enabled.
- `g++ --version`: 6.3.0

**Steps to reproduce**

1. Create a new file and paste in example code below.
2. Save the file and notice issue does not manifest.
3. Click File > Open Folder
4. Select the folder where you saved the file.
5. Intellisense will show errors on lines 47 and 54. Program compiles just fine.

**Expected behavior**
No red squiggles.

**Code sample**
```cpp
struct A
{
    template <class Func, typename Output, typename ...Args>
    bool Call(Output &output, Args& ...args, Func f = Func()) const
    {
        return f(output, args...);
    }

    template <class Func, typename Output, typename ...Args>
    bool Call2(Output &output, Func f = Func()) const
    {
        return f(output);
    }

};

struct B
{
    template <class Func, typename Output, typename ...Args>
    static bool Call(Output &output, Args& ...args, Func f = Func())
    {
        return f(output, args...);
    }

    template <class Func, typename Output, typename ...Args>
    static bool Call2(Output &output, Func f = Func())
    {
        return f(output);
    }
};

struct F
{
    bool operator()(unsigned int &i) const
    {
        return 1 != (i = i % 2 ? i * 3 + 1: i >> 1);
    }
};

int main(int argc, char **argv)
{
    unsigned int i = 100;
    
    A a;
    a.Call<F>(i);
//    ~~~~
// no instance of function template "A::Call" matches the argument list C/C++(304)

    a.Call2<F>(i); // OK


    B::Call<F>(i);
//  ~
// no instance of function template "B::Call" matches the argument list C/C++(304)

    B::Call2<F>(i); // OK

    return 0;
}
```

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed VS bug 1495011 for our shared parser.

**Comment by tinlittle** [comment]
This bug can still be reproduced with 

- VS Code Version: 1.72.2
- C/C++ Extension Version: 1.13.3
- Visual Studio 2022 17.4 Preview 5

Red squiggles appear on any instantiation to ```std::views::zip(...)``` since it is a variadic member function template.

Please raise the priority since Microsoft's own STL implementation (albeit C++23) now triggers this bug.

**Comment by sean-mcmanus** [comment]
@tinlittle Okay, thanks for letting us know. I've added your info to the bug and inquired on the status.

**Comment by tinlittle** [comment]
Looks like this issue was fixed in the C/C++ Extension Version 1.14.4.

**Comment by sean-mcmanus** [comment]
@tinlittle I don't think it's fixed. You may be hitting a bug which is preventing the squiggles from appearing.

**Comment by tinlittle** [comment]
@sean-mcmanus you are correct, intellisense stopped working completely. Thanks for the quick response.

**Comment by TheCharlatan** [comment]
I think I run into this same issue with:
```
template <unsigned num_params>
struct Applier{
    const char* const fmt;
    
    Applier(const char* str) : fmt{str} {
    }
};

template <typename... Args>
inline void Format(Applier<sizeof...(Args)> str, const Args&... args) {
}

// Example usage
int main() {
    Format("Test: %d", 404);
}
```
C/C++ Extension Version: 1.21.6

**Comment by tinlittle** [comment]
I believe this has been fixed for real for sometime now.

**Comment by ChrisBlueStone** [comment]
This does seem to be fixed now. I don't recall when I last noticed the issue, but I don't think it was too long ago. Has the fix been verified somewhere?

**Comment by ChrisBlueStone** [comment]
Closing this as it no longer appears to be an issue.
