### ISSUE TITLE
Bugs when a function is called "delete"

### ISSUE THREAD

**Issue by n0on0** [microsoft/vscode-cpptools#9336]
Bug type: Language Service

**Describe the bug**
When a C source code file contains a function with name "delete", it causes some bugs. What I have noticed so far:
1. Attempt to rename the function through Rename Symbol (F2) ends with error "A definition for the selected symbol could not be located."
2. The function is not listed in the dropdown menu with functions. When the cursor is within the function body, it shows just "...".
3. Autoformat (Shift+Alt+F) inserts a space between the function name and the parenthesses (`delete ()`), although it violates the set format style (see below).

Workspace consists only from one folder (with one C file), although the bugs are present regardless of this. 

Note: I'm not sure whether this is a bug in the C/C++ Extenstion or in the VSCode.

- OS and Version: Windows 10 21H2 19044.1706 (x64)
- VS Code Version: 1.67.2
- C/C++ Extension Version: 1.9.8
- Other extensions:
  - Code Runner v0.11.7
  - Remote - WSL v0.66.3
- Remote: WSL2 - Ubuntu 20.04

**Steps to reproduce**
1. Open a C file with function with name "delete"

**Expected behavior**
Opposite of the behaviour described above

**Code sample and logs**

- Code sample
```
#include <stdio.h>
#include <stdlib.h>

void some_function() {
    return;
}

void delete() {
    return;
}

void some_other_function() {
    return;
}

int main(int argc, char const *argv[]) {
    return 0;
}
```

- Configurations in `c_cpp_properties.json`
I didn't find such file, so I'm attaching at least settings from settings.json which relates to the C/C++ Extenstion:
```
"code-runner.runInTerminal": true,
"C_Cpp.clang_format_style": "{ BasedOnStyle: LLVM, UseTab: Never, IndentWidth: 4, TabWidth: 4, BreakBeforeBraces: Attach, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0, AccessModifierOffset: -4, NamespaceIndentation: All, FixNamespaceComments: false }"
```

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 5/20/2022, 3:00:59 AM
Version: 1.9.8
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu17",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /mnt/c/Users/user/Documents/vscode-test/test.c ]:
    /mnt/c/Users/user/Documents/vscode-test/test.c
Translation Unit Configurations:
[ /mnt/c/Users/user/Documents/vscode-test/test.c ]:
    Process ID: 2667
    Memory Usage: 15 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/lib/gcc/x86_64-linux-gnu/9/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=90400
Total Memory Usage: 15 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 2325
```

**Comment by Colengms** [comment]
Hi @n0on0 .  Thanks for reporting this.  It looks like we have a fix for this in development that should be available in our next pre-release, 1.10.3, which we expect to publish early next week.

**Comment by sean-mcmanus** [comment]
This is fixed with 1.10.3 (pre-release).

**Comment by n0on0** [comment]
This bug is still not fixed. All 3 "symptoms" described above are still present.

- VS Code Version: 1.68.1
- C/C++ Extension Version: 1.10.7
- Other extensions:
  - Code Runner v0.11.8
  - Remote - WSL v0.66.3
- Remote: WSL2 - Ubuntu 20.04

**Comment by n0on0** [comment]
This bug is not fully fixed. Rename symbol already works, but the second and third "symptom" (listed above) still persist.

> When a C source code file contains a function with name "delete", it causes some bugs. What I have noticed so far:
> 2. The function is not listed in the dropdown menu with functions. When the cursor is within the function body, it shows just "...".
> 3. Autoformat (Shift+Alt+F) inserts a space between the function name and the parenthesses (delete ()), although it violates the set format style (see below).


- VS Code Version: 1.68.1
- C/C++ Extension Version: 1.10.7
- Other extensions:
  - Code Runner v0.11.8
  - Remote - WSL v0.66.3
- Remote: WSL2 - Ubuntu 20.04

**Comment by sean-mcmanus** [comment]
Issue 2 is a limitation of our tag parser -- it parses code as C++. I've filed an issue on VS at https://developercommunity.visualstudio.com/t/C-language-c-file-IntelliSense-tag-p/10081769 , but I doubt it will get fixed.

Issue 3 is a clang-format bug and doesn't repro with C_Cpp.formatting set to "vcFormat". Seems to be a duplicate of https://github.com/llvm/llvm-project/issues/43678 .

**Comment by sean-mcmanus** [comment]
For issue 3, the previously mentioned issue got fixed, so I filed a new issue at https://github.com/llvm/llvm-project/issues/56249 .
