### ISSUE TITLE
Processing stuck when calling wordexp with certain compilerFragments

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#9688]
@sean-mcmanus 
Recently I have been facing the same problem: formatter stuck when saving (I have auto save and format on save active) and intellisense stuck in the flame icon forever (hovering a variable prints `loading...`).
I don't have a step by step guide to repro the problem because it doesn't happen always. The only thing I do is: edit code and then cmake run (with the cmake-tools ext). Sometimes the bug appears sometimes not.

Here is my call stack (I couldn't get it with the vscode - launch.json guide so I used the lldb one):

<details><summary>call stack</summary>

```
~
❯ lldb -p 79097
(lldb) process attach --pid 79097
Process 79097 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00000001c1e089ec libsystem_kernel.dylib`__read_nocancel + 8
libsystem_kernel.dylib`:
->  0x1c1e089ec <+8>:  b.lo   0x1c1e08a0c               ; <+40>
    0x1c1e089f0 <+12>: pacibsp
    0x1c1e089f4 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1c1e089f8 <+20>: mov    x29, sp
Executable module set to "/Users/$USER/.vscode/extensions/ms-vscode.cpptools-1.12.0-darwin-arm64/bin/cpptools".
Architecture set to: arm64e-apple-macosx-.
(lldb) bt all
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00000001c1e089ec libsystem_kernel.dylib`__read_nocancel + 8
    frame #1: 0x00000001c1d36714 libsystem_c.dylib`__sread + 24
    frame #2: 0x00000001c1d11618 libsystem_c.dylib`_sread + 32
    frame #3: 0x00000001c1d115ac libsystem_c.dylib`__srefill1 + 36
    frame #4: 0x00000001c1d2ca78 libsystem_c.dylib`__srget + 24
    frame #5: 0x00000001c1d3aba0 libsystem_c.dylib`getc + 72
    frame #6: 0x00000001c1db381c libc++.1.dylib`std::__1::__stdinbuf<char>::__getchar(bool) + 160
    frame #7: 0x0000000104df47e4 cpptools`std::__1::basic_istream<char, std::__1::char_traits<char> >& std::__1::getline<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, char) + 148
    frame #8: 0x0000000104db764c cpptools`vscode::message_handler::main_loop() + 1644
    frame #9: 0x0000000104db5e38 cpptools`main + 288
    frame #10: 0x000000010666d08c dyld`start + 520
  thread #2
    frame #0: 0x00000001c1e0cc20 libsystem_kernel.dylib`kevent + 8
    frame #1: 0x0000000105634e58 cpptools`uv__io_poll + 724
    frame #2: 0x000000010562e4c0 cpptools`uv_run + 372
    frame #3: 0x00000001055f7608 cpptools`msvc::loop_t::run_loop() + 64
    frame #4: 0x00000001055fa6a8 cpptools`msvc::thread_t::invoker_t<void (*)(std::__1::shared_ptr<msvc::loop_t>), std::__1::shared_ptr<msvc::loop_t>&>::invoke() + 40
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #3
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104d9e914 cpptools`void std::__1::condition_variable_any::wait<std::__1::unique_lock<std::__1::mutex> >(std::__1::unique_lock<std::__1::mutex>&) + 100
    frame #4: 0x0000000104eb9238 cpptools`vscode::thread_pool::do_work(unsigned long) + 340
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #4
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104d9e914 cpptools`void std::__1::condition_variable_any::wait<std::__1::unique_lock<std::__1::mutex> >(std::__1::unique_lock<std::__1::mutex>&) + 100
    frame #4: 0x0000000104eb9238 cpptools`vscode::thread_pool::do_work(unsigned long) + 340
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #5
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104d9e914 cpptools`void std::__1::condition_variable_any::wait<std::__1::unique_lock<std::__1::mutex> >(std::__1::unique_lock<std::__1::mutex>&) + 100
    frame #4: 0x0000000104eb9238 cpptools`vscode::thread_pool::do_work(unsigned long) + 340
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #6
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104d9e914 cpptools`void std::__1::condition_variable_any::wait<std::__1::unique_lock<std::__1::mutex> >(std::__1::unique_lock<std::__1::mutex>&) + 100
    frame #4: 0x0000000104eb9238 cpptools`vscode::thread_pool::do_work(unsigned long) + 340
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #7
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104d9e914 cpptools`void std::__1::condition_variable_any::wait<std::__1::unique_lock<std::__1::mutex> >(std::__1::unique_lock<std::__1::mutex>&) + 100
    frame #4: 0x0000000104eb9238 cpptools`vscode::thread_pool::do_work(unsigned long) + 340
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #8
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104d9e914 cpptools`void std::__1::condition_variable_any::wait<std::__1::unique_lock<std::__1::mutex> >(std::__1::unique_lock<std::__1::mutex>&) + 100
    frame #4: 0x0000000104eb9238 cpptools`vscode::thread_pool::do_work(unsigned long) + 340
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #9
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104d9e914 cpptools`void std::__1::condition_variable_any::wait<std::__1::unique_lock<std::__1::mutex> >(std::__1::unique_lock<std::__1::mutex>&) + 100
    frame #4: 0x0000000104eb9238 cpptools`vscode::thread_pool::do_work(unsigned long) + 340
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #10
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104d9e914 cpptools`void std::__1::condition_variable_any::wait<std::__1::unique_lock<std::__1::mutex> >(std::__1::unique_lock<std::__1::mutex>&) + 100
    frame #4: 0x0000000104eb9238 cpptools`vscode::thread_pool::do_work(unsigned long) + 340
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #11
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93320 libc++.1.dylib`std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
    frame #3: 0x0000000104d9ecc8 cpptools`std::__1::cv_status std::__1::condition_variable_any::wait_until<std::__1::unique_lock<std::__1::mutex>, std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&) + 268
    frame #4: 0x0000000104ebab1c cpptools`unsigned int msvc::bitset_event_t::wait_for_any_set<long long, std::__1::ratio<1l, 1000l> >(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&, unsigned int) + 112
    frame #5: 0x0000000104eba9f0 cpptools`msvc::thread_t::invoker_t<vscode::thread_pool::thread_pool()::$_0>::invoke() + 164
    frame #6: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #7: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #12
    frame #0: 0x00000001c1e0cc20 libsystem_kernel.dylib`kevent + 8
    frame #1: 0x0000000105634e58 cpptools`uv__io_poll + 724
    frame #2: 0x000000010562e4c0 cpptools`uv_run + 372
    frame #3: 0x00000001055f7608 cpptools`msvc::loop_t::run_loop() + 64
    frame #4: 0x00000001055fa6a8 cpptools`msvc::thread_t::invoker_t<void (*)(std::__1::shared_ptr<msvc::loop_t>), std::__1::shared_ptr<msvc::loop_t>&>::invoke() + 40
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #13
    frame #0: 0x00000001c1e089ec libsystem_kernel.dylib`__read_nocancel + 8
    frame #1: 0x00000001c1d6e930 libsystem_c.dylib`wordexp + 2220
    frame #2: 0x000000010561bc20 cpptools`msvc::parse_arguments(msvc::basic_zstring_view<char>) + 60
    frame #3: 0x0000000104d64538 cpptools`cpp_properties::set_custom_browse_path(vscode::WorkspaceBrowseConfiguration const&) + 768
    frame #4: 0x0000000104dceed0 cpptools`vscode::message_handler::cpptools_didChangeCustomBrowseConfiguration(vscode::CustomBrowseConfigurationParams) + 124
    frame #5: 0x0000000104dbc07c cpptools`vscode::message_handler::dispatch(vscode::vscode_client_message&&, vscode::vscode_server_message&, vscode::message_handler::msg_proc_thread_token) + 10016
    frame #6: 0x0000000104db9890 cpptools`vscode::message_handler::handle_message(vscode::vscode_client_message&&, vscode::message_handler::msg_proc_thread_token) + 52
    frame #7: 0x0000000104e27268 cpptools`std::__1::__function::__func<vscode::message_handler::main_loop()::$_5, std::__1::allocator<vscode::message_handler::main_loop()::$_5>, void ()>::operator()() + 1996
    frame #8: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #9: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #14
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104e282c8 cpptools`vscode::message_deque<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, false>::pop_impl(bool) + 92
    frame #4: 0x0000000104e2817c cpptools`std::__1::__function::__func<vscode::message_handler::main_loop()::$_6, std::__1::allocator<vscode::message_handler::main_loop()::$_6>, void ()>::operator()() + 48
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #15
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104e29904 cpptools`vscode::message_deque<vscode::folding_ranges_params, false>::pop_impl(bool) + 92
    frame #4: 0x0000000104e2973c cpptools`std::__1::__function::__func<vscode::message_handler::main_loop()::$_9, std::__1::allocator<vscode::message_handler::main_loop()::$_9>, void ()>::operator()() + 80
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #16
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104e28d70 cpptools`vscode::message_deque<vscode::browse_engine_update_action, false>::pop_impl(bool) + 84
    frame #4: 0x0000000104e2860c cpptools`std::__1::__function::__func<vscode::message_handler::main_loop()::$_7, std::__1::allocator<vscode::message_handler::main_loop()::$_7>, void ()>::operator()() + 156
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #17
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104e29e3c cpptools`vscode::message_deque<vscode::vscode_client_message, false>::pop_impl(bool) + 96
    frame #4: 0x0000000104e29cf4 cpptools`std::__1::__function::__func<vscode::message_handler::main_loop()::$_10, std::__1::allocator<vscode::message_handler::main_loop()::$_10>, void ()>::operator()() + 68
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #18
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104e29e3c cpptools`vscode::message_deque<vscode::vscode_client_message, false>::pop_impl(bool) + 96
    frame #4: 0x0000000104e29ff4 cpptools`std::__1::__function::__func<vscode::message_handler::main_loop()::$_11, std::__1::allocator<vscode::message_handler::main_loop()::$_11>, void ()>::operator()() + 68
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #19
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104e2a5b8 cpptools`vscode::message_deque<vscode::message_handler::parse_file_entry, true>::pop_impl(bool) + 92
    frame #4: 0x0000000104e2a1a4 cpptools`std::__1::__function::__func<vscode::message_handler::main_loop()::$_12, std::__1::allocator<vscode::message_handler::main_loop()::$_12>, void ()>::operator()() + 112
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #20
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104e29e3c cpptools`vscode::message_deque<vscode::vscode_client_message, false>::pop_impl(bool) + 96
    frame #4: 0x0000000104e2aaf4 cpptools`std::__1::__function::__func<vscode::message_handler::main_loop()::$_13, std::__1::allocator<vscode::message_handler::main_loop()::$_13>, void ()>::operator()() + 68
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #21
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93320 libc++.1.dylib`std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
    frame #3: 0x0000000104e2aeb8 cpptools`vscode::message_deque<int, false>::pop_impl(bool, int&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >) + 148
    frame #4: 0x0000000104e2ad6c cpptools`std::__1::__function::__func<vscode::message_handler::main_loop()::$_14, std::__1::allocator<vscode::message_handler::main_loop()::$_14>, void ()>::operator()() + 316
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #22
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104d9e914 cpptools`void std::__1::condition_variable_any::wait<std::__1::unique_lock<std::__1::mutex> >(std::__1::unique_lock<std::__1::mutex>&) + 100
    frame #4: 0x0000000104e2b208 cpptools`std::__1::__function::__func<vscode::message_handler::main_loop()::$_15, std::__1::allocator<vscode::message_handler::main_loop()::$_15>, void ()>::operator()() + 196
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #23
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000104e29518 cpptools`vscode::message_deque<int, false>::pop_impl(bool) + 84
    frame #4: 0x0000000104e29440 cpptools`std::__1::__function::__func<vscode::message_handler::main_loop()::$_8, std::__1::allocator<vscode::message_handler::main_loop()::$_8>, void ()>::operator()() + 52
    frame #5: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #6: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #24
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x000000010563ba7c cpptools`uv_cond_wait + 12
    frame #3: 0x000000010562aebc cpptools`worker + 112
    frame #4: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #25
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x000000010563ba7c cpptools`uv_cond_wait + 12
    frame #3: 0x000000010562aebc cpptools`worker + 112
    frame #4: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #26
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x000000010563ba7c cpptools`uv_cond_wait + 12
    frame #3: 0x000000010562aebc cpptools`worker + 112
    frame #4: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #27
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x000000010563ba7c cpptools`uv_cond_wait + 12
    frame #3: 0x000000010562aebc cpptools`worker + 112
    frame #4: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
  thread #28
    frame #0: 0x00000001c1e0a270 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001c1e4483c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001c1d93284 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000105442604 cpptools`run_tag_parser() + 348
    frame #4: 0x00000001053d5f2c cpptools`process_translation_unit(char const*, int, an_exported_template_file*) + 912
    frame #5: 0x00000001050516b8 cpptools`cfe_main(int, char**) + 136
    frame #6: 0x00000001053fc2b4 cpptools`cfe_main_exception_handler(int, char**) + 12
    frame #7: 0x00000001050517a4 cpptools`edg_main(int, char**) + 12
    frame #8: 0x0000000105446048 cpptools`antlr_parse_routine() + 488
    frame #9: 0x000000010561b7f4 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #10: 0x00000001c1e4426c libsystem_pthread.dylib`_pthread_start + 148
(lldb) exit
Quitting LLDB will detach from one or more processes. Do you really want to proceed: [Y/n] y
```

</details>

_Originally posted by @lucasaf04 in https://github.com/microsoft/vscode-cpptools/issues/9631#issuecomment-1205032803_

**Comment by sean-mcmanus** [comment]
@lucasaf04 Your issue appears different. Our main thread is stuck calling the wordexp system call. Are you able to provide the Custom Browse Configuration logging in the C/C++ logging window after setting C_Cpp.loggingLevel to "Debug", in particular the compilerFragments section?

**Comment by Colengms** [comment]
Hi @lucasaf04 .  It looks like our call to the OS api function `wordexp` is simply not returning. I'm not able easily to reproduce the issue on my mac with the same compilerFragments.  The call to `wordexp` is used to resolve compilerFragments in the same way that the current shell would, such as to remove shell quoting and escaping.  https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/wordexp.3.html

The compilerFragments in your logs are not unusual.  They don't even contain shell quoting or escaping.  And we're not yet getting reports about this issue from other Mac users.  Is there anything unusual about how the shell is configured on your system?

**Comment by sean-mcmanus** [comment]
Yeah, same here.

**Comment by sean-mcmanus** [comment]
Our team isn't able to repro the issue.

@Colengms Has anyone tried the repro with the .zshenv? I did not.

**Comment by Colengms** [comment]
@v-ericawu When you tried to repro this, were you able to set up an environment that leveraged the provided `.zshenv` file?

**Comment by v-ericawu** [comment]
@Colengms IntelliSense loads normally after setting the .zshenv file:
![image](https://user-images.githubusercontent.com/78774400/187182501-927af003-32cb-406c-b56d-b604bc2fbe50.png)

**Comment by albertcaldas84** [comment]
Anyone knows any workaround for these hangs? I'm having them so often (every minute or so) that this is hintering development completely. Killing the cpptools-srv doesn't work anymore. Can I help with more callstacks or something?

**Comment by sean-mcmanus** [comment]
What Mac OS version is everyone using who is hitting this?

It seems like a bug with the Mac OS, since it's stuck inside their implementation of wordexp, and in their documentation I don't see any information on why wordexp would get stuck: https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/wordexp.3.html . Can you file a bug on your OS? We haven't gotten any bug reports from Linux users.

Maybe we could add some workaround for this Mac bug via running it in a separate thread and cancelling it after a timeout.

**Comment by sean-mcmanus** [comment]
Are you able to build/run this sample program that uses wordexp, i.e. are you able to make it get stuck somehow via passing in the arguments that we're using in your compilerFragments (in your logging). It works for me and doesn't get stuck (using macOS 12.4), i.e. it keeps logging 0.

```cpp
#include <wordexp.h>
#include <iostream>

int main()
{
    wordexp_t worde;
    const char numargs = 24;
    const char *strs[numargs] = {
        "-g -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk",
        "-fcolor-diagnostics",
        "-I/opt/homebrew/opt/llvm/include",
        "-I'/opt/homebrew/opt/llvm/include'",
        "-I\"/opt/homebrew/opt/llvm/include\"",
        "-I\\\\\"/opt/homebrew/opt/llvm/include\\\\\"",
        "-Wall",
        "-Weffc++",
        "-Wextra",
        "-Wpedantic",
        "-Wshadow",
        "-Wunused",
        "-Wsign-conversion",
        "-Wnon-virtual-dtor",
        "-Wold-style-cast",
        "-Wcast-align",
        "-Woverloaded-virtual",
        "-Wconversion",
        "-Wnull-dereference",
        "-Wdouble-promotion",
        "-Wformat=2",
        "-Wimplicit-fallthrough",
        "-Werror",
        "-std=c++11"};
    int argn = 0;
    while (true)
    {
        int i = wordexp(strs[argn++ % numargs], &worde, 0); // maybe replace 0 with WRDE_NOCMD?
        wordfree(&worde);
        if (i != 0)
            break;
        std::cout << i << std::endl;
    }
    return 0;
}
```

The docs say "The wordexp() function attempts to detect input that would cause commands to be execute", so if it's getting stuck on that code, we can try passing in WRDE_NOCMD as a potential workaround.

FYI, I found a bug with wordfree wasn't being call on error conditions, but I'm not seeing that cause it to get stuck.

**Comment by sean-mcmanus** [comment]
Yes, we're looking into potentially adding Mac-only input logging and disabling commands for 1.13.1. By stuck, I mean wordexp isn't returning.

Yeah, we decided against calling wordfree on errors, since it looks like the API only intends wordfree to be called on non-error conditions.

**Comment by sean-mcmanus** [comment]
Okay, it appears stuck on the single call to wordexp.

**Comment by albertcaldas84** [comment]
Any news on this?

**Comment by sean-mcmanus** [comment]
@albertcaldas84 Yeah, we have some changes related to this for our next 1.13.1 update, but it's been delayed this past week.

**Comment by sean-mcmanus** [comment]
We've published a version with wordexp-related updates (Mac-only): 1.13.1: https://github.com/microsoft/vscode-cpptools/releases/tag/v1.13.1 -- we made some minor changes that are always enabled, but I'm guessing those won't fix the issue, so to enable the other changes we added you need to set C_Cpp.experimentalFeatures to "enabled" (no other experimental features will get enabled currently) -- that will disable command expansion for wordexp in case that is the cause. If the issue is not fixed with that, then set C_Cpp.loggingLevel to hidden value of "7" (in the settings json editor) to cause "wordexp input: " logging to appear in the C/C++ log which could help identify if there are particular inputs to wordexp that are causing the issue, and those inputs could potentially be used for getting a repro of the bug.

**Comment by albertcaldas84** [comment]
Hi!
Enabling the experimental feature doesn't fix the issue unfortunately. 

`frame #0: 0x00000001a1b0aa0c libsystem_kernel.dylib`__read_nocancel + 8
    frame #1: 0x00000001a1a70930 libsystem_c.dylib`wordexp + 2220
    frame #2: 0x00000001058c53f0 cpptools`msvc::parse_arguments(msvc::basic_zstring_view<char>, bool) + 108
    frame #3: 0x0000000104fdc794 cpptools`compiler_info::parse_arguments(msvc::basic_zstring_view<char>) + 160
    frame #4: 0x0000000104ffdc5c cpptools`cpp_properties::set_custom_browse_path(vscode::WorkspaceBrowseConfiguration const&) + 764
    frame #5: 0x000000010506ab9c cpptools`vscode::message_handler::cpptools_didChangeCustomBrowseConfiguration(vscode::CustomBrowseConfigurationParams) + 124
    frame #6: 0x0000000105057cf8 cpptools`vscode::message_handler::dispatch(vscode::vscode_client_message&&, vscode::vscode_server_message&, vscode::message_handler::msg_proc_thread_token) + 10308
    frame #7: 0x00000001050553e8 cpptools`vscode::message_handler::handle_message(vscode::vscode_client_message&&, vscode::message_handler::msg_proc_thread_token) + 52
    frame #8: 0x00000001050c445c cpptools`std::__1::__function::__func<vscode::message_handler::main_loop()::$_7, std::__1::allocator<vscode::message_handler::main_loop()::$_7>, void ()>::operator()() + 1996
    frame #9: 0x00000001058c4f94 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #10: 0x00000001a1b4626c libsystem_pthread.dylib`_pthread_start + 148`

Will increase the logging to 7.

**Comment by albertcaldas84** [comment]
Awesome! Trying it with experimental feature on.

**Comment by albertcaldas84** [comment]
Still hanging:
```
thread #15
    frame #0: 0x00000001a1b0aa0c libsystem_kernel.dylib`__read_nocancel + 8
    frame #1: 0x00000001a1a70930 libsystem_c.dylib`wordexp + 2220
    frame #2: 0x00000001058453f0 cpptools`msvc::parse_arguments(msvc::basic_zstring_view<char>, bool) + 108
    frame #3: 0x0000000104f5c794 cpptools`compiler_info::parse_arguments(msvc::basic_zstring_view<char>) + 160
    frame #4: 0x0000000104f7dc5c cpptools`cpp_properties::set_custom_browse_path(vscode::WorkspaceBrowseConfiguration const&) + 764
    frame #5: 0x0000000104feab9c cpptools`vscode::message_handler::cpptools_didChangeCustomBrowseConfiguration(vscode::CustomBrowseConfigurationParams) + 124
    frame #6: 0x0000000104fd7cf8 cpptools`vscode::message_handler::dispatch(vscode::vscode_client_message&&, vscode::vscode_server_message&, vscode::message_handler::msg_proc_thread_token) + 10308
    frame #7: 0x0000000104fd53e8 cpptools`vscode::message_handler::handle_message(vscode::vscode_client_message&&, vscode::message_handler::msg_proc_thread_token) + 52
    frame #8: 0x000000010504445c cpptools`std::__1::__function::__func<vscode::message_handler::main_loop()::$_7, std::__1::allocator<vscode::message_handler::main_loop()::$_7>, void ()>::operator()() + 1996
    frame #9: 0x0000000105844f94 cpptools`msvc::thread_helper_t::thread_entry(void*) + 28
    frame #10: 0x00000001a1b4626c libsystem_pthread.dylib`_pthread_start + 148
```

will enable logging.

**Comment by albertcaldas84** [comment]
[wordexp_hang_logging_7.txt](https://github.com/microsoft/vscode-cpptools/files/9663044/wordexp_hang_logging_7.txt)

**Comment by sean-mcmanus** [comment]
Logging indicates that the call to wordexp("-std=c++17") is getting stuck. All the other calls to wordexp seem fine too. So there doesn't appear to be anything obviously wrong going on. Maybe we just need to add a timeout/cancel.

**Comment by sean-mcmanus** [comment]
The fix for https://github.com/microsoft/vscode-cpptools/issues/9882 may have a side effect of fixing (or reducing the occurrence of) this issue by not repeatedly calling wordexp on the same inputs.

**Comment by sean-mcmanus** [comment]
Your logging shows it get stuck on the 18th call to wordexp -- is the call that gets stuck random? i.e. sometimes is sooner or later? If so, that would indicate there is some race condition, possibly due to the other IntelliSense thread doing process creation work that could interfere with wordexp's internal process creation if they happen to occur at the same time.

**Comment by albertcaldas84** [comment]
Often it gets stuck in 5 minutes, but sometimes in 20. Seems pretty random.

**Comment by sean-mcmanus** [comment]
Yeah, we have a change for 1.13.2 that should improve or fix this (our target is next Tuesday).

**Comment by Zingam** [comment]
I also experience such issue on macOS. Just hovering the mouse over something to see the details can result in the "Loading..." hover and the flame icon in the status bar is stuck on Updating IntelliSense forever.

**Comment by sean-mcmanus** [comment]
@Zingam Yeah, we believe a significant number of Mac users are randomly hitting this, most of whom probably aren't aware they're hitting this particular bug. I'm not 100% sure you're hitting this or not without knowing the cpptools call stacks, but you should know after we release the fix.

**Comment by sean-mcmanus** [comment]
https://github.com/microsoft/vscode-cpptools/releases/tag/v1.13.2 has a change that may reduce the occurrence of this but it's not fixed yet. Setting C_Cpp.experimentalFeatures to true may fix this, but we're still running tests to determine if that's true or not.

**Comment by albertcaldas84** [comment]
Ok, will get it. Thanks! Anything you want us to test?

**Comment by sean-mcmanus** [comment]
Our testing indicates it's fixed when C_Cpp.experimentalFeatures is set to true, so we'll move those changes to the non-experimental case for 1.13.3.

**Comment by H-G-Hristov** [comment]
With 1.13.2 I still happened that I was unable to cmd+click to a definition of a Core Foundation type (Apple SDK header).
There was no stuck flame.

After I restarted VSCode the issue fixed itself.

Is cmd+click  issue related to the wordexp issue?

**Comment by sean-mcmanus** [comment]
@H-G-Hristov That sounds like a different issue. If wordexp is stuck then all IntelliSense operations would be stuck and wordexp would be on a call stack. If only Go to Definition doesn't work that could be caused by something else. Are you able to provide more repro info or logging or a call stack? It sounds like it's random?

**Comment by albertcaldas84** [comment]
I confirm that I haven't had any hang in the whole morning. Thanks sean :)

**Comment by H-G-Hristov** [comment]
I notices that the release notes changed from "Fixed and reduced" to "Reduced" is this still not fixed fully?

**Comment by sean-mcmanus** [comment]
The fix is available with 1.13.3 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.13.3 -- @H-G-Hristov with 1.13.2 the experimentalFeatures setting had to be set in order for it to be fully fixed (otherwise it was just "reduced").

**Comment by sean-mcmanus** [comment]
This has been fixed with insiders for over a month, but it's not available in non-insiders: https://github.com/microsoft/vscode-cpptools/releases/tag/v1.13.6
